In [1]:
import copy
import functools
import glob
import math
import pickle
import scipy
import sklearn
import warnings

warnings.filterwarnings('ignore')

import itertools
import graphviz as gr
import numpy as np
import os
import pandas as pd
import statsmodels.formula.api as smf
import statsmodels.api as sm
import seaborn as sns


from matplotlib import style
from matplotlib import pyplot as plt
from pprint import pprint
from scipy import stats, special
from sklearn import datasets, mixture
from sklearn.metrics import confusion_matrix
from sklearn.preprocessing import StandardScaler
from tqdm import tqdm

from scipy.stats import ttest_ind


from urllib.request import urlopen
import json
with urlopen('https://raw.githubusercontent.com/plotly/datasets/master/geojson-counties-fips.json') as response:
    counties = json.load(response)

import plotly.express as px
import plotly.figure_factory as ff

%matplotlib inline

style.use("fivethirtyeight")
pd.set_option("display.max_columns", 6)

np.random.seed(0)
pd.set_option('display.max_columns', None)

import dask
import dask.dataframe as dd
from dask.distributed import Client

### Import Historical Data and Census Data

In [2]:
dp_df = pd.read_csv("../data/CDPHE_TLGRF_historical.csv")

In [3]:
dp_df

,fips,county_x,state_x,date.x,tau.hat,log_rolled_cases,shifted_log_rolled_cases,rolled_cases,shifted_rolled_cases,predictor,delta cases,capacity,rank_unfiltered,changepoint,outbreak,rank_filtered,delta_ranked
0,8031.0,Denver,Colorado,2020-03-18,0.253478,3.306363,4.857595,27.285714,128.714286,6.916333,101.428571,1.0,1.0,0.0,0.0,1.0,1.0
1,8037.0,Eagle,Colorado,2020-03-18,0.246840,3.235873,4.406719,25.428571,82.000000,6.276791,56.571429,1.0,2.0,0.0,0.0,2.0,2.0
2,8031.0,Denver,Colorado,2020-03-19,0.267161,3.547151,5.058972,34.714286,157.428571,9.274309,122.714286,1.0,1.0,0.0,0.0,1.0,1.0
3,8037.0,Eagle,Colorado,2020-03-19,0.253065,3.438585,4.561368,31.142857,95.714286,7.881172,64.571429,1.0,2.0,0.0,0.0,2.0,2.0
4,8031.0,Denver,Colorado,2020-03-20,0.250975,3.774402,5.250776,43.571429,190.714286,10.935347,147.142857,1.0,1.0,0.0,0.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3235,8029.0,Delta,Colorado,2022-12-23,-0.017627,4.460970,4.252569,86.571429,70.285714,-1.525969,-16.285714,1.0,19.0,0.0,0.0,11.0,12.0
3236,8081.0,Moffat,Colorado,2022-12-23,-0.035139,3.809832,3.509411,45.142857,33.428571,-1.586254,-11.714286,1.0,20.0,0.0,0.0,12.0,11.0
3237,8067.0,La Plata,Colorado,2022-12-23,-0.016677,5.125663,4.924143,168.285714,137.571429,-2.806479,-30.714286,1.0,26.0,0.0,0.0,13.0,14.0
3238,8083.0,Montezuma,Colorado,2022-12-23,-0.029646,4.751124,4.550865,115.714286,94.714286,-3.430459,-21.000000,1.0,28.0,1.0,1.0,14.0,13.0
3239,8041.0,El Paso,Colorado,2022-12-23,-0.014133,8.037682,7.816302,3095.428571,2480.714286,-43.746290,-614.714286,1.0,40.0,0.0,0.0,15.0,15.0

### Exclude dates where there is not enough TLGRF information to make decision

In [4]:
CDPHE_decisions = dp_df[dp_df["changepoint"] == 1]
DP_dates = sorted(CDPHE_decisions["date.x"].unique())
TLGRF_decisions = dp_df[dp_df["date.x"].isin(DP_dates)]
TLGRF_decisions = TLGRF_decisions[TLGRF_decisions["rank_filtered"] <= TLGRF_decisions["capacity"]]
CDPHE_decision_count = pd.DataFrame(CDPHE_decisions.groupby("date.x")["changepoint"].count())
TLGRF_decision_count = pd.DataFrame(TLGRF_decisions.groupby("date.x")["changepoint"].count())

# Obtain dates where TLGRF total != CDPHE total
decision_counts = pd.merge(CDPHE_decision_count, TLGRF_decision_count, on="date.x")
decision_counts = decision_counts.rename(columns={"changepoint_x":"CDPHE_counts", "changepoint_y":"TLGRF_counts"})
excluded_dates = decision_counts[decision_counts["CDPHE_counts"] != decision_counts["TLGRF_counts"]].index
filtered_DP_dates = sorted(list(set(DP_dates) - set(excluded_dates)))
#DP_dates

### CDPHE's and TLGRF's Decisions

In [5]:
filtered_dp_df = dp_df[dp_df["date.x"].isin(filtered_DP_dates)]
#filtered_dp_df = dp_df
TLGRF_decision_mask = filtered_dp_df["rank_filtered"] <= filtered_dp_df["capacity"]
filtered_dp_df["TLGRF_decision"] = TLGRF_decision_mask.astype(int)
filtered_dp_df["CDPHE_decision"] = filtered_dp_df["changepoint"].astype(int)
filtered_dp_df

,fips,county_x,state_x,date.x,tau.hat,log_rolled_cases,shifted_log_rolled_cases,rolled_cases,shifted_rolled_cases,predictor,delta cases,capacity,rank_unfiltered,changepoint,outbreak,rank_filtered,delta_ranked,TLGRF_decision,CDPHE_decision
10,8031.0,Denver,Colorado,2020-03-25,0.214118,4.857595,6.035481,128.714286,418.000000,27.560029,289.285714,1.0,1.0,1.0,1.0,1.0,1.0,1,1
11,8041.0,El Paso,Colorado,2020-03-25,0.270288,4.110874,5.390376,61.000000,219.285714,16.487597,158.285714,1.0,2.0,0.0,0.0,2.0,2.0,0,0
12,8037.0,Eagle,Colorado,2020-03-25,0.190914,4.406719,5.307560,82.000000,201.857143,15.654948,119.857143,1.0,3.0,0.0,0.0,3.0,3.0,0,0
13,8035.0,Douglas,Colorado,2020-03-25,0.218179,3.575551,4.670155,35.714286,106.714286,7.792108,71.000000,1.0,7.0,0.0,0.0,4.0,4.0,0,0
14,8051.0,Gunnison,Colorado,2020-03-25,0.239097,3.279837,4.317488,26.571429,75.000000,6.353157,48.428571,1.0,9.0,0.0,0.0,5.0,5.0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3235,8029.0,Delta,Colorado,2022-12-23,-0.017627,4.460970,4.252569,86.571429,70.285714,-1.525969,-16.285714,1.0,19.0,0.0,0.0,11.0,12.0,0,0
3236,8081.0,Moffat,Colorado,2022-12-23,-0.035139,3.809832,3.509411,45.142857,33.428571,-1.586254,-11.714286,1.0,20.0,0.0,0.0,12.0,11.0,0,0
3237,8067.0,La Plata,Colorado,2022-12-23,-0.016677,5.125663,4.924143,168.285714,137.571429,-2.806479,-30.714286,1.0,26.0,0.0,0.0,13.0,14.0,0,0
3238,8083.0,Montezuma,Colorado,2022-12-23,-0.029646,4.751124,4.550865,115.714286,94.714286,-3.430459,-21.000000,1.0,28.0,1.0,1.0,14.0,13.0,0,1
3239,8041.0,El Paso,Colorado,2022-12-23,-0.014133,8.037682,7.816302,3095.428571,2480.714286,-43.746290,-614.714286,1.0,40.0,0.0,0.0,15.0,15.0,0,0

In [6]:
CDPHE_decisions = filtered_dp_df[filtered_dp_df["CDPHE_decision"] == 1]
TLGRF_decisions = filtered_dp_df[filtered_dp_df["TLGRF_decision"] == 1]

CDPHE_decision_count = pd.DataFrame(CDPHE_decisions.groupby("date.x")["changepoint"].count())
TLGRF_decision_count = pd.DataFrame(TLGRF_decisions.groupby("date.x")["changepoint"].count())
CDPHE_decision_count["changepoint"].agg(["sum","count"]), TLGRF_decision_count["changepoint"].agg(["sum","count"])

(sum      165
 count    145
 Name: changepoint, dtype: int64,
 sum      165
 count    145
 Name: changepoint, dtype: int64)

In [7]:
filtered_dp_df_old = filtered_dp_df[filtered_dp_df["date.x"] <= "2021-09-01"]
CDPHE_decisions_old = filtered_dp_df_old[filtered_dp_df_old["CDPHE_decision"] == 1]
TLGRF_decisions_old = filtered_dp_df_old[filtered_dp_df_old["TLGRF_decision"] == 1]

CDPHE_decision_count_old = pd.DataFrame(CDPHE_decisions_old.groupby("date.x")["changepoint"].count())
TLGRF_decision_count_old = pd.DataFrame(TLGRF_decisions_old.groupby("date.x")["changepoint"].count())
CDPHE_decision_count_old["changepoint"].agg(["sum","count"]), TLGRF_decision_count_old["changepoint"].agg(["sum","count"])

filtered_dp_df_old

,fips,county_x,state_x,date.x,tau.hat,log_rolled_cases,shifted_log_rolled_cases,rolled_cases,shifted_rolled_cases,predictor,delta cases,capacity,rank_unfiltered,changepoint,outbreak,rank_filtered,delta_ranked,TLGRF_decision,CDPHE_decision
10,8031.0,Denver,Colorado,2020-03-25,0.214118,4.857595,6.035481,128.714286,418.000000,27.560029,289.285714,1.0,1.0,1.0,1.0,1.0,1.0,1,1
11,8041.0,El Paso,Colorado,2020-03-25,0.270288,4.110874,5.390376,61.000000,219.285714,16.487597,158.285714,1.0,2.0,0.0,0.0,2.0,2.0,0,0
12,8037.0,Eagle,Colorado,2020-03-25,0.190914,4.406719,5.307560,82.000000,201.857143,15.654948,119.857143,1.0,3.0,0.0,0.0,3.0,3.0,0,0
13,8035.0,Douglas,Colorado,2020-03-25,0.218179,3.575551,4.670155,35.714286,106.714286,7.792108,71.000000,1.0,7.0,0.0,0.0,4.0,4.0,0,0
14,8051.0,Gunnison,Colorado,2020-03-25,0.239097,3.279837,4.317488,26.571429,75.000000,6.353157,48.428571,1.0,9.0,0.0,0.0,5.0,5.0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1483,8091.0,Ouray,Colorado,2021-08-30,0.023396,3.362358,3.479040,28.857143,32.428571,0.675143,3.571429,2.0,39.0,0.0,0.0,21.0,19.0,0,0
1484,8055.0,Huerfano,Colorado,2021-08-30,0.021689,3.337294,3.301114,28.142857,27.142857,0.610394,-1.000000,2.0,40.0,0.0,0.0,22.0,20.0,0,0
1485,8003.0,Alamosa,Colorado,2021-08-30,-0.003395,4.178773,4.529523,65.285714,92.714286,-0.221655,27.428571,2.0,44.0,1.0,1.0,23.0,4.0,0,1
1486,8111.0,San Juan,Colorado,2021-08-30,-0.011466,3.526361,3.247047,34.000000,25.714286,-0.389857,-8.285714,2.0,45.0,0.0,0.0,24.0,24.0,0,0
1487,8029.0,Delta,Colorado,2021-08-30,-0.007182,4.435906,4.411932,84.428571,82.428571,-0.606393,-2.000000,2.0,46.0,0.0,0.0,25.0,21.0,0,0

In [34]:
#unfiltered_dp_df = dp_df[dp_df["date.x"].isin(DP_dates)]
unfiltered_CDPHE_decisions = dp_df[dp_df["changepoint"] == 1]
unfiltered_CDPHE_decisions = unfiltered_CDPHE_decisions[unfiltered_CDPHE_decisions["date.x"] < "2021-09-30s"]

unfiltered_dp_df["CDPHE_decision"] = unfiltered_dp_df["changepoint"]
unfiltered_dp_df["TLGRF_decision"] = 0

unfiltered_DP_dates = sorted(unfiltered_CDPHE_decisions["date.x"].unique())
unfiltered_TLGRF_decisions = unfiltered_dp_df[unfiltered_dp_df["date.x"].isin(unfiltered_DP_dates)]
unfiltered_TLGRF_decisions = unfiltered_TLGRF_decisions[unfiltered_TLGRF_decisions["rank_filtered"] <= unfiltered_TLGRF_decisions["capacity"]]
unfiltered_TLGRF_decisions["TLGRF_decision"] = 1
unfiltered_dp_df.update(unfiltered_TLGRF_decisions)

unfiltered_CDPHE_decision_count = pd.DataFrame(unfiltered_CDPHE_decisions.groupby("date.x")["changepoint"].count())
unfiltered_TLGRF_decision_count = pd.DataFrame(unfiltered_TLGRF_decisions.groupby("date.x")["changepoint"].count())
unfiltered_CDPHE_decision_count["changepoint"].agg(["sum","count"]), unfiltered_TLGRF_decision_count["changepoint"].agg(["sum","count"])

(sum      99
 count    83
 Name: changepoint, dtype: int64,
 sum      107
 count     83
 Name: changepoint, dtype: int64)

In [9]:
unfiltered_dp_df

,fips,county_x,state_x,date.x,tau.hat,log_rolled_cases,shifted_log_rolled_cases,rolled_cases,shifted_rolled_cases,predictor,delta cases,capacity,rank_unfiltered,changepoint,outbreak,rank_filtered,delta_ranked,CDPHE_decision,TLGRF_decision
6,8031.0,Denver,Colorado,2020-03-23,0.228447,4.446007,5.749393,85.285714,314.000000,19.483248,228.714286,2.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0
7,8037.0,Eagle,Colorado,2020-03-23,0.198125,4.120198,5.068005,61.571429,158.857143,12.198821,97.285714,2.0,2.0,0.0,0.0,2.0,4.0,0.0,1.0
8,8041.0,El Paso,Colorado,2020-03-23,0.270250,3.415382,5.114566,30.428571,166.428571,8.223314,136.000000,2.0,3.0,0.0,0.0,3.0,2.0,0.0,0.0
9,8059.0,Jefferson,Colorado,2020-03-23,0.201594,3.630039,5.056246,37.714286,157.000000,7.602956,119.285714,2.0,4.0,1.0,1.0,4.0,3.0,1.0,0.0
10,8031.0,Denver,Colorado,2020-03-25,0.214118,4.857595,6.035481,128.714286,418.000000,27.560029,289.285714,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3235,8029.0,Delta,Colorado,2022-12-23,-0.017627,4.460970,4.252569,86.571429,70.285714,-1.525969,-16.285714,1.0,19.0,0.0,0.0,11.0,12.0,0.0,0.0
3236,8081.0,Moffat,Colorado,2022-12-23,-0.035139,3.809832,3.509411,45.142857,33.428571,-1.586254,-11.714286,1.0,20.0,0.0,0.0,12.0,11.0,0.0,0.0
3237,8067.0,La Plata,Colorado,2022-12-23,-0.016677,5.125663,4.924143,168.285714,137.571429,-2.806479,-30.714286,1.0,26.0,0.0,0.0,13.0,14.0,0.0,0.0
3238,8083.0,Montezuma,Colorado,2022-12-23,-0.029646,4.751124,4.550865,115.714286,94.714286,-3.430459,-21.000000,1.0,28.0,1.0,1.0,14.0,13.0,1.0,0.0
3239,8041.0,El Paso,Colorado,2022-12-23,-0.014133,8.037682,7.816302,3095.428571,2480.714286,-43.746290,-614.714286,1.0,40.0,0.0,0.0,15.0,15.0,0.0,0.0

### Calculate Binary Classification Performance

In [10]:
def binary_classification_performance(df, outcome_col="rank_filtered", predictor_col="TLGRF_decision"):
    # Compute TP, TN, FP, FN
    selected_df = df[df[predictor_col]==1]
    
    Results_Thresh = pd.DataFrame()
    #Total
    Total_Decision_Set = df.groupby('date.x')[outcome_col].count()
    Results_Thresh["Total"] = Total_Decision_Set
    #P
    P = df.groupby('date.x')["capacity"].max()
    Results_Thresh["P"] = P
    #TP
    TP = selected_df.groupby('date.x').apply(lambda x: (x[outcome_col] <= len(x)).sum())
    Results_Thresh["TP"] = TP
    #FP = FN
    FP = selected_df.groupby('date.x').apply(lambda x: (x[outcome_col] > len(x)).sum())
    Results_Thresh["FP"] = FP
    Results_Thresh["FN"] = FP
    #N
    Results_Thresh["N"] = Results_Thresh["Total"] - Results_Thresh["P"]
    Results_Thresh["TN"] = Results_Thresh["N"] - Results_Thresh["FN"]
    #TN
    Results_Thresh = Results_Thresh[["Total", "P", "N", "TP", "FP", "FN", "TN"]]
    
    TP = Results_Thresh.sum()["TP"]
    FP = Results_Thresh.sum()["FP"]
    FN = Results_Thresh.sum()["FN"]
    TN = Results_Thresh.sum()["TN"]


    PPV = Results_Thresh.sum()["TP"]/(Results_Thresh.sum()["TP"] + Results_Thresh.sum()["FP"])
    FPV = Results_Thresh.sum()["FP"]/(Results_Thresh.sum()["TN"] + Results_Thresh.sum()["FP"])
    TPR = Results_Thresh.sum()["TP"]/(Results_Thresh.sum()["TP"] + Results_Thresh.sum()["FN"])
    TNR = Results_Thresh.sum()["TN"]/(Results_Thresh.sum()["TN"] + Results_Thresh.sum()["FP"])

    Precision = Results_Thresh.sum()["TP"] / (Results_Thresh.sum()["TP"] + Results_Thresh.sum()["FP"])
    Recall = Results_Thresh.sum()["TP"] / (Results_Thresh.sum()["TP"] + Results_Thresh.sum()["FN"])
    F1 = 2 * Precision * Recall / (Precision + Recall)

    # create a pandas dataframe from the confusion matrix values
    confusion_table = pd.DataFrame({'actual_positive': [1, 1, 0, 0], 'predicted_positive': [0, 1, 0, 1], 'count': [FN, TP, TN, FP]})

    # create a pivot table to represent the confusion matrix
    confusion_matrix = pd.pivot_table(confusion_table, values='count', index=['actual_positive'], columns=['predicted_positive'])

    # set the column and index names of the pivot table
    confusion_matrix.columns.name = 'Predicted Label'
    confusion_matrix.index.name = 'Actual Label'
    #confusion_matrix = confusion_matrix.T


    print("PPV={}, FPV={}\nTPR={}, TNR={}\nF1={}".format(PPV, FPV, TPR, TNR, F1))
    print(Results_Thresh.sum())
    confusion_matrix
    
    return Results_Thresh, (PPV, FPV, TPR, TNR, F1), confusion_matrix

In [11]:
binary_classification_performance(filtered_dp_df, outcome_col="delta_ranked", predictor_col="CDPHE_decision")

PPV=0.08484848484848485, FPV=0.07347931873479319
TPR=0.08484848484848485, TNR=0.9265206812652068
F1=0.08484848484848485
Total    2220.0
P         165.0
N        2055.0
TP         14.0
FP        151.0
FN        151.0
TN       1904.0
dtype: float64

(            Total    P     N  TP  FP  FN    TN
 date.x
 2020-03-25      5  1.0   4.0   1   0   0   4.0
 2020-03-30      5  1.0   4.0   0   1   1   3.0
 2020-04-09      8  1.0   7.0   0   1   1   6.0
 2020-04-21      7  1.0   6.0   1   0   0   6.0
 2020-04-28      8  1.0   7.0   0   1   1   6.0
 ...           ...  ...   ...  ..  ..  ..   ...
 2022-12-01     17  1.0  16.0   0   1   1  15.0
 2022-12-09     17  1.0  16.0   1   0   0  16.0
 2022-12-12     16  1.0  15.0   0   1   1  14.0
 2022-12-16     17  1.0  16.0   0   1   1  15.0
 2022-12-23     15  1.0  14.0   0   1   1  13.0

 [145 rows x 7 columns],
 (0.08484848484848485,
  0.07347931873479319,
  0.08484848484848485,
  0.9265206812652068,
  0.08484848484848485),
 Predicted Label       0      1
 Actual Label
 0                1904.0  151.0
 1                 151.0   14.0)

In [12]:
binary_classification_performance(filtered_dp_df, outcome_col="delta_ranked", predictor_col="TLGRF_decision")

PPV=0.6909090909090909, FPV=0.024817518248175182
TPR=0.6909090909090909, TNR=0.9751824817518249
F1=0.6909090909090909
Total    2220.0
P         165.0
N        2055.0
TP        114.0
FP         51.0
FN         51.0
TN       2004.0
dtype: float64

(            Total    P     N  TP  FP  FN    TN
 date.x
 2020-03-25      5  1.0   4.0   1   0   0   4.0
 2020-03-30      5  1.0   4.0   1   0   0   4.0
 2020-04-09      8  1.0   7.0   1   0   0   7.0
 2020-04-21      7  1.0   6.0   1   0   0   6.0
 2020-04-28      8  1.0   7.0   1   0   0   7.0
 ...           ...  ...   ...  ..  ..  ..   ...
 2022-12-01     17  1.0  16.0   1   0   0  16.0
 2022-12-09     17  1.0  16.0   0   1   1  15.0
 2022-12-12     16  1.0  15.0   0   1   1  14.0
 2022-12-16     17  1.0  16.0   0   1   1  15.0
 2022-12-23     15  1.0  14.0   0   1   1  13.0

 [145 rows x 7 columns],
 (0.6909090909090909,
  0.024817518248175182,
  0.6909090909090909,
  0.9751824817518249,
  0.6909090909090909),
 Predicted Label       0      1
 Actual Label
 0                2004.0   51.0
 1                  51.0  114.0)

### Validation for Old Manuscript

In [35]:
binary_classification_performance(unfiltered_dp_df[unfiltered_dp_df["date.x"] <= "2021-09-01"], outcome_col="delta_ranked", predictor_col="TLGRF_decision")

PPV=0.6989247311827957, FPV=0.03160270880361174
TPR=0.6989247311827957, TNR=0.9683972911963883
F1=0.6989247311827957
Total    979.0
P         93.0
N        886.0
TP        65.0
FP        28.0
FN        28.0
TN       858.0
dtype: float64

(            Total    P     N  TP  FP  FN    TN
 date.x
 2020-03-23      4  2.0   2.0   1   1   1   1.0
 2020-03-25      5  1.0   4.0   1   0   0   4.0
 2020-03-30      5  1.0   4.0   1   0   0   4.0
 2020-04-09      8  1.0   7.0   1   0   0   7.0
 2020-04-21      7  1.0   6.0   1   0   0   6.0
 ...           ...  ...   ...  ..  ..  ..   ...
 2021-08-03     15  1.0  14.0   1   0   0  14.0
 2021-08-04     14  1.0  13.0   1   0   0  13.0
 2021-08-25     25  1.0  24.0   1   0   0  24.0
 2021-08-26     24  2.0  22.0   2   0   0  22.0
 2021-08-30     25  2.0  23.0   1   1   1  22.0

 [74 rows x 7 columns],
 (0.6989247311827957,
  0.03160270880361174,
  0.6989247311827957,
  0.9683972911963883,
  0.6989247311827957),
 Predicted Label      0     1
 Actual Label
 0                858.0  28.0
 1                 28.0  65.0)

In [36]:
binary_classification_performance(unfiltered_dp_df[unfiltered_dp_df["date.x"] <= "2021-09-01"], outcome_col="delta_ranked", predictor_col="CDPHE_decision")

PPV=0.09090909090909091, FPV=0.09029345372460497
TPR=0.09090909090909091, TNR=0.909706546275395
F1=0.09090909090909091
Total    979.0
P         93.0
N        886.0
TP         8.0
FP        80.0
FN        80.0
TN       806.0
dtype: float64

(            Total    P     N  TP  FP  FN    TN
 date.x
 2020-03-23      4  2.0   2.0   0   1   1   1.0
 2020-03-25      5  1.0   4.0   1   0   0   4.0
 2020-03-30      5  1.0   4.0   0   1   1   3.0
 2020-04-09      8  1.0   7.0   0   1   1   6.0
 2020-04-21      7  1.0   6.0   1   0   0   6.0
 ...           ...  ...   ...  ..  ..  ..   ...
 2021-08-03     15  1.0  14.0   0   1   1  13.0
 2021-08-04     14  1.0  13.0   0   1   1  12.0
 2021-08-25     25  1.0  24.0   0   1   1  23.0
 2021-08-26     24  2.0  22.0   0   2   2  20.0
 2021-08-30     25  2.0  23.0   0   2   2  21.0

 [74 rows x 7 columns],
 (0.09090909090909091,
  0.09029345372460497,
  0.09090909090909091,
  0.909706546275395,
  0.09090909090909091),
 Predicted Label      0     1
 Actual Label
 0                806.0  80.0
 1                 80.0   8.0)

In [15]:
(1921+20+97+97, 2004+114+51+51)

(2135, 2220)

### Investigate Sources of Discrepancy

In [16]:
### Load in Combined Census Data
augmented_data_path = "../../data/augmented_us-counties-states_latest.csv"
#augmented_df = (dd.read_csv(augmented_data_path, assume_missing=True)).compute()
augmented_df = (dd.read_csv(augmented_data_path, assume_missing=True))
augmented_colorado_df = augmented_df[augmented_df["state"]=="Colorado"]
augmented_colorado_df = augmented_colorado_df.compute()

In [17]:
augmented_colorado_df = augmented_colorado_df.sort_values(by=["date","fips"])
augmented_colorado_df

,fips,date,county,state,cases,deaths,datetime,days_from_start,rolled_cases,LAT,LON,AREA_SQMI,E_TOTPOP,E_HU,E_HH,E_POV,E_UNEMP,E_PCI,E_NOHSDP,E_AGE65,E_AGE17,E_DISABL,E_SNGPNT,E_MINRTY,E_LIMENG,E_MUNIT,E_MOBILE,E_CROWD,E_NOVEH,E_GROUPQ,EP_POV,MP_POV,EP_UNEMP,MP_UNEMP,EP_PCI,MP_PCI,EP_NOHSDP,MP_NOHSDP,EP_AGE65,MP_AGE65,EP_AGE17,MP_AGE17,EP_DISABL,MP_DISABL,EP_SNGPNT,MP_SNGPNT,EP_MINRTY,MP_MINRTY,EP_LIMENG,MP_LIMENG,EP_MUNIT,MP_MUNIT,EP_MOBILE,MP_MOBILE,EP_CROWD,MP_CROWD,EP_NOVEH,MP_NOVEH,EP_GROUPQ,MP_GROUPQ,EPL_POV,EPL_UNEMP,EPL_PCI,EPL_NOHSDP,SPL_THEME1,RPL_THEME1,EPL_AGE65,EPL_AGE17,EPL_DISABL,EPL_SNGPNT,SPL_THEME2,RPL_THEME2,EPL_MINRTY,EPL_LIMENG,SPL_THEME3,RPL_THEME3,EPL_MUNIT,EPL_MOBILE,EPL_CROWD,EPL_NOVEH,EPL_GROUPQ,SPL_THEME4,RPL_THEME4,SPL_THEMES,RPL_THEMES,F_POV,F_UNEMP,F_PCI,F_NOHSDP,F_THEME1,F_AGE65,F_AGE17,F_DISABL,F_SNGPNT,F_THEME2,F_MINRTY,F_LIMENG,F_THEME3,F_MUNIT,F_MOBILE,F_CROWD,F_NOVEH,F_GROUPQ,F_THEME4,F_TOTAL,E_UNINSUR,EP_UNINSUR,MP_UNINSUR,E_DAYPOP,State_FIPS_Code,State_of_emergency_issued,State_of_emergency_lifted,Date_closed_K-12_public_schools,Closed_day_cares,Reopen_day_cares,Date_banned_visitors_to_nursing_homes,Stay_at_home/_shelter_in_place,Stay_at_home_order'_issued_but_did_not_specifically_restrict_movement_of_the_general_public,End/relax_stay_at_home/shelter_in_place,Closed_other_non-essential_businesses,Closed_businesses_overnight,Began_to_reopen_businesses,Religious_gatherings_exempt_without_clear_social_distance_mandate*,Face_mask_mandate_in_public_spaces,Face_mask_mandate_x2,Face_mask_mandate_enforced_by_fines,Face_mask_mandate_enforced_by_criminal_charge/citation,No_legal_enforcement_of_face_mask_mandate,Face_mask_mandate_for_employees_of_public-facing_businesses,Ended_face_mask_mandate,Ended_face_mask_mandate_x2,Attempted_to_prevent_local_governments_from_implementing_face_mask_orders,Banned_local_mask_mandates,Liquor_stores_remained_open,Allowed_restaurants_to_sell_takeout_alcohol,Allowed_restaurants_to_deliver_alcohol,Firearm_sellers_remained_open,Cannabis_dispensaries_considered_essential_business,Closed_restaurants_except_take_out,Reopen_restaurants,Initially_reopen_restaurants_for_outdoor_dining_only,Closed_gyms,Reopened_gyms,Closed_movie_theaters,Reopened_movie_theaters,Closed_Bars,Reopen_bars,Reopened_hair_salons/barber_shops,Reopened_religious_gatherings,Reopened_other_non-essential_retail,Allowed_businesses_to_reopen_overnight,Began_to_reclose_bars,Closed_bars_(x2),Closed_movie_theaters_(x2),Closed_hair_salons/barber_shops_(x2),Closed_gyms_(x2),Closed_restaurants_(x2),Reopened_restaurants_(x2),Reopened_bars_(x2),Reopened_gyms_(x2),Reopened_hair_salons/barber_shops_(x2),Reopened_movie_theaters_(x2),Closed_bars_(x3),Closed_restaurants_(x3),Reopened_bars_(x3),Reopened_restaurants_(x3),Mandate_quarantine_for_those_entering_the_state_from_specific_settings,Mandate_quarantine_for_all_individuals_entering_the_state,Date_all_mandated_quarantines_ended,Date_vaccine_allocation_plan_last_updated,Vaccine_allocation_phase:_Frontline_Healthcare_Workers,Vaccine_allocation_phase:_Healthcare_Service_Workers,Vaccine_allocation_phase:_Home_Healthcare_Workers,Vaccine_allocation_phase:_Additional_Healthcare_Workers,Vaccine_allocation_phase:_Long-term_Care_Residents,Vaccine_allocation_phase:_EMS_Providers,Vaccine_allocation_phase:_Firefighters,Vaccine_allocation_phase:_Law_Enforcement_&_Public_Safety_Personnel,Vaccine_allocation_phase:_Correctional_Staff,Vaccine_allocation_phase:_People_who_are_Incarcerated,Vaccine_allocation_phase:_Residents_of_Homeless_Shelters,Vaccine_allocation_phase:_Adults_Ages_75+,Vaccine_allocation_phase:_Adults_Ages_65+,Vaccine_allocation_phase:_Adults_w/_High-Risk_Medical_Conditions,Vaccine_allocation_phase:_Pre-K-12_School_Employees,Vaccine_allocation_phase:_Higher_Education_Employees,Vaccine_allocation_phase:_Public_Transit_Workers,Vaccine_allocation_phase:_Food_Supply_Workers,Vaccine_allocation_phase:_Grocery_Store_Workers,Vaccine_allocation_phase:_Frontline_Essential_Workers,Vaccine_allocation_phase:_Additional_Essential_Workers,Vaccine_allocation_phase:_General_Public,Date_adults_ages_80+_became_eligible_for_COVID-19_vaccination,Date_adults_ages_75+_became_eligible_for_COVID-19_vaccination,Date_adults_ages_70+_became_eligible_for_COVID-19_vaccination,Date_adults_ages_65+_became_eligible_for_COVID-19_vaccination,Date_adults_ages_60+_became_eligible_for_COVID-19_vaccination,Date_adults_ages_55+_became_eligible_for_COVID-19_vaccination,Date_adults_ages_50+_became_eligible_for_COVID-19_vaccination,Date_adults_ages_45+_became_eligible_for_COVID-19_vaccination,Date_adults_ages_40+_became_eligible_for_COVID-19_vaccination,Date_adults_ages_30+_became_eligible_for_COVID-19_vaccination,Date_K-12_school_employees_became_eligible_for_COVID-19_vaccination,Date_grocery_store_workers_became_eligible_for_COVID-19_vaccination,Date_incarcerated_people_became_eligible_for_COVID-19_vaccination,Date_general_public_became_eligible_for_COVID-19_vaccination,Adults_ages_65+_prioritized_ahead_of_essential_workers,Prioritization_by_race/ethnicity,Proof_of_work_eligibility_requirement_for_vaccination,Proof_of_age_eligibility_requirement_for_vaccination,Proof_of_residency_requirement_for_vaccination,Penalty_for_failure_to_comply_with_vaccine_distribution_requirements,Expanded_scope_of_practice_of_certain_health_providers_to_administer_vaccines,First_overall_eviction_moratorium_start,First_overall_eviction_moratorium_end,Second_overall_eviction_moratorium_start,Second_overall_eviction_moratorium_end,Third_overall_eviction_moratorium_start,Third_overall_eviction_moratorium_end,First_eviction_initiation_ban_start,First_eviction_initiation_ban_end,Second_Eviction_Initiation_Ban_Start,Second_Eviction_Initiation_Ban_End,First_eviction_hearing_ban_start,First_eviction_hearing_ban_end,Second_Eviction_Hearing_Ban_Start,Second_Eviction_Hearing_Ban_End,First_eviction_enforcement_ban_start,First_eviction_enforcement_ban_end,Second_Eviction_Enforcement_Ban_Start,Second_Eviction_Enforcement_Ban_End,COVID-19_hardship_limitation_start,COVID-19_hardship_limitation_end,Second_COVID-19_hardship_limitation_start,Second_COVID-19_hardship_limitation_end,Non-payment_limitation_start,Non-payment_limitation_end,Second_non-payment_limitation_start,Second_non-payment_limitation_end,CARES_Act_pleading_start,CARES_Act_pleading_end,CDC_moratorium_start,CDC_moratorium_end,Late_Fee_Ban_Start,Late_Fee_Ban_End,Second_Late_Fee_Ban_Start,Second_Late_Fee_Ban_End,Utilities_shutoff_moratorium_start,Utilities_shutoff_moratorium_expiration,Second_utilities_shutoff_moratorium_start,Utilities_reconnection_start,Utilities_reconnection_end,SNAP_Waiver_-_Emergency_Allotments_to_Current_SNAP_Households,SNAP_Waiver_-_Pandemic_EBT_during_school_year_2019-2020,SNAP_Waiver_-_Pandemic_EBT_during_school_year_2020-2021,SNAP_Waiver_-_Pandemic_EBT_during_summer_2021,SNAP_Waiver_-_Temporary_Suspension_of_Claims_Collection,2020_Q1_SNAP_ABAWD_Time_Limit_Waiver,Modify_Medicaid_requirements_with_1135_waivers_(date_of_CMS_approval),Reopened_ACA_enrollment_using_a_special_enrollment_period,State_previously_allowed_audio-only_telehealth,Allow_audio-only_telehealth,Allow/expand_Medicaid_telehealth_coverage,State_had_CHIP_premium_non-payment_lock-out_period_as_of_January_2019,Suspend_CHIP_premium_non-payment_lock-outs,Report_COVID-19_testing_by_race/ethnicity,Report_COVID-19_cases_by_race/ethnicity,Report_COVID-19_hospitalizations_by_race,Report_COVID-19_deaths_by_race/ethnicity,Report_COVID-19_vaccinations_by_race/ethnicity,Report_Indigenous_COVID-19_testing,Report_Indigenous_COVID-19_cases,Report_Indigenous_COVID-19_hospitalizations,Report_Indigenous_COVID-19_deaths,Report_Indigenous_COVID-19_vaccinations,Stopped_personal_visitation_in_state_prisons,Stopped_legal_visitation_in_state_prisons,Resumed_visitation_in_state_prisons,Stopped_visitation_in_state_prisons_x2,Resumed_visitation_in_state_prisons_x2,Does_not_charge_copays_for_incarcerated_individuals,Waived_COVID/respiratory_illness-related_copays_during_pandemic_for_incarcerated_individuals,Waived_all_copays_during_pandemic_for_incarcerated_individuals,Did_not_waive_copays_for_incarcerated_individuals,Suspended_elective_medical_procedures,Resumed_elective_medical_procedures,No_order_to_suspend_elective_medical_procedures_but_did_release_guidance_or_orders_to_resume,Suspended_elective_medical_procedures_x2,Resumed_elective_medical_procedures_x2,No_state_unemployment_waiting_period_prior_to_pandemic;_or_date_waiting_period_waived_not_found,Waived_one_week_waiting_period_for_unemployment_insurance,Reinstated_one_week_waiting_period_for_unemployment_insurance,Waived_work_search_requirement_for_unemployment_insurance,Reinstated_work_search_requirement_for_UI,Expanded_eligibility_of_unemployment_insurance_to_anyone_who_is_quarantined_and/or_taking_care_of_someone_who_is_quarantined,Expanded_eligibility_to_high-risk_individuals_in_preventative_quarantine,Expanded_eligibility_of_unemployment_insurance_to_those_who_have_lost_childcare/school_closures,Extended_the_amount_of_time_an_individual_can_be_on_unemployment_insurance,Weekly_unemployment_insurance_maximum_amount_(dollars),"Weekly_unemployment_insurance_maximum_amount_with_extra_stimulus_(through_July_31,_2020)_(dollars)",January_2020_unemployment_insurance_maximum_duration_(weeks),July_2020_unemployment_insurance_maximum_duration_(weeks),2021_unemployment_insurance_maximum_duration_(weeks),Extended_Benefits_program_activated,Extended_Benefits_program_deactivated,Extended_Benefits_program_activated_x2,Total_Unemployment_Rate_at_Extended_Benefits_program_shutoff,Total_Unemployment_Rate_relative_to_prior_year_(%),Total_Unemployment_Rate_relative_to_second_prior_year_(%),20-week_Extended_Benefits_program_activated,20-week_Extended_Benefits_program_deactivated,20-week_Extended_Benefits_program_activated_x2,Stopped_participating_in_pandemic-related_federal_unemployment_benefit_programs,Minimum_total_earnings_required_in_the_base_period_to_qualify_for_UI,Number_of_calendar_quarters_with_earnings_in_the_base_period_needed_to_qualify_for_UI,Minimum_total_earnings_required_outside_the_highest_earning_calendar_quarter_of_the_base_period_to_qualify_for_UI,Require_earnings_in_the_last_two_calendar_quarters_of_the_base_period_in_order_to_qualify_for_UI,Earnings_in_base_period_required_to_receive_a_$300_weekly_benefit_amount_for_UI,Taxable_Wage_Amount,Minimum_Tax_Rate_(%),Maximum_Tax_Rate_(%),Average_Benefit_Amount_(August),OSHA-approved_state_plan,State_department_in_charge_of_enforcing_programs,Aerosol_transmissable_diseases_standards,Air_or_ventilation_standards,Paid_sick_leave_prior_to_pandemic,Paid_sick_leave_expansion_during_pandemic,COVID-19_anti-retaliation_rules,COVID-19_business_liability_protections,COVID-19_liability_protections_for_healthcare_providers,Branch_of_government_implementing_COVID-19_liability_rules,COVID-19_workers'_compensation_expansion,Types_of_workers_eligible_for_workers'_compensation_expansion,Data_reporting_required_for_medical_treatment,Minimum_number_of_work_days_missed_by_workers_to_require_data_reporting,"Occupational_injuries,_illnesses,_and_fatalities_reporting_prior_to_pandemic",Made_Effort_to_Limit_Abortion_Access,Use_of_telemedicine/telephone_evaluations_to_initiate_buprenorphine_prescribing,Patients_can_receive_14-28_take-home_doses_of_opioid_medication,Home_delivery_of_take-home_medication_by_opioid_treatment_programs,Use_of_telemedicine_for_schedule_II-V_prescriptions,Exceptions_to_emergency_oral_prescriptions,Waive_requirement_to_obtain_separate_DEA_registration_to_dispense_outside_home_state,Medicaid_Expansion,Population_density_per_square_miles,Population_2018,Square_Miles,Number_Homeless_(2019),Percent_Unemployed_(2018),Percent_living_under_the_federal_poverty_line_(2018),Percent_at_risk_for_serious_illness_due_to_COVID,All-cause_deaths_2018,"Mental_health_professionals_per_100,000_population_in_2019",Were_there_casino(s)_in_State?_(Land_and_Non-Land_based),State_has_at_least_one_Indian/Alaska_Native_reservation,"COVID-19_is_not_an_acceptable_reason_to_request_application_for_mail-in_ballot_unless_sick_or_exposed_(as_of_September_16,_2020)","Witness_or_notary_signature_required_for_mail-in_ballot_(as_of_September_1,_2020)",Permanent_mail-in_ballot_system,"Automatic_mail-in_ballot_system_in_response_to_COVID-19_(0,1,2_2_being_conditional-_see_notes_for_details)","Automatic_applications_sent_for_mail-in_ballots_in_response_to_COVID-19_(0,1,2_2_being_conditional-_see_notes_for_details)",Last_date_of_receipt_of_mail-in_ballot_request_for_the_general_election_(by_mail_or_online),Closed_casinos,Reopened_casinos,Closed_casinos_(x2),Reopened_casinos_(x2),Mention_of_tribal_casinos,Jan_1_2019_Minimum_Wage,Mar_29_2019_Minimum_Wage,Jul_1_2019_Minimum_Wage,Oct_1_2019_Minimum_Wage,Jan_1_2020_Minimum_Wage,Jul_1_2020_Minimum_Wage,Sep_1_2020_Minimum_Wage,Oct_1_2020_Minimum_Wage,2020_Minimum_Wage_for_Tipped_Workers,2021_Minimum_Wage,Different_Minimum_Wage_for_Smaller_Businesses,death,deathConfirmed,deathIncrease,deathProbable,hospitalized,hospitalizedCumulative,hospitalizedCurrently,hospitalizedIncrease,inIcuCumulative,inIcuCurrently,negative,negativeIncrease,negativeTestsAntibody,negativeTestsPeopleAntibody,negativeTestsViral,onVentilatorCumulative,onVentilatorCurrently,positive,positiveCasesViral,positiveIncrease,positiveScore,positiveTestsAntibody,positiveTestsAntigen,positiveTestsPeopleAntibody,positiveTestsPeopleAntigen,positiveTestsViral,recovered,totalTestEncountersViral,totalTestEncountersViralIncrease,totalTestResults,totalTestResultsIncrease,totalTestsAntibody,totalTestsAntigen,totalTestsPeopleAntibody,totalTestsPeopleAntigen,totalTestsPeopleViral,totalTestsPeopleViralIncrease,totalTestsViral,totalTestsViralIncrease,metrics.testPositivityRatio,metrics.vaccinationsInitiatedRatio,metrics.vaccinationsCompletedRatio
15888,8035.0,2020-03-11,Douglas,Colorado,3.0,0.0,2020-03-11,50.0,2.714286,39.325414,-104.925987,840.249704,328614.0,121541.0,117426.0,11333.0,5418.0,51017.0,4347.0,35801.0,89484.0,21589.0,7569.0,56665.0,2110.0,13218.0,429.0,1320.0,2389.0,802.0,3.5,0.3,3.0,0.3,51017.0,766.0,2.0,0.2,10.9,0.1,27.2,0.0,6.6,0.3,6.4,0.5,17.2,0.1,0.7,0.1,10.9,0.6,0.4,0.1,1.1,0.2,2.0,0.3,0.2,0.1,0.0013,0.1245,0.0076,0.0019,0.1353,0.0022,0.0331,0.9296,0.0038,0.2216,1.1881,0.0678,0.5199,0.4642,0.9841,0.5030,0.8962,0.0137,0.1888,0.0322,0.0204,1.1513,0.0376,3.4588,0.0150,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,9624.0,2.9,0.3,246303.0,8.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,618.0,1218.0,26.0,26.0,26.0,0.0,0.0,0.0,6.5,250.0,197.0,0.0,0.0,0.0,0.0,2500.0,1.0,0.0,0.0,13000.0,13600.0,0.58,7.4,371.47,3.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,54.72,5695564.0,104094.0,9619.0,3.9,9.6,31.3,38526.0,356.4,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,11.1,11.1,11.1,11.1,12.0,12.0,12.0,12.0,8.98,12.32,1.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,298.0,47.0,NaN,NaN,NaN,NaN,NaN,45.0,NaN,17.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,70.0,70.0,70.0,70.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,0.000,0.000,0.000
29004,8059.0,2020-03-11,Jefferson,Colorado,4.0,0.0,2020-03-11,50.0,1.571429,39.579511,-105.245462,764.289433,570427.0,238711.0,230153.0,41438.0,12071.0,41930.0,22840.0,88707.0,115926.0,56105.0,14610.0,123559.0,8090.0,35531.0,2493.0,3173.0,9242.0,8779.0,7.4,0.4,3.7,0.3,41930.0,476.0,5.6,0.2,15.6,0.1,20.3,0.0,9.9,0.2,6.3,0.4,21.7,0.1,1.5,0.2,14.9,0.5,1.0,0.1,1.4,0.2,4.0,0.3,1.5,0.1,0.0611,0.2054,0.0299,0.0548,0.3512,0.0248,0.2572,0.2471,0.0592,0.2069,0.7704,0.0232,0.5874,0.6905,1.2779,0.6749,0.9481,0.0357,0.2964,0.2114,0.3457,1.8373,0.1987,4.2368,0.0627,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,32505.0,5.8,0.3,473348.0,8.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,618.0,1218.0,26.0,26.0,26.0,0.0,0.0,0.0,6.5,250.0,197.0,0.0,0.0,0.0,0.0,2500.0,1.0,0.0,0.0,13000.0,13600.0,0.58,7.4,371.47,3.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,54.72,5695564.0,104094.0,9619.0,3.9,9.6,31.3,38526.0,356.4,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,11.1,11.1,11.1,11.1,12.0,12.0,12.0,12.0,8.98,12.32,1.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,298.0,47.0,NaN,NaN,NaN,NaN,NaN,45.0,NaN,17.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,70.0,70.0,70.0,70.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,0.000,0.000,0.000
13539,8031.0,2020-03-12,Denver,Colorado,9.0,0.0,2020-03-12,51.0,4.000000,39.761850,-104.881105,153.292030,693417.0,314045.0,294358.0,93728.0,16235.0,41196.0,64043.0,78751.0,139801.0,66458.0,21867.0,320707.0,38939.0,114374.0,1149.0,9490.0,29335.0,14919.0,13.8,0.5,4.0,0.2,41196.0,566.0,12.9,0.4,11.4,0.1,20.2,0.0,9.7,0.2,7.4,0.4,46.3,0.0,6.0,0.3,36.4,0.6,0.4,0.1,3.2,0.2,10.0,0.4,2.2,0.1,0.4280,0.2455,0.0328,0.5438,1.2501,0.2780,0.0449,0.2353,0.0538,0.3613,0.6953,0.0175,0.8590,0.9366,1.7956,0.9382,0.9962,0.0137,0.7953,0.9074,0.5409,3.2535,0.8717,6.9945,0.4197,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,1.0,0.0,2.0,3.0,70752.0,10.3,0.3,700195.0,8.0,2.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,2.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,618.0,1218.0,26.0,26.0,26.0,0.0,0.0,0.0,6.5,250.0,197.0,0.0,0.0,0.0,0.0,2500.0,1.0,0.0,0.0,13000.0,13600.0,0.58,7.4,371.47,3.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,54.72,5695564.0,104094.0,9619.0,3.9,9.6,31.3,38526.0,356.4,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,11.1,11.1,11.1,11.1,12.0,12.0,12.0,12.0,8.98,12.32,1.0,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,524.0,226.0,NaN,NaN,NaN,NaN,NaN,72.0,NaN,27.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,198.0,128.0,198.0,128.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0.0,0.018,0.000,0.000

In [18]:
decision_set_augmented = pd.merge(filtered_dp_df, augmented_colorado_df, left_on=["fips","date.x"], right_on=["fips","date"])
cols_to_drop = decision_set_augmented.columns[decision_set_augmented.nunique()==1]
reduced_decision_set_augmented = decision_set_augmented.drop(cols_to_drop, axis=1)

In [19]:
TLGRF_decision_augmented = reduced_decision_set_augmented[reduced_decision_set_augmented["TLGRF_decision"]==1]
CDPHE_decision_augmented = reduced_decision_set_augmented[reduced_decision_set_augmented["CDPHE_decision"]==1]

CDPHE_decision_augmented["CDPHE_TP"] = CDPHE_decision_augmented["delta_ranked"] <= CDPHE_decision_augmented["capacity"]
TLGRF_decision_augmented["TLGRF_TP"] = TLGRF_decision_augmented["delta_ranked"] <= TLGRF_decision_augmented["capacity"]

CDPHE_decision_augmented["CDPHE_FP"] = CDPHE_decision_augmented["delta_ranked"] > CDPHE_decision_augmented["capacity"]
TLGRF_decision_augmented["TLGRF_FP"] = TLGRF_decision_augmented["delta_ranked"] > TLGRF_decision_augmented["capacity"]


reduced_decision_set_augmented["CDPHE_TP"] = False
reduced_decision_set_augmented["TLGRF_TP"] = False
reduced_decision_set_augmented["CDPHE_FP"] = False
reduced_decision_set_augmented["TLGRF_FP"] = False


reduced_decision_set_augmented.update(CDPHE_decision_augmented)
reduced_decision_set_augmented.update(TLGRF_decision_augmented)
reduced_decision_set_augmented

,fips,county_x,date.x,tau.hat,log_rolled_cases,shifted_log_rolled_cases,rolled_cases_x,shifted_rolled_cases,predictor,delta cases,capacity,rank_unfiltered,changepoint,outbreak,rank_filtered,delta_ranked,TLGRF_decision,CDPHE_decision,date,county,cases,deaths,datetime,days_from_start,rolled_cases_y,LAT,LON,AREA_SQMI,E_TOTPOP,E_HU,E_HH,E_POV,E_UNEMP,E_PCI,E_NOHSDP,E_AGE65,E_AGE17,E_DISABL,E_SNGPNT,E_MINRTY,E_LIMENG,E_MUNIT,E_MOBILE,E_CROWD,E_NOVEH,E_GROUPQ,EP_POV,MP_POV,EP_UNEMP,MP_UNEMP,EP_PCI,MP_PCI,EP_NOHSDP,MP_NOHSDP,EP_AGE65,MP_AGE65,EP_AGE17,MP_AGE17,EP_DISABL,MP_DISABL,EP_SNGPNT,MP_SNGPNT,EP_MINRTY,MP_MINRTY,EP_LIMENG,MP_LIMENG,EP_MUNIT,MP_MUNIT,EP_MOBILE,MP_MOBILE,EP_CROWD,MP_CROWD,EP_NOVEH,MP_NOVEH,EP_GROUPQ,MP_GROUPQ,EPL_POV,EPL_UNEMP,EPL_PCI,EPL_NOHSDP,SPL_THEME1,RPL_THEME1,EPL_AGE65,EPL_AGE17,EPL_DISABL,EPL_SNGPNT,SPL_THEME2,RPL_THEME2,EPL_MINRTY,EPL_LIMENG,SPL_THEME3,RPL_THEME3,EPL_MUNIT,EPL_MOBILE,EPL_CROWD,EPL_NOVEH,EPL_GROUPQ,SPL_THEME4,RPL_THEME4,SPL_THEMES,RPL_THEMES,F_POV,F_UNEMP,F_PCI,F_THEME1,F_AGE65,F_AGE17,F_DISABL,F_SNGPNT,F_THEME2,F_MINRTY,F_LIMENG,F_THEME3,F_MUNIT,F_CROWD,F_NOVEH,F_GROUPQ,F_THEME4,F_TOTAL,E_UNINSUR,EP_UNINSUR,MP_UNINSUR,E_DAYPOP,State_of_emergency_issued,State_of_emergency_lifted,Date_closed_K-12_public_schools,Date_banned_visitors_to_nursing_homes,Stay_at_home/_shelter_in_place,End/relax_stay_at_home/shelter_in_place,Closed_other_non-essential_businesses,Began_to_reopen_businesses,Face_mask_mandate_in_public_spaces,Face_mask_mandate_for_employees_of_public-facing_businesses,Ended_face_mask_mandate,Allowed_restaurants_to_sell_takeout_alcohol,Allowed_restaurants_to_deliver_alcohol,Closed_restaurants_except_take_out,Reopen_restaurants,Closed_gyms,Reopened_gyms,Closed_movie_theaters,Reopened_movie_theaters,Closed_Bars,Reopen_bars,Reopened_hair_salons/barber_shops,Reopened_religious_gatherings,Reopened_other_non-essential_retail,Began_to_reclose_bars,Closed_bars_(x2),Reopened_bars_(x2),Date_vaccine_allocation_plan_last_updated,Vaccine_allocation_phase:_Frontline_Healthcare_Workers,Vaccine_allocation_phase:_Healthcare_Service_Workers,Vaccine_allocation_phase:_Home_Healthcare_Workers,Vaccine_allocation_phase:_Additional_Healthcare_Workers,Vaccine_allocation_phase:_Long-term_Care_Residents,Vaccine_allocation_phase:_EMS_Providers,Vaccine_allocation_phase:_Firefighters,Vaccine_allocation_phase:_Law_Enforcement_&_Public_Safety_Personnel,Vaccine_allocation_phase:_Correctional_Staff,Vaccine_allocation_phase:_Adults_Ages_75+,Vaccine_allocation_phase:_Adults_Ages_65+,Vaccine_allocation_phase:_Adults_w/_High-Risk_Medical_Conditions,Vaccine_allocation_phase:_Pre-K-12_School_Employees,Vaccine_allocation_phase:_Higher_Education_Employees,Vaccine_allocation_phase:_Public_Transit_Workers,Vaccine_allocation_phase:_Food_Supply_Workers,Vaccine_allocation_phase:_Grocery_Store_Workers,Vaccine_allocation_phase:_Frontline_Essential_Workers,Vaccine_allocation_phase:_Additional_Essential_Workers,Date_adults_ages_80+_became_eligible_for_COVID-19_vaccination,Date_adults_ages_75+_became_eligible_for_COVID-19_vaccination,Date_adults_ages_70+_became_eligible_for_COVID-19_vaccination,Date_adults_ages_65+_became_eligible_for_COVID-19_vaccination,Date_adults_ages_60+_became_eligible_for_COVID-19_vaccination,Date_adults_ages_55+_became_eligible_for_COVID-19_vaccination,Date_adults_ages_50+_became_eligible_for_COVID-19_vaccination,Date_adults_ages_45+_became_eligible_for_COVID-19_vaccination,Date_adults_ages_40+_became_eligible_for_COVID-19_vaccination,Date_adults_ages_30+_became_eligible_for_COVID-19_vaccination,Date_K-12_school_employees_became_eligible_for_COVID-19_vaccination,Date_grocery_store_workers_became_eligible_for_COVID-19_vaccination,Date_incarcerated_people_became_eligible_for_COVID-19_vaccination,Date_general_public_became_eligible_for_COVID-19_vaccination,First_overall_eviction_moratorium_start,First_overall_eviction_moratorium_end,Second_overall_eviction_moratorium_start,Second_overall_eviction_moratorium_end,First_eviction_initiation_ban_start,First_eviction_initiation_ban_end,Second_Eviction_Initiation_Ban_Start,Second_Eviction_Initiation_Ban_End,First_eviction_enforcement_ban_start,First_eviction_enforcement_ban_end,Second_Eviction_Enforcement_Ban_Start,Second_Eviction_Enforcement_Ban_End,COVID-19_hardship_limitation_start,COVID-19_hardship_limitation_end,Second_COVID-19_hardship_limitation_start,Second_COVID-19_hardship_limitation_end,CDC_moratorium_start,CDC_moratorium_end,Late_Fee_Ban_Start,Late_Fee_Ban_End,Second_Late_Fee_Ban_Start,Second_Late_Fee_Ban_End,SNAP_Waiver_-_Emergency_Allotments_to_Current_SNAP_Households,SNAP_Waiver_-_Pandemic_EBT_during_school_year_2019-2020,SNAP_Waiver_-_Temporary_Suspension_of_Claims_Collection,Modify_Medicaid_requirements_with_1135_waivers_(date_of_CMS_approval),Reopened_ACA_enrollment_using_a_special_enrollment_period,Allow_audio-only_telehealth,Allow/expand_Medicaid_telehealth_coverage,Stopped_personal_visitation_in_state_prisons,Resumed_visitation_in_state_prisons,Suspended_elective_medical_procedures,Resumed_elective_medical_procedures,Waived_one_week_waiting_period_for_unemployment_insurance,Extended_Benefits_program_activated,Extended_Benefits_program_deactivated,Extended_Benefits_program_activated_x2,Closed_casinos,Reopened_casinos,death,deathConfirmed,deathIncrease,deathProbable,hospitalized,hospitalizedCumulative,hospitalizedCurrently,hospitalizedIncrease,inIcuCumulative,inIcuCurrently,negative,negativeIncrease,negativeTestsAntibody,negativeTestsPeopleAntibody,negativeTestsViral,onVentilatorCumulative,onVentilatorCurrently,positive,positiveCasesViral,positiveIncrease,positiveTestsAntibody,positiveTestsAntigen,positiveTestsPeopleAntibody,positiveTestsPeopleAntigen,positiveTestsViral,recovered,totalTestEncountersViral,totalTestEncountersViralIncrease,totalTestResults,totalTestResultsIncrease,totalTestsAntibody,totalTestsAntigen,totalTestsPeopleAntibody,totalTestsPeopleAntigen,totalTestsPeopleViral,totalTestsPeopleViralIncrease,totalTestsViral,metrics.testPositivityRatio,metrics.vaccinationsInitiatedRatio,metrics.vaccinationsCompletedRatio,CDPHE_TP,TLGRF_TP,CDPHE_FP,TLGRF_FP
0,8031.0,Denver,2020-03-25,0.214118,4.857595,6.035481,128.714286,418.000000,27.560029,289.285714,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2020-03-25,Denver,214.0,3.0,2020-03-25,64.0,128.714286,39.761850,-104.881105,153.292030,693417.0,314045.0,294358.0,93728.0,16235.0,41196.0,64043.0,78751.0,139801.0,66458.0,21867.0,320707.0,38939.0,114374.0,1149.0,9490.0,29335.0,14919.0,13.8,0.5,4.0,0.2,41196.0,566.0,12.9,0.4,11.4,0.1,20.2,0.0,9.7,0.2,7.4,0.4,46.3,0.0,6.0,0.3,36.4,0.6,0.4,0.1,3.2,0.2,10.0,0.4,2.2,0.1,0.4280,0.2455,0.0328,0.5438,1.2501,0.2780,0.0449,0.2353,0.0538,0.3613,0.6953,0.0175,0.8590,0.9366,1.7956,0.9382,0.9962,0.0137,0.7953,0.9074,0.5409,3.2535,0.8717,6.9945,0.4197,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,2.0,3.0,70752.0,10.3,0.3,700195.0,15.0,0.0,3.0,14.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,6.0,6.0,9.0,0.0,9.0,0.0,9.0,0.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,0.0,6.0,15.0,0.0,3.0,0.0,6.0,0.0,0.0,0.0,9.0,0.0,19.0,NaN,8.0,NaN,148.0,148.0,230.0,64.0,NaN,NaN,6978.0,189.0,NaN,NaN,NaN,NaN,NaN,1086.0,NaN,174.0,NaN,NaN,NaN,NaN,NaN,NaN,9078.0,1134.0,9078.0,1134.0,NaN,NaN,NaN,NaN,8064.0,363.0,NaN,0.250,0.000,0.000,True,True,False,False
1,8041.0,El Paso,2020-03-25,0.270288,4.110874,5.390376,61.000000,219.285714,16.487597,158.285714,1.0,2.0,0.0,0.0,2.0,2.0,0.0,0.0,2020-03-25,El Paso,122.0,5.0,2020-03-25,64.0,61.000000,38.827383,-104.527472,2126.844422,688153.0,268622.0,253379.0,72948.0,20584.0,32348.0,27792.0,83244.0,168985.0,81446.0,22428.0,210157.0,9985.0,33487.0,8254.0,7106.0,10895.0,18465.0,10.9,0.5,6.2,0.3,32348.0,381.0,6.3,0.3,12.1,0.1,24.6,0.0,12.4,0.3,8.9,0.4,30.5,0.1,1.6,0.2,12.5,0.4,3.1,0.2,2.8,0.2,4.3,0.3,2.7,0.1,0.2427,0.6207,0.1624,0.0834,1.1092,0.2379,0.0675,0.7927,0.2120,0.6234,1.6956,0.2646,0.6985,0.7052,1.4037,0.7539,0.9201,0.1258,0.7249,0.2563,0.6250,2.6521,0.5782,6.8606,0.3927,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,48537.0,7.4,0.4,610628.0,15.0,0.0,3.0,14.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,6.0,6.0,9.0,0.0,9.0,0.0,9.0,0.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,0.0,6.0,15.0,0.0,3.0,0.0,6.0,0.0,0.0,0.0,9.0,0.0,19.0,NaN,8.0,NaN,148.0,148.0,230.0,64.0,NaN,NaN,6978.0,189.0,NaN,NaN,NaN,NaN,NaN,1086.0,NaN,174.0,NaN,NaN,NaN,NaN,NaN,NaN,9078.0,1134.0,9078.0,1134.0,NaN,NaN,NaN,NaN,8064.0,363.0,NaN,0.079,0.000,0.000,False,False,False,False
2,8037.0,Eagle,2020-03-25,0.190914,4.406719,5.307560,82.000000,201.857143,15.654948,119.857143,1.0,3.0,0.0,0.0,3.0,3.0,0.0,0.0,2020-03-25,Eagle,120.0,1.0,2020-03-25,64.0,82.000000,39.626992,-106.695169,1684.470957,54357.0,32154.0,17750.0,3793.0,764.0,41064.0,4075.0,5482.0,12118.0,2332.0,1015.0,17856.0,3473.0,8466.0,1724.0,768.0,304.0,84.0,7.0,1.6,2.2,0.8,41064.0,2404.0,10.7,1.4,10.1,0.3,22.3,0.1,4.3,0.9,5.7,1.4,32.8,0.0,6.8,1.0,26.3,1.8,5.4,1.0,4.3,1.3,1.7,0.9,0.2,0.2,0.0497,0.0573,0.0331,0.3996,0.5397,0.0662,0.0207,0.4906,0.0003,0.1391,0.6507,0.0156,0.7221,0.9487,1.6708,0.8886,0.9898,0.2518,0.8911,0.0232,0.0204,2.1763,0.3260,5.0375,0.1369,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,2.0,8190.0,15.1,1.9,52146.0,15.0,0.0,3.0,14.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,6.0,6.0,9.0,0.0,9.0,0.0,9.0,0.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,0.0,6.0,15.0,0.0,3.0,0.0,6.0,0.0,0.0,0.0,9.0,0.0,19.0,NaN,8.0,NaN,148.0,148.0,230.0,64.0,NaN,NaN,6978.0,189.0,NaN,NaN,NaN,NaN,NaN,1086.0,NaN,174.0,NaN,NaN,NaN,NaN,NaN,NaN,9078.0,1134.0,9078.0,1134.0,NaN,NaN,NaN,NaN,8064.0,363.0,NaN,0.000,0.000,0.000,False,False,False,False
3,8035.0,Douglas,2020-03-25,0.218179,3.575551,4.670155,35.714286,106.714286,7.792108,71.000000,1.0,7.0,0.0,0.0,4.0,4.0,0.0,0.0,2020-03-25,Douglas,58.0,0.0,2020-03-25,64.0,35.714286,39.325414,-104.925987,840.249704,328614.0,121541.0,117426.0,11333.0,5418.0,51017.0,4347.0,35801.0,89484.0,21589.0,7569.0,56665.0,2110.0,13218.0,429.0,1320.0,2389.0,802.0,3.5,0.3,3.0,0.3,51017.0,766.0,2.0,0.2,10.9,0.1,27.2,0.0,6.6,0.3,6.4,0.5,17.2,0.1,0.7,0.1,10.9,0.6,0.4,0.1,1.1,0.2,2.0,0.3,0.2,0.1,0.0013,0.1245,0.0076,0.0019,0.1353,0.0022,0.0331,0.9296,0.0038,0.2216,1.1881,0.0678,0.5199,0.4642,0.9841,0.5030,0.8962,0.0137,0.1888,0.0322,0.0204,1.1513,0.0376,3.4588,0.0150,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,9624.0,2.9,0.3,246303.0,15.0,0.0,3.0,14.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,6.0,6.0,9.0,0.0,9.0,0.0,9.0,0.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,0.0,6.0,15.0,0.0,3.0,0.0,6.0,0.0,0.0,0.0,9.0,0.0,19.0,NaN,8.0,NaN,148.0,148.0,230.0,64.0,NaN,NaN,6978.0,189.0,NaN,NaN,NaN,NaN,NaN,1086.0,NaN,174.0,NaN,NaN,NaN,NaN,NaN,NaN,9078.0,1134.0,9078.0,1134.0,NaN,NaN,NaN,NaN,8064.0,363.0,NaN,1.000,0.000,0.000,False,False,False,False
4,8051.0,Gunnison,2020-03-25,0.239097,3.279837,4.317488,26.571429,75.000000,6.353157,48.428571,1.0,9.0,0.0,0.0,5.0,5.0,0.0,0.0,2020-03-25,Gunnison,52.0,1.0,2020-03-25,64.0,26.571429,38.670499,-107.056880,3239.140212,16537.0,11854.0,6643.0,2084.0,589.0,30127.0,296.0,2044.0,2929.0,1294.0,511.0,2119.0,71.0,1120.0,673.0,132.0,197.0,896.0,13.2,3.0,5.8,1.6,30127.0,1499.0,2.8,1.1,12.4,0.3,17.7,0.5,7.8,1.4,7.7,2.2,12.8,0.2,0.4,0.6,9.4,1.7,5.7,1.2,2.0,1.0,3.0,1.6,5.4,0.7,0.3908,0.5481,0.2494,0.0035,1.1918,0.2631,0.0780,0.0735,0.0140,0.4126,0.5781,0.0127,0.4193,0.2970,0.7163,0.3426,0.8685,0.2668,0.5180,0.0920,0.8262,2.5715,0.5326,5.0577,0.1392,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1779.0,10.8,2.3,15340.0,15.0,0.0,3.0,14.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,6.0,6.0,9.0,0.0,9.0,0.0,9.0,0.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,0.0,6.0,15.0,0.0,3.0,0.0,6.0,0.0,0.0,0.0,9.0,0.0,19.0,NaN,8.0,NaN,148.0,148.0,230.0,64.0,NaN,NaN,6978.0,189.0,NaN,NaN,NaN,NaN,NaN,1086.0,NaN,174.0,NaN,NaN,NaN,NaN,NaN,NaN,9078.0,1134.0,9078.0,1134.0,NaN,NaN,NaN,NaN,8064.0,363.0,NaN,0.000,0.000,0.000,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2215,8029.0,Delta,2022-12-23,-0.017627,4.460970,4.252569,86.571429,70.285714,-1.525969,-16.285714,1.0,19.0,0.0,0.0,11.0,12.0,0.0,0.0,2022-12-23,Delta,78.0,155.0,2022-12-23,1067.0,86.571429,38.861595,-107.864892,1142.126464,30346.0,14763.0,11882.0,5145.0,1010.0,24886.0,2130.0,7499.0,6176.0,5478.0,571.0,5637.0,477.0,282.0,2348.0,274.0,595.0,1259.0,17.6,2.6,8.5,2.2,24886.0,1562.0,9.6,1.3,24.7,0.3,20.4,0.3,18.8,1.5,4.8,1.2,18.6,0.1,1.7,0.6,1.9,0.8,15.9,2.2,2.3,0.9,5.0,1.3,4.1,0.8,0.6860,0.8675,0.5946,0.3114,2.4595,0.6554,0.9128,0.2550,0.7638,0.0735,2.0051,0.4900,0.5450,0.7170,1.2620,0.6644,0.3582,0.6746,0.6049,0.3715,0.7635,2.7727,0.6466,8.4993,0.6866,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2981.0,10.2,1.4,25386.0,1018.0,534.0,1006.0,1017.0,1003.0,971.0,1010.0,967.0,891.0,975.0,588.0,1009.0,1009.0,1012.0,941.0,1012.0,933.0,1012.0,919.0,1012.0,919.0,967.0,933.0,967.0,907.0,907.0,607.0,648.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,724.0,724.0,724.0,659.0,659.0,645.0,645.0,631.0,631.0,631.0,684.0,659.0,631.0,631.0,968.0,923.0,794.0,722.0,968.0,923.0,794.0,722.0,968.0,923.0,794.0,722.0,939.0,923.0,794.0,722.0,800.0,723.0,967.0,923.0,800.0,606.0,997.0,975.0,988.0,1003.0,1009.0,997.0,1009.0,1018.0,577.0,1006.0,971.0,1009.0,937.0,756.0,664.0,1012.0,852.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.076,0.542,0.492,False,False,False,False
2216,8081.0,Moffat,2022-12-23,-0.035139,3.809832,3.509411,45.142857,33.428571,-1.586254,-11.714286,1.0,20.0,0.0,0.0,12.0,11.0,0.0,0.0,2022-12-23,Moffat,35.0,58.0,2022-12-23,1067.0,45.142857,40.610864,-108.217154,4743.241381,13060.0,6282.0,5210.0,1796.0,265.0,27845.0,803.0,1816.0,3381.0,1481.0,654.0,2463.0,241.0,556.0,1222.0,148.0,262.0,152.0,13.9,3.1,4.1,1.4,27845.0,1835.0,9.1,1.8,13.9,0.5,25.9,0.0,11.5,1.7,12.6,3.0,18.9,0.1,2.0,1.0,8.9,2.9,19.5,3.3,2.8,1.5,5.0,1.8,1.2,0.7,0.4344,0.2611,0.3844,0.2744,1.3543,0.3086,0.1442,0.8819,0.1512,0.9405,2.1178,0.5906,0.5492,0.7631,1.3123,0.6975,0.8548,0.7695,0.7249,0.3715,0.2184,2.9391,0.7329,7.7235,0.5471,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1745.0,13.5,3.5,10682.0,1018.0,534.0,1006.0,1017.0,1003.0,971.0,1010.0,967.0,891.0,975.0,588.0,1009.0,1009.0,1012.0,941.0,1012.0,933.0,1012.0,919.0,1012.0,919.0,967.0,933.0,967.0,907.0,907.0,607.0,648.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,724.0,724.0,724.0,659.0,659.0,645.0,645.0,631.0,631.0,631.0,684.0,659.0,631.0,631.0,968.0,923.0,794.0,722.0,968.0,923.0,794.0,722.0,968.0,923.0,794.0,722.0,939.0,923.0,794.0,722.0,800.0,723.0,967.0,923.0,800.0,606.0,997.0,975.0,988.0,1003.0,1009.0,997.0,1009.0,1018.0,577.0,1006.0,971.0,1009.0,937.0,756.0,664.0,1012.0,852.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.084,0.504,0.450,False,False,False,False
2217,8067.0,La Plata,2022-12-23,-0.016677,5.125663,4.924143,168.285714,137.571429,-2.806479,-30.714286,1.0,26.0,0.0,0.0,13.0,14.0,0.0,0.0,2022-12-23,La Plata,155.0,94.0,2022-12-23,1067.0,168.285714,37.287367,-107.839718,1689.783902,55101.0,27442.0,21793.0,4609.0,1250.0,37864.0,1966.0,8634.0,10565.0,4854.0,1065.0,11719.0,275.0,2280.0,3647.0,533.0,571.0,1888.0,8.7,1.0,4.1,0.8,37864.0,2105.0,5.0,0.7,15.7,0.1,19.2,0.0,8.9,0.8,4.9,0.8,21.3,0.1,0.5,0.3,8.3,1.2,13.3,1.3,2.4,0.8,2.6,0.6,3.4,0.6,0.1166,0.2611,0.0596,0.0357,0.4730,0.0503,0.2665,0.1506,0.0296,0.0777,0.5244,0.0102,0.5817,0.3582,0.9399,0.4801,0.8399,0.5957,0.6313,0.0630,0.7103,2.8402,0.6829,4.7775,0.1086,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,4993.0,9.1,1.2,53142.0,1018.0,534.0,1006.0,1017.0,1003.0,971.0,1010.0,967.0,891.0,975.0,588.0,1009.0,1009.0,1012.0,941.0,1012.0,933.0,1012.0,919.0,1012.0,919.0,967.0,933.0,967.0,907.0,907.0,607.0,648.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,724.0,724.0,724.0,659.0,659.0,645.0,645.0,631.0,631.0,631.0,684.0,659.0,631.0,631.0,968.0,923.0,794.0,722.0,968.0,923.0,794.0,722.0,968.0,923.0,794.0,722.0,939.0,923.0,794.0,722.0,800.0,723.0,967.0,923.0,800.0,606.0,997.0,975.0,988.0,1003.0,1009.0,997.0,1009.0,1018.0,577.0,1006.0,971.0,1009.0,937.0,756.0,664.0,1012.0,852.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.126,0.822,0.732,False,False,False,False

In [20]:
reduced_decision_set_augmented[reduced_decision_set_augmented["CDPHE_TP"] == 1]

,fips,county_x,date.x,tau.hat,log_rolled_cases,shifted_log_rolled_cases,rolled_cases_x,shifted_rolled_cases,predictor,delta cases,capacity,rank_unfiltered,changepoint,outbreak,rank_filtered,delta_ranked,TLGRF_decision,CDPHE_decision,date,county,cases,deaths,datetime,days_from_start,rolled_cases_y,LAT,LON,AREA_SQMI,E_TOTPOP,E_HU,E_HH,E_POV,E_UNEMP,E_PCI,E_NOHSDP,E_AGE65,E_AGE17,E_DISABL,E_SNGPNT,E_MINRTY,E_LIMENG,E_MUNIT,E_MOBILE,E_CROWD,E_NOVEH,E_GROUPQ,EP_POV,MP_POV,EP_UNEMP,MP_UNEMP,EP_PCI,MP_PCI,EP_NOHSDP,MP_NOHSDP,EP_AGE65,MP_AGE65,EP_AGE17,MP_AGE17,EP_DISABL,MP_DISABL,EP_SNGPNT,MP_SNGPNT,EP_MINRTY,MP_MINRTY,EP_LIMENG,MP_LIMENG,EP_MUNIT,MP_MUNIT,EP_MOBILE,MP_MOBILE,EP_CROWD,MP_CROWD,EP_NOVEH,MP_NOVEH,EP_GROUPQ,MP_GROUPQ,EPL_POV,EPL_UNEMP,EPL_PCI,EPL_NOHSDP,SPL_THEME1,RPL_THEME1,EPL_AGE65,EPL_AGE17,EPL_DISABL,EPL_SNGPNT,SPL_THEME2,RPL_THEME2,EPL_MINRTY,EPL_LIMENG,SPL_THEME3,RPL_THEME3,EPL_MUNIT,EPL_MOBILE,EPL_CROWD,EPL_NOVEH,EPL_GROUPQ,SPL_THEME4,RPL_THEME4,SPL_THEMES,RPL_THEMES,F_POV,F_UNEMP,F_PCI,F_THEME1,F_AGE65,F_AGE17,F_DISABL,F_SNGPNT,F_THEME2,F_MINRTY,F_LIMENG,F_THEME3,F_MUNIT,F_CROWD,F_NOVEH,F_GROUPQ,F_THEME4,F_TOTAL,E_UNINSUR,EP_UNINSUR,MP_UNINSUR,E_DAYPOP,State_of_emergency_issued,State_of_emergency_lifted,Date_closed_K-12_public_schools,Date_banned_visitors_to_nursing_homes,Stay_at_home/_shelter_in_place,End/relax_stay_at_home/shelter_in_place,Closed_other_non-essential_businesses,Began_to_reopen_businesses,Face_mask_mandate_in_public_spaces,Face_mask_mandate_for_employees_of_public-facing_businesses,Ended_face_mask_mandate,Allowed_restaurants_to_sell_takeout_alcohol,Allowed_restaurants_to_deliver_alcohol,Closed_restaurants_except_take_out,Reopen_restaurants,Closed_gyms,Reopened_gyms,Closed_movie_theaters,Reopened_movie_theaters,Closed_Bars,Reopen_bars,Reopened_hair_salons/barber_shops,Reopened_religious_gatherings,Reopened_other_non-essential_retail,Began_to_reclose_bars,Closed_bars_(x2),Reopened_bars_(x2),Date_vaccine_allocation_plan_last_updated,Vaccine_allocation_phase:_Frontline_Healthcare_Workers,Vaccine_allocation_phase:_Healthcare_Service_Workers,Vaccine_allocation_phase:_Home_Healthcare_Workers,Vaccine_allocation_phase:_Additional_Healthcare_Workers,Vaccine_allocation_phase:_Long-term_Care_Residents,Vaccine_allocation_phase:_EMS_Providers,Vaccine_allocation_phase:_Firefighters,Vaccine_allocation_phase:_Law_Enforcement_&_Public_Safety_Personnel,Vaccine_allocation_phase:_Correctional_Staff,Vaccine_allocation_phase:_Adults_Ages_75+,Vaccine_allocation_phase:_Adults_Ages_65+,Vaccine_allocation_phase:_Adults_w/_High-Risk_Medical_Conditions,Vaccine_allocation_phase:_Pre-K-12_School_Employees,Vaccine_allocation_phase:_Higher_Education_Employees,Vaccine_allocation_phase:_Public_Transit_Workers,Vaccine_allocation_phase:_Food_Supply_Workers,Vaccine_allocation_phase:_Grocery_Store_Workers,Vaccine_allocation_phase:_Frontline_Essential_Workers,Vaccine_allocation_phase:_Additional_Essential_Workers,Date_adults_ages_80+_became_eligible_for_COVID-19_vaccination,Date_adults_ages_75+_became_eligible_for_COVID-19_vaccination,Date_adults_ages_70+_became_eligible_for_COVID-19_vaccination,Date_adults_ages_65+_became_eligible_for_COVID-19_vaccination,Date_adults_ages_60+_became_eligible_for_COVID-19_vaccination,Date_adults_ages_55+_became_eligible_for_COVID-19_vaccination,Date_adults_ages_50+_became_eligible_for_COVID-19_vaccination,Date_adults_ages_45+_became_eligible_for_COVID-19_vaccination,Date_adults_ages_40+_became_eligible_for_COVID-19_vaccination,Date_adults_ages_30+_became_eligible_for_COVID-19_vaccination,Date_K-12_school_employees_became_eligible_for_COVID-19_vaccination,Date_grocery_store_workers_became_eligible_for_COVID-19_vaccination,Date_incarcerated_people_became_eligible_for_COVID-19_vaccination,Date_general_public_became_eligible_for_COVID-19_vaccination,First_overall_eviction_moratorium_start,First_overall_eviction_moratorium_end,Second_overall_eviction_moratorium_start,Second_overall_eviction_moratorium_end,First_eviction_initiation_ban_start,First_eviction_initiation_ban_end,Second_Eviction_Initiation_Ban_Start,Second_Eviction_Initiation_Ban_End,First_eviction_enforcement_ban_start,First_eviction_enforcement_ban_end,Second_Eviction_Enforcement_Ban_Start,Second_Eviction_Enforcement_Ban_End,COVID-19_hardship_limitation_start,COVID-19_hardship_limitation_end,Second_COVID-19_hardship_limitation_start,Second_COVID-19_hardship_limitation_end,CDC_moratorium_start,CDC_moratorium_end,Late_Fee_Ban_Start,Late_Fee_Ban_End,Second_Late_Fee_Ban_Start,Second_Late_Fee_Ban_End,SNAP_Waiver_-_Emergency_Allotments_to_Current_SNAP_Households,SNAP_Waiver_-_Pandemic_EBT_during_school_year_2019-2020,SNAP_Waiver_-_Temporary_Suspension_of_Claims_Collection,Modify_Medicaid_requirements_with_1135_waivers_(date_of_CMS_approval),Reopened_ACA_enrollment_using_a_special_enrollment_period,Allow_audio-only_telehealth,Allow/expand_Medicaid_telehealth_coverage,Stopped_personal_visitation_in_state_prisons,Resumed_visitation_in_state_prisons,Suspended_elective_medical_procedures,Resumed_elective_medical_procedures,Waived_one_week_waiting_period_for_unemployment_insurance,Extended_Benefits_program_activated,Extended_Benefits_program_deactivated,Extended_Benefits_program_activated_x2,Closed_casinos,Reopened_casinos,death,deathConfirmed,deathIncrease,deathProbable,hospitalized,hospitalizedCumulative,hospitalizedCurrently,hospitalizedIncrease,inIcuCumulative,inIcuCurrently,negative,negativeIncrease,negativeTestsAntibody,negativeTestsPeopleAntibody,negativeTestsViral,onVentilatorCumulative,onVentilatorCurrently,positive,positiveCasesViral,positiveIncrease,positiveTestsAntibody,positiveTestsAntigen,positiveTestsPeopleAntibody,positiveTestsPeopleAntigen,positiveTestsViral,recovered,totalTestEncountersViral,totalTestEncountersViralIncrease,totalTestResults,totalTestResultsIncrease,totalTestsAntibody,totalTestsAntigen,totalTestsPeopleAntibody,totalTestsPeopleAntigen,totalTestsPeopleViral,totalTestsPeopleViralIncrease,totalTestsViral,metrics.testPositivityRatio,metrics.vaccinationsInitiatedRatio,metrics.vaccinationsCompletedRatio,CDPHE_TP,TLGRF_TP,CDPHE_FP,TLGRF_FP
0,8031.0,Denver,2020-03-25,0.214118,4.857595,6.035481,128.714286,418.000000,27.560029,289.285714,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2020-03-25,Denver,214.0,3.0,2020-03-25,64.0,128.714286,39.761850,-104.881105,153.292030,693417.0,314045.0,294358.0,93728.0,16235.0,41196.0,64043.0,78751.0,139801.0,66458.0,21867.0,320707.0,38939.0,114374.0,1149.0,9490.0,29335.0,14919.0,13.8,0.5,4.0,0.2,41196.0,566.0,12.9,0.4,11.4,0.1,20.2,0.0,9.7,0.2,7.4,0.4,46.3,0.0,6.0,0.3,36.4,0.6,0.4,0.1,3.2,0.2,10.0,0.4,2.2,0.1,0.4280,0.2455,0.0328,0.5438,1.2501,0.2780,0.0449,0.2353,0.0538,0.3613,0.6953,0.0175,0.8590,0.9366,1.7956,0.9382,0.9962,0.0137,0.7953,0.9074,0.5409,3.2535,0.8717,6.9945,0.4197,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,2.0,3.0,70752.0,10.3,0.3,700195.0,15.0,0.0,3.0,14.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,6.0,6.0,9.0,0.0,9.0,0.0,9.0,0.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,0.0,6.0,15.0,0.0,3.0,0.0,6.0,0.0,0.0,0.0,9.0,0.0,19.0,NaN,8.0,NaN,148.0,148.0,230.0,64.0,NaN,NaN,6978.0,189.0,NaN,NaN,NaN,NaN,NaN,1086.0,NaN,174.0,NaN,NaN,NaN,NaN,NaN,NaN,9078.0,1134.0,9078.0,1134.0,NaN,NaN,NaN,NaN,8064.0,363.0,NaN,0.250,0.000,0.000,True,True,False,False
18,8014.0,Broomfield,2020-04-21,0.011312,4.465908,4.543295,87.000000,94.000000,0.984131,7.000000,1.0,11.0,1.0,1.0,1.0,1.0,1.0,1.0,2020-04-21,Broomfield,88.0,2.0,2020-04-21,91.0,87.000000,39.953593,-105.050787,33.003534,66120.0,27647.0,26721.0,3296.0,1372.0,47016.0,1460.0,8499.0,15692.0,5395.0,1364.0,15124.0,975.0,6529.0,743.0,470.0,821.0,297.0,5.0,1.0,3.6,0.6,47016.0,1883.0,3.2,0.7,12.9,0.1,23.7,0.1,8.2,0.7,5.1,0.8,22.9,0.3,1.6,0.4,23.6,1.3,2.7,0.5,1.8,0.6,3.1,0.5,0.4,0.2,0.0127,0.1946,0.0127,0.0051,0.2251,0.0080,0.0990,0.6826,0.0178,0.0939,0.8933,0.0322,0.6049,0.7052,1.3101,0.6963,0.9863,0.1044,0.4457,0.1022,0.0341,1.6727,0.1458,4.1012,0.0490,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,3075.0,4.7,0.9,62140.0,42.0,0.0,30.0,41.0,27.0,0.0,34.0,0.0,0.0,0.0,0.0,33.0,33.0,36.0,0.0,36.0,0.0,36.0,0.0,36.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,21.0,0.0,12.0,27.0,33.0,21.0,33.0,42.0,0.0,30.0,0.0,33.0,0.0,0.0,0.0,36.0,0.0,486.0,NaN,37.0,NaN,2003.0,2003.0,851.0,123.0,NaN,NaN,38257.0,897.0,NaN,NaN,NaN,NaN,NaN,10447.0,NaN,341.0,NaN,NaN,NaN,NaN,NaN,NaN,54244.0,1476.0,54244.0,1476.0,NaN,NaN,NaN,NaN,48704.0,1238.0,NaN,1.000,0.000,0.000,True,True,False,False
45,8045.0,Garfield,2020-06-03,0.015760,3.645077,3.897634,38.285714,49.285714,0.603376,11.000000,1.0,8.0,1.0,1.0,3.0,1.0,0.0,1.0,2020-06-03,Garfield,39.0,2.0,2020-06-03,134.0,38.285714,39.599352,-107.909780,2947.543401,58538.0,23875.0,21138.0,4662.0,1403.0,32491.0,4740.0,7034.0,15028.0,4734.0,1522.0,18460.0,2765.0,1702.0,2401.0,1230.0,599.0,920.0,8.1,1.2,4.3,0.9,32491.0,1070.0,12.2,1.4,12.0,0.2,25.7,0.1,8.2,0.8,7.2,1.3,31.5,0.2,5.1,0.9,7.1,1.2,10.1,1.2,5.8,1.2,2.8,0.7,1.6,0.3,0.0838,0.2924,0.1573,0.5056,1.0391,0.2131,0.0640,0.8714,0.0178,0.3247,1.2779,0.0879,0.7084,0.9195,1.6279,0.8685,0.7985,0.4670,0.9478,0.0783,0.3792,2.6708,0.5915,6.6157,0.3510,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,2.0,9878.0,17.1,1.7,54276.0,85.0,0.0,73.0,84.0,70.0,38.0,77.0,34.0,0.0,42.0,0.0,76.0,76.0,79.0,8.0,79.0,0.0,79.0,0.0,79.0,0.0,34.0,0.0,34.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,35.0,0.0,0.0,0.0,35.0,0.0,0.0,0.0,35.0,0.0,0.0,0.0,6.0,0.0,0.0,0.0,0.0,0.0,34.0,0.0,0.0,0.0,64.0,42.0,55.0,70.0,76.0,64.0,76.0,85.0,0.0,73.0,38.0,76.0,4.0,0.0,0.0,79.0,0.0,1494.0,1182.0,20.0,312.0,4443.0,4443.0,356.0,24.0,NaN,NaN,170140.0,2751.0,64531.0,NaN,NaN,NaN,NaN,27060.0,24557.0,272.0,4934.0,NaN,NaN,NaN,NaN,NaN,226370.0,4859.0,226370.0,4859.0,69465.0,NaN,NaN,NaN,194697.0,3997.0,NaN,0.041,0.000,0.000,True,False,False,False
90,8125.0,Yuma,2020-09-28,0.089033,3.737670,4.082368,42.000000,59.285714,3.739391,17.285714,2.0,13.0,1.0,1.0,1.0,2.0,1.0,1.0,2020-09-28,Yuma,55.0,1.0,2020-09-28,251.0,42.000000,40.000770,-102.421649,2364.397328,10069.0,4525.0,4051.0,1438.0,134.0,25846.0,786.0,1829.0,2701.0,1190.0,328.0,2490.0,605.0,179.0,537.0,178.0,181.0,120.0,14.5,4.0,2.6,1.1,25846.0,1888.0,11.9,2.4,18.2,0.4,26.8,0.6,12.0,2.0,8.1,2.5,24.7,0.1,6.5,1.9,4.0,2.0,11.9,3.2,4.4,2.1,4.5,2.0,1.2,0.6,0.4799,0.0860,0.5318,0.4852,1.5829,0.3796,0.5113,0.9150,0.1840,0.4900,2.1003,0.5715,0.6304,0.9436,1.5740,0.8437,0.6240,0.5425,0.8962,0.2846,0.2184,2.5657,0.5285,7.8229,0.5637,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,2.0,1118.0,11.3,2.4,7119.0,202.0,0.0,190.0,201.0,187.0,155.0,194.0,151.0,75.0,159.0,0.0,193.0,193.0,196.0,125.0,196.0,117.0,196.0,103.0,196.0,103.0,151.0,117.0,151.0,91.0,91.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,152.0,107.0,0.0,0.0,152.0,107.0,0.0,0.0,152.0,107.0,0.0,0.0,123.0,107.0,0.0,0.0,0.0,0.0,151.0,107.0,0.0,0.0,181.0,159.0,172.0,187.0,193.0,181.0,193.0,202.0,0.0,190.0,155.0,193.0,121.0,0.0,0.0,196.0,36.0,2044.0,1687.0,3.0,357.0,7530.0,7530.0,246.0,7.0,NaN,NaN,830384.0,6082.0,155928.0,NaN,NaN,NaN,NaN,69490.0,64612.0,411.0,11707.0,NaN,NaN,NaN,NaN,NaN,1326642.0,13239.0,1326642.0,13239.0,167635.0,NaN,NaN,NaN,894996.0,6457.0,NaN,0.110,0.000,0.000,True,True,False,False
623,8093.0,Park,2021-04-26,0.043467,4.404976,4.662090,81.857143,105.857143,3.558099,24.000000,2.0,10.0,1.0,1.0,2.0,2.0,1.0,1.0,2021-04-26,Park,90.0,5.0,2021-04-26,461.0,81.857143,39.118914,-105.717648,2193.901611,17392.0,14449.0,7119.0,947.0,513.0,35939.0,401.0,3322.0,3009.0,1996.0,166.0,1885.0,12.0,3.0,574.0,65.0,132.0,126.0,5.5,1.7,5.4,2.2,35939.0,3339.0,3.0,1.0,19.1,0.8,17.3,0.8,11.6,1.9,2.3,1.0,10.8,0.4,0.1,0.4,0.0,0.1,4.0,1.3,0.9,0.8,1.9,1.2,0.7,0.8,0.0197,0.4876,0.0764,0.0045,0.5882,0.0809,0.5995,0.0605,0.1585,0.0092,0.8277,0.0264,0.3664,0.0707,0.4371,0.1964,0.0000,0.1751,0.1223,0.0283,0.0729,0.3986,0.0016,2.2516,0.0006,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1256.0,7.3,2.0,9184.0,412.0,0.0,400.0,411.0,397.0,365.0,404.0,361.0,285.0,369.0,0.0,403.0,403.0,406.0,335.0,406.0,327.0,406.0,313.0,406.0,313.0,361.0,327.0,361.0,301.0,301.0,1.0,42.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,118.0,118.0,118.0,53.0,53.0,39.0,39.0,25.0,25.0,25.0,78.0,53.0,25.0,25.0,362.0,317.0,188.0,116.0,362.0,317.0,188.0,116.0,362.0,317.0,188.0,116.0,333.0,317.0,188.0,116.0,194.0,117.0,361.0,317.0,194.0,0.0,391.0,369.0,382.0,397.0,403.0,391.0,403.0,412.0,0.0,400.0,365.0,403.0,331.0,150.0,58.0,406.0,246.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.106,0.165,0.095,True,True,False,False
657,8021.0,Conejos,2021-05-12,0.050686,4.408460,4.793426,82.142857,120.714286,4.163524,38.571429,1.0,6.0,1.0,1.0,2.0,1.0,0.0,1.0,2021-05-12,Conejos,95.0,11.0,2021-05-12,477.0,82.142857,37.213406,-106.176447,1287.436098,8142.0,4398.0,3068.0,1813.0,374.0,19545.0,711.0,1466.0,2210.0,1607.0,256.0,4558.0,203.0,88.0,813.0,114.0,195.0,62.0,22.4,3.6,11.5,3.0,19545.0,1374.0,13.4,2.1,18.0,0.2,27.1,0.1,19.8,1.9,8.3,2.1,56.0,0.3,2.7,1.1,2.0,1.0,18.5,2.5,3.7,1.5,6.4,1.7,0.8,0.4,0.8627,0.9637,0.9188,0.5715,3.3167,0.8879,0.4893,0.9265,0.8169,0.5234,2.7561,0.9405,0.9077,0.8274,1.7351,0.9175,0.3725,0.7440,0.8551,0.6043,0.0936,2.6695,0.5903,10.4774,0.9325,0.0,1.0,1.0,2.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,4.0,1091.0,13.5,3.1,5853.0,428.0,0.0,416.0,427.0,413.0,381.0,420.0,377.0,301.0,385.0,0.0,419.0,419.0,422.0,351.0,422.0,343.0,422.0,329.0,422.0,329.0,377.0,343.0,377.0,317.0,317.0,17.0,58.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,134.0,134.0,134.0,69.0,69.0,55.0,55.0,41.0,41.0,41.0,94.0,69.0,41.0,41.0,378.0,333.0,204.0,132.0,378.0,333.0,204.0,132.0,378.0,333.0,204.0,132.0,349.0,333.0,204.0,132.0,210.0,133.0,377.0,333.0,210.0,16.0,407.0,385.0,398.0,413.0,419.0,407.0,419.0,428.0,0.0,416.0,381.0,419.0,347.0,166.0,74.0,422.0,262.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.186,0.126,0.088,True,False,False,False
682,8081.0,Moffat,2021-06-07,0.047881,4.462619,4.713384,86.714286,111.428571,4.151980,24.714286,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,2021-06-07,Moffat,105.0,22.0,2021-06-07,503.0,86.714286,40.610864,-108.217154,4743.241381,13060.0,6282.0,5210.0,1796.0,265.0,27845.0,803.0,1816.0,3381.0,1481.0,654.0,2463.0,241.0,556.0,1222.0,148.0,262.0,152.0,13.9,3.1,4.1,1.4,27845.0,1835.0,9.1,1.8,13.9,0.5,25.9,0.0,11.5,1.7,12.6,3.0,18.9,0.1,2.0,1.0,8.9,2.9,19.5,3.3,2.8,1.5,5.0,1.8,1.2,0.7,0.4344,0.2611,0.3844,0.2744,1.3543,0.3086,0.1442,0.8819,0.1512,0.9405,2.1178,0.5906,0.5492,0.7631,1.3123,0.6975,0.8548,0.7695,0.7249,0.3715,0.2184,2.9391,0.7329,7.7235,0.5471,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1745.0,13.5,3.5,10682.0,454.0,0.0,442.0,453.0,439.0,407.0,446.0,403.0,327.0,411.0,24.0,445.0,445.0,448.0,377.0,448.0,369.0,448.0,355.0,448.0,355.0,403.0,369.0,403.0,343.0,343.0,43.0,84.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,160.0,160.0,160.0,95.0,95.0,81.0,81.0,67.0,67.0,67.0,120.0,95.0,67.0,67.0,404.0,359.0,230.0,158.0,404.0,359.0,230.0,158.0,404.0,359.0,230.0,158.0,375.0,359.0,230.0,158.0,236.0,159.0,403.0,359.0,236.0,42.0,433.0,411.0,424.0,439.0,445.0,433.0,445.0,454.0,13.0,442.0,407.0,445.0,373.0,192.0,100.0,448.0,288.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.141,0.163,0.136,True,True,False,False
1057,8083.0,Montezuma,2021-10-01,0.036991,5.237202,5.577571,188.142857,264.428571,6.959582,76.285714,2.0,9.0,1.0,1.0,3.0,2.0,0.0,1.0,2021-10-01,Montezuma,222.0,33.0,2021-10-01,619.0,188.142857,37.338025,-108.595786,2029.327837,25909.0,12313.0,10615.0,4140.0,597.0,25161.0,1921.0,5353.0,5799.0,4446.0,787.0,7082.0,141.0,235.0,2332.0,320.0,255.0,265.0,16.1,2.2,5.1,1.4,25161.0,1044.0,10.5,1.8,20.7,0.3,22.4,0.2,17.3,1.5,7.4,1.5,27.3,0.2,0.6,0.4,1.9,0.7,18.9,2.2,3.0,1.0,2.4,0.8,1.0,0.4,0.5889,0.4303,0.5764,0.3868,1.9824,0.5041,0.7380,0.5040,0.6558,0.3613,2.2591,0.7020,0.6593,0.4187,1.0780,0.5536,0.3582,0.7536,0.7622,0.0503,0.1525,2.0768,0.2846,7.3963,0.4946,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3324.0,12.9,1.9,22410.0,570.0,86.0,558.0,569.0,555.0,523.0,562.0,519.0,443.0,527.0,140.0,561.0,561.0,564.0,493.0,564.0,485.0,564.0,471.0,564.0,471.0,519.0,485.0,519.0,459.0,459.0,159.0,200.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,276.0,276.0,276.0,211.0,211.0,197.0,197.0,183.0,183.0,183.0,236.0,211.0,183.0,183.0,520.0,475.0,346.0,274.0,520.0,475.0,346.0,274.0,520.0,475.0,346.0,274.0,491.0,475.0,346.0,274.0,352.0,275.0,519.0,475.0,352.0,158.0,549.0,527.0,540.0,555.0,561.0,549.0,561.0,570.0,129.0,558.0,523.0,561.0,489.0,308.0,216.0,564.0,404.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.068,0.615,0.528,True,False,False,False
1293,8121.0,Washington,2021-12-13,-0.050677,3.195753,3.381966,24.428571,29.428571,-1.237975,5.000000,1.0,12.0,1.0,1.0,5.0,1.0,0.0,1.0,2021-12-13,Washington,22.0,24.0,2021-12-13,692.0,24.428571,39.965790,-103.209744,2518.082648,4840.0,2406.0,2030.0,480.0,64.0,26680.0,254.0,944.0,1108.0,538.0,171.0,611.0,44.0,20.0,185.0,44.0,97.0,295.0,10.7,2.7,2.7,1.2,26680.0,1631.0,7.5,2.0,19.5,0.1,22.9,0.0,11.8,1.5,8.4,2.6,12.6,0.2,1.0,1.2,0.8,0.4,7.7,2.0,2.2,1.0,4.8,1.5,6.1,2.5,0.2312,0.0949,0.4678,0.1614,0.9553,0.1936,0.6428,0.5715,0.1706,0.5412,1.9261,0.4250,0.4155,0.5791,0.9946,0.5084,0.1369,0.3639,0.5801,0.3381,0.8523,2.2713,0.3719,6.1473,0.2822,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,229.0,5.0,1.4,3059.0,643.0,159.0,631.0,642.0,628.0,596.0,635.0,592.0,516.0,600.0,213.0,634.0,634.0,637.0,566.0,637.0,558.0,637.0,544.0,637.0,544.0,592.0,558.0,592.0,532.0,532.0,232.0,273.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,349.0,349.0,349.0,284.0,284.0,270.0,270.0,256.0,256.0,256.0,309.0,284.0,256.0,256.0,593.0,548.0,419.0,347.0,593.0,548.0,419.0,347.0,593.0,548.0,419.0,347.0,564.0,548.0,419.0,347.0,425.0,348.0,592.0,548.0,425.0,231.0,622.0,600.0,613.0,628.0,634.0,622.0,634.0,643.0,202.0,631.0,596.0,634.0,562.0,381.0,289.0,637.0,477.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000,0.324,0.290,True,False,False,False

### CDPHE_TP but TLGRF_FP

In [21]:
CDPHE_TP_TLGRF_FP_mask = (reduced_decision_set_augmented["CDPHE_TP"] == True) & (reduced_decision_set_augmented["TLGRF_TP"] == False)
CDPHE_TP_TLGRF_FP = reduced_decision_set_augmented[CDPHE_TP_TLGRF_FP_mask]
CDPHE_TP_TLGRF_FP

,fips,county_x,date.x,tau.hat,log_rolled_cases,shifted_log_rolled_cases,rolled_cases_x,shifted_rolled_cases,predictor,delta cases,capacity,rank_unfiltered,changepoint,outbreak,rank_filtered,delta_ranked,TLGRF_decision,CDPHE_decision,date,county,cases,deaths,datetime,days_from_start,rolled_cases_y,LAT,LON,AREA_SQMI,E_TOTPOP,E_HU,E_HH,E_POV,E_UNEMP,E_PCI,E_NOHSDP,E_AGE65,E_AGE17,E_DISABL,E_SNGPNT,E_MINRTY,E_LIMENG,E_MUNIT,E_MOBILE,E_CROWD,E_NOVEH,E_GROUPQ,EP_POV,MP_POV,EP_UNEMP,MP_UNEMP,EP_PCI,MP_PCI,EP_NOHSDP,MP_NOHSDP,EP_AGE65,MP_AGE65,EP_AGE17,MP_AGE17,EP_DISABL,MP_DISABL,EP_SNGPNT,MP_SNGPNT,EP_MINRTY,MP_MINRTY,EP_LIMENG,MP_LIMENG,EP_MUNIT,MP_MUNIT,EP_MOBILE,MP_MOBILE,EP_CROWD,MP_CROWD,EP_NOVEH,MP_NOVEH,EP_GROUPQ,MP_GROUPQ,EPL_POV,EPL_UNEMP,EPL_PCI,EPL_NOHSDP,SPL_THEME1,RPL_THEME1,EPL_AGE65,EPL_AGE17,EPL_DISABL,EPL_SNGPNT,SPL_THEME2,RPL_THEME2,EPL_MINRTY,EPL_LIMENG,SPL_THEME3,RPL_THEME3,EPL_MUNIT,EPL_MOBILE,EPL_CROWD,EPL_NOVEH,EPL_GROUPQ,SPL_THEME4,RPL_THEME4,SPL_THEMES,RPL_THEMES,F_POV,F_UNEMP,F_PCI,F_THEME1,F_AGE65,F_AGE17,F_DISABL,F_SNGPNT,F_THEME2,F_MINRTY,F_LIMENG,F_THEME3,F_MUNIT,F_CROWD,F_NOVEH,F_GROUPQ,F_THEME4,F_TOTAL,E_UNINSUR,EP_UNINSUR,MP_UNINSUR,E_DAYPOP,State_of_emergency_issued,State_of_emergency_lifted,Date_closed_K-12_public_schools,Date_banned_visitors_to_nursing_homes,Stay_at_home/_shelter_in_place,End/relax_stay_at_home/shelter_in_place,Closed_other_non-essential_businesses,Began_to_reopen_businesses,Face_mask_mandate_in_public_spaces,Face_mask_mandate_for_employees_of_public-facing_businesses,Ended_face_mask_mandate,Allowed_restaurants_to_sell_takeout_alcohol,Allowed_restaurants_to_deliver_alcohol,Closed_restaurants_except_take_out,Reopen_restaurants,Closed_gyms,Reopened_gyms,Closed_movie_theaters,Reopened_movie_theaters,Closed_Bars,Reopen_bars,Reopened_hair_salons/barber_shops,Reopened_religious_gatherings,Reopened_other_non-essential_retail,Began_to_reclose_bars,Closed_bars_(x2),Reopened_bars_(x2),Date_vaccine_allocation_plan_last_updated,Vaccine_allocation_phase:_Frontline_Healthcare_Workers,Vaccine_allocation_phase:_Healthcare_Service_Workers,Vaccine_allocation_phase:_Home_Healthcare_Workers,Vaccine_allocation_phase:_Additional_Healthcare_Workers,Vaccine_allocation_phase:_Long-term_Care_Residents,Vaccine_allocation_phase:_EMS_Providers,Vaccine_allocation_phase:_Firefighters,Vaccine_allocation_phase:_Law_Enforcement_&_Public_Safety_Personnel,Vaccine_allocation_phase:_Correctional_Staff,Vaccine_allocation_phase:_Adults_Ages_75+,Vaccine_allocation_phase:_Adults_Ages_65+,Vaccine_allocation_phase:_Adults_w/_High-Risk_Medical_Conditions,Vaccine_allocation_phase:_Pre-K-12_School_Employees,Vaccine_allocation_phase:_Higher_Education_Employees,Vaccine_allocation_phase:_Public_Transit_Workers,Vaccine_allocation_phase:_Food_Supply_Workers,Vaccine_allocation_phase:_Grocery_Store_Workers,Vaccine_allocation_phase:_Frontline_Essential_Workers,Vaccine_allocation_phase:_Additional_Essential_Workers,Date_adults_ages_80+_became_eligible_for_COVID-19_vaccination,Date_adults_ages_75+_became_eligible_for_COVID-19_vaccination,Date_adults_ages_70+_became_eligible_for_COVID-19_vaccination,Date_adults_ages_65+_became_eligible_for_COVID-19_vaccination,Date_adults_ages_60+_became_eligible_for_COVID-19_vaccination,Date_adults_ages_55+_became_eligible_for_COVID-19_vaccination,Date_adults_ages_50+_became_eligible_for_COVID-19_vaccination,Date_adults_ages_45+_became_eligible_for_COVID-19_vaccination,Date_adults_ages_40+_became_eligible_for_COVID-19_vaccination,Date_adults_ages_30+_became_eligible_for_COVID-19_vaccination,Date_K-12_school_employees_became_eligible_for_COVID-19_vaccination,Date_grocery_store_workers_became_eligible_for_COVID-19_vaccination,Date_incarcerated_people_became_eligible_for_COVID-19_vaccination,Date_general_public_became_eligible_for_COVID-19_vaccination,First_overall_eviction_moratorium_start,First_overall_eviction_moratorium_end,Second_overall_eviction_moratorium_start,Second_overall_eviction_moratorium_end,First_eviction_initiation_ban_start,First_eviction_initiation_ban_end,Second_Eviction_Initiation_Ban_Start,Second_Eviction_Initiation_Ban_End,First_eviction_enforcement_ban_start,First_eviction_enforcement_ban_end,Second_Eviction_Enforcement_Ban_Start,Second_Eviction_Enforcement_Ban_End,COVID-19_hardship_limitation_start,COVID-19_hardship_limitation_end,Second_COVID-19_hardship_limitation_start,Second_COVID-19_hardship_limitation_end,CDC_moratorium_start,CDC_moratorium_end,Late_Fee_Ban_Start,Late_Fee_Ban_End,Second_Late_Fee_Ban_Start,Second_Late_Fee_Ban_End,SNAP_Waiver_-_Emergency_Allotments_to_Current_SNAP_Households,SNAP_Waiver_-_Pandemic_EBT_during_school_year_2019-2020,SNAP_Waiver_-_Temporary_Suspension_of_Claims_Collection,Modify_Medicaid_requirements_with_1135_waivers_(date_of_CMS_approval),Reopened_ACA_enrollment_using_a_special_enrollment_period,Allow_audio-only_telehealth,Allow/expand_Medicaid_telehealth_coverage,Stopped_personal_visitation_in_state_prisons,Resumed_visitation_in_state_prisons,Suspended_elective_medical_procedures,Resumed_elective_medical_procedures,Waived_one_week_waiting_period_for_unemployment_insurance,Extended_Benefits_program_activated,Extended_Benefits_program_deactivated,Extended_Benefits_program_activated_x2,Closed_casinos,Reopened_casinos,death,deathConfirmed,deathIncrease,deathProbable,hospitalized,hospitalizedCumulative,hospitalizedCurrently,hospitalizedIncrease,inIcuCumulative,inIcuCurrently,negative,negativeIncrease,negativeTestsAntibody,negativeTestsPeopleAntibody,negativeTestsViral,onVentilatorCumulative,onVentilatorCurrently,positive,positiveCasesViral,positiveIncrease,positiveTestsAntibody,positiveTestsAntigen,positiveTestsPeopleAntibody,positiveTestsPeopleAntigen,positiveTestsViral,recovered,totalTestEncountersViral,totalTestEncountersViralIncrease,totalTestResults,totalTestResultsIncrease,totalTestsAntibody,totalTestsAntigen,totalTestsPeopleAntibody,totalTestsPeopleAntigen,totalTestsPeopleViral,totalTestsPeopleViralIncrease,totalTestsViral,metrics.testPositivityRatio,metrics.vaccinationsInitiatedRatio,metrics.vaccinationsCompletedRatio,CDPHE_TP,TLGRF_TP,CDPHE_FP,TLGRF_FP
45,8045.0,Garfield,2020-06-03,0.015760,3.645077,3.897634,38.285714,49.285714,0.603376,11.000000,1.0,8.0,1.0,1.0,3.0,1.0,0.0,1.0,2020-06-03,Garfield,39.0,2.0,2020-06-03,134.0,38.285714,39.599352,-107.909780,2947.543401,58538.0,23875.0,21138.0,4662.0,1403.0,32491.0,4740.0,7034.0,15028.0,4734.0,1522.0,18460.0,2765.0,1702.0,2401.0,1230.0,599.0,920.0,8.1,1.2,4.3,0.9,32491.0,1070.0,12.2,1.4,12.0,0.2,25.7,0.1,8.2,0.8,7.2,1.3,31.5,0.2,5.1,0.9,7.1,1.2,10.1,1.2,5.8,1.2,2.8,0.7,1.6,0.3,0.0838,0.2924,0.1573,0.5056,1.0391,0.2131,0.0640,0.8714,0.0178,0.3247,1.2779,0.0879,0.7084,0.9195,1.6279,0.8685,0.7985,0.4670,0.9478,0.0783,0.3792,2.6708,0.5915,6.6157,0.3510,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,2.0,9878.0,17.1,1.7,54276.0,85.0,0.0,73.0,84.0,70.0,38.0,77.0,34.0,0.0,42.0,0.0,76.0,76.0,79.0,8.0,79.0,0.0,79.0,0.0,79.0,0.0,34.0,0.0,34.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,35.0,0.0,0.0,0.0,35.0,0.0,0.0,0.0,35.0,0.0,0.0,0.0,6.0,0.0,0.0,0.0,0.0,0.0,34.0,0.0,0.0,0.0,64.0,42.0,55.0,70.0,76.0,64.0,76.0,85.0,0.0,73.0,38.0,76.0,4.0,0.0,0.0,79.0,0.0,1494.0,1182.0,20.0,312.0,4443.0,4443.0,356.0,24.0,NaN,NaN,170140.0,2751.0,64531.0,NaN,NaN,NaN,NaN,27060.0,24557.0,272.0,4934.0,NaN,NaN,NaN,NaN,NaN,226370.0,4859.0,226370.0,4859.0,69465.0,NaN,NaN,NaN,194697.0,3997.0,NaN,0.041,0.000,0.000,True,False,False,False
657,8021.0,Conejos,2021-05-12,0.050686,4.408460,4.793426,82.142857,120.714286,4.163524,38.571429,1.0,6.0,1.0,1.0,2.0,1.0,0.0,1.0,2021-05-12,Conejos,95.0,11.0,2021-05-12,477.0,82.142857,37.213406,-106.176447,1287.436098,8142.0,4398.0,3068.0,1813.0,374.0,19545.0,711.0,1466.0,2210.0,1607.0,256.0,4558.0,203.0,88.0,813.0,114.0,195.0,62.0,22.4,3.6,11.5,3.0,19545.0,1374.0,13.4,2.1,18.0,0.2,27.1,0.1,19.8,1.9,8.3,2.1,56.0,0.3,2.7,1.1,2.0,1.0,18.5,2.5,3.7,1.5,6.4,1.7,0.8,0.4,0.8627,0.9637,0.9188,0.5715,3.3167,0.8879,0.4893,0.9265,0.8169,0.5234,2.7561,0.9405,0.9077,0.8274,1.7351,0.9175,0.3725,0.7440,0.8551,0.6043,0.0936,2.6695,0.5903,10.4774,0.9325,0.0,1.0,1.0,2.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,4.0,1091.0,13.5,3.1,5853.0,428.0,0.0,416.0,427.0,413.0,381.0,420.0,377.0,301.0,385.0,0.0,419.0,419.0,422.0,351.0,422.0,343.0,422.0,329.0,422.0,329.0,377.0,343.0,377.0,317.0,317.0,17.0,58.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,134.0,134.0,134.0,69.0,69.0,55.0,55.0,41.0,41.0,41.0,94.0,69.0,41.0,41.0,378.0,333.0,204.0,132.0,378.0,333.0,204.0,132.0,378.0,333.0,204.0,132.0,349.0,333.0,204.0,132.0,210.0,133.0,377.0,333.0,210.0,16.0,407.0,385.0,398.0,413.0,419.0,407.0,419.0,428.0,0.0,416.0,381.0,419.0,347.0,166.0,74.0,422.0,262.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.186,0.126,0.088,True,False,False,False
1057,8083.0,Montezuma,2021-10-01,0.036991,5.237202,5.577571,188.142857,264.428571,6.959582,76.285714,2.0,9.0,1.0,1.0,3.0,2.0,0.0,1.0,2021-10-01,Montezuma,222.0,33.0,2021-10-01,619.0,188.142857,37.338025,-108.595786,2029.327837,25909.0,12313.0,10615.0,4140.0,597.0,25161.0,1921.0,5353.0,5799.0,4446.0,787.0,7082.0,141.0,235.0,2332.0,320.0,255.0,265.0,16.1,2.2,5.1,1.4,25161.0,1044.0,10.5,1.8,20.7,0.3,22.4,0.2,17.3,1.5,7.4,1.5,27.3,0.2,0.6,0.4,1.9,0.7,18.9,2.2,3.0,1.0,2.4,0.8,1.0,0.4,0.5889,0.4303,0.5764,0.3868,1.9824,0.5041,0.7380,0.5040,0.6558,0.3613,2.2591,0.7020,0.6593,0.4187,1.0780,0.5536,0.3582,0.7536,0.7622,0.0503,0.1525,2.0768,0.2846,7.3963,0.4946,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3324.0,12.9,1.9,22410.0,570.0,86.0,558.0,569.0,555.0,523.0,562.0,519.0,443.0,527.0,140.0,561.0,561.0,564.0,493.0,564.0,485.0,564.0,471.0,564.0,471.0,519.0,485.0,519.0,459.0,459.0,159.0,200.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,276.0,276.0,276.0,211.0,211.0,197.0,197.0,183.0,183.0,183.0,236.0,211.0,183.0,183.0,520.0,475.0,346.0,274.0,520.0,475.0,346.0,274.0,520.0,475.0,346.0,274.0,491.0,475.0,346.0,274.0,352.0,275.0,519.0,475.0,352.0,158.0,549.0,527.0,540.0,555.0,561.0,549.0,561.0,570.0,129.0,558.0,523.0,561.0,489.0,308.0,216.0,564.0,404.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.068,0.615,0.528,True,False,False,False
1293,8121.0,Washington,2021-12-13,-0.050677,3.195753,3.381966,24.428571,29.428571,-1.237975,5.000000,1.0,12.0,1.0,1.0,5.0,1.0,0.0,1.0,2021-12-13,Washington,22.0,24.0,2021-12-13,692.0,24.428571,39.965790,-103.209744,2518.082648,4840.0,2406.0,2030.0,480.0,64.0,26680.0,254.0,944.0,1108.0,538.0,171.0,611.0,44.0,20.0,185.0,44.0,97.0,295.0,10.7,2.7,2.7,1.2,26680.0,1631.0,7.5,2.0,19.5,0.1,22.9,0.0,11.8,1.5,8.4,2.6,12.6,0.2,1.0,1.2,0.8,0.4,7.7,2.0,2.2,1.0,4.8,1.5,6.1,2.5,0.2312,0.0949,0.4678,0.1614,0.9553,0.1936,0.6428,0.5715,0.1706,0.5412,1.9261,0.4250,0.4155,0.5791,0.9946,0.5084,0.1369,0.3639,0.5801,0.3381,0.8523,2.2713,0.3719,6.1473,0.2822,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,229.0,5.0,1.4,3059.0,643.0,159.0,631.0,642.0,628.0,596.0,635.0,592.0,516.0,600.0,213.0,634.0,634.0,637.0,566.0,637.0,558.0,637.0,544.0,637.0,544.0,592.0,558.0,592.0,532.0,532.0,232.0,273.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,349.0,349.0,349.0,284.0,284.0,270.0,270.0,256.0,256.0,256.0,309.0,284.0,256.0,256.0,593.0,548.0,419.0,347.0,593.0,548.0,419.0,347.0,593.0,548.0,419.0,347.0,564.0,548.0,419.0,347.0,425.0,348.0,592.0,548.0,425.0,231.0,622.0,600.0,613.0,628.0,634.0,622.0,634.0,643.0,202.0,631.0,596.0,634.0,562.0,381.0,289.0,637.0,477.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000,0.324,0.290,True,False,False,False
1798,8097.0,Pitkin,2022-07-25,0.048184,5.322313,5.497754,204.857143,244.142857,9.870884,39.285714,1.0,10.0,1.0,1.0,2.0,1.0,0.0,1.0,2022-07-25,Pitkin,241.0,8.0,2022-07-25,916.0,204.857143,39.217538,-106.916159,970.700932,17909.0,13794.0,7018.0,1289.0,531.0,56180.0,501.0,3083.0,2874.0,684.0,567.0,2592.0,134.0,3528.0,585.0,95.0,389.0,129.0,7.2,1.8,4.3,1.7,56180.0,7246.0,3.7,1.3,17.2,0.3,16.0,0.8,3.8,1.2,8.1,3.5,14.5,0.7,0.8,0.7,25.6,3.4,4.2,1.3,1.4,1.1,5.5,1.9,0.7,0.3,0.0567,0.2924,0.0025,0.0089,0.3605,0.0271,0.4091,0.0283,0.0000,0.4900,0.9274,0.0350,0.4597,0.5113,0.9710,0.4941,0.9892,0.1866,0.2964,0.4677,0.0729,2.0128,0.2607,4.2717,0.0656,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,2395.0,13.4,2.8,23290.0,867.0,383.0,855.0,866.0,852.0,820.0,859.0,816.0,740.0,824.0,437.0,858.0,858.0,861.0,790.0,861.0,782.0,861.0,768.0,861.0,768.0,816.0,782.0,816.0,756.0,756.0,456.0,497.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,573.0,573.0,573.0,508.0,508.0,494.0,494.0,480.0,480.0,480.0,533.0,508.0,480.0,480.0,817.0,772.0,643.0,571.0,817.0,772.0,643.0,571.0,817.0,772.0,643.0,571.0,788.0,772.0,643.0,571.0,649.0,572.0,816.0,772.0,649.0,455.0,846.0,824.0,837.0,852.0,858.0,846.0,858.0,867.0,426.0,855.0,820.0,858.0,786.0,605.0,513.0,861.0,701.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000,0.950,0.843,True,False,False,False
1927,8003.0,Alamosa,2022-09-21,-0.012620,4.007333,4.163337,55.000000,64.285714,-0.694112,9.285714,1.0,25.0,1.0,1.0,11.0,1.0,0.0,1.0,2022-09-21,Alamosa,58.0,63.0,2022-09-21,974.0,55.000000,37.568442,-105.788041,722.576715,16444.0,6936.0,6153.0,3635.0,708.0,21328.0,1287.0,2113.0,3932.0,2948.0,387.0,8504.0,640.0,451.0,1113.0,196.0,506.0,1089.0,23.7,4.1,9.3,3.3,21328.0,1792.0,13.5,2.5,12.8,0.2,23.9,0.3,18.4,2.0,6.3,2.2,51.7,0.3,4.2,1.7,6.5,2.1,16.0,2.4,3.2,1.7,8.2,2.9,6.6,1.5,0.8911,0.9121,0.8417,0.5772,3.2221,0.8669,0.0952,0.7122,0.7358,0.2069,1.7501,0.2958,0.8863,0.8968,1.7831,0.9331,0.7771,0.6778,0.7953,0.8026,0.8650,3.9178,0.9943,10.6731,0.9452,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2237.0,14.0,3.0,16662.0,925.0,441.0,913.0,924.0,910.0,878.0,917.0,874.0,798.0,882.0,495.0,916.0,916.0,919.0,848.0,919.0,840.0,919.0,826.0,919.0,826.0,874.0,840.0,874.0,814.0,814.0,514.0,555.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,631.0,631.0,631.0,566.0,566.0,552.0,552.0,538.0,538.0,538.0,591.0,566.0,538.0,538.0,875.0,830.0,701.0,629.0,875.0,830.0,701.0,629.0,875.0,830.0,701.0,629.0,846.0,830.0,701.0,629.0,707.0,630.0,874.0,830.0,707.0,513.0,904.0,882.0,895.0,910.0,916.0,904.0,916.0,925.0,484.0,913.0,878.0,916.0,844.0,663.0,571.0,919.0,759.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.066,0.644,0.577,True,False,False,False
2157,8125.0,Yuma,2022-12-09,0.032697,3.461262,3.614771,31.857143,37.142857,1.041620,5.285714,1.0,12.0,1.0,1.0,3.0,1.0,0.0,1.0,2022-12-09,Yuma,35.0,27.0,2022-12-09,1053.0,31.857143,40.000770,-102.421649,2364.397328,10069.0,4525.0,4051.0,1438.0,134.0,25846.0,786.0,1829.0,2701.0,1190.0,328.0,2490.0,605.0,179.0,537.0,178.0,181.0,120.0,14.5,4.0,2.6,1.1,25846.0,1888.0,11.9,2.4,18.2,0.4,26.8,0.6,12.0,2.0,8.1,2.5,24.7,0.1,6.5,1.9,4.0,2.0,11.9,3.2,4.4,2.1,4.5,2.0,1.2,0.6,0.4799,0.0860,0.5318,0.4852,1.5829,0.3796,0.5113,0.9150,0.1840,0.4900,2.1003,0.5715,0.6304,0.9436,1.5740,0.8437,0.6240,0.5425,0.8962,0.2846,0.2184,2.5657,0.5285,7.8229,0.5637,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,2.0,1118.0,11.3,2.4,7119.0,1004.0,520.0,992.0,1003.0,989.0,957.0,996.0,953.0,877.0,961.0,574.0,995.0,995.0,998.0,927.0,998.0,919.0,998.0,905.0,998.0,905.0,953.0,919.0,953.0,893.0,893.0,593.0,634.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,710.0,710.0,710.0,645.0,645.0,631.0,631.0,617.0,617.0,617.0,670.0,645.0,617.0,617.0,954.0,909.0,780.0,708.0,954.0,909.0,780.0,708.0,954.0,909.0,780.0,708.0,925.0,909.0,780.0,708.0,786.0,709.0,953.0,909.0,786.0,592.0,983.0,961.0,974.0,989.0,995.0,983.0,995.0,1004.0,563.0,992.0,957.0,995.0,923.0,742.0,650.0,998.0,838.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.206,0.506,0.453,True,False,False,False

### TLGRF_TP but CDPHE_FP

In [22]:
CDPHE_FP_TLGRF_TP_mask = (reduced_decision_set_augmented["CDPHE_TP"] == False) & (reduced_decision_set_augmented["TLGRF_TP"] == True)
CDPHE_FP_TLGRF_TP = reduced_decision_set_augmented[CDPHE_FP_TLGRF_TP_mask]
CDPHE_FP_TLGRF_TP

,fips,county_x,date.x,tau.hat,log_rolled_cases,shifted_log_rolled_cases,rolled_cases_x,shifted_rolled_cases,predictor,delta cases,capacity,rank_unfiltered,changepoint,outbreak,rank_filtered,delta_ranked,TLGRF_decision,CDPHE_decision,date,county,cases,deaths,datetime,days_from_start,rolled_cases_y,LAT,LON,AREA_SQMI,E_TOTPOP,E_HU,E_HH,E_POV,E_UNEMP,E_PCI,E_NOHSDP,E_AGE65,E_AGE17,E_DISABL,E_SNGPNT,E_MINRTY,E_LIMENG,E_MUNIT,E_MOBILE,E_CROWD,E_NOVEH,E_GROUPQ,EP_POV,MP_POV,EP_UNEMP,MP_UNEMP,EP_PCI,MP_PCI,EP_NOHSDP,MP_NOHSDP,EP_AGE65,MP_AGE65,EP_AGE17,MP_AGE17,EP_DISABL,MP_DISABL,EP_SNGPNT,MP_SNGPNT,EP_MINRTY,MP_MINRTY,EP_LIMENG,MP_LIMENG,EP_MUNIT,MP_MUNIT,EP_MOBILE,MP_MOBILE,EP_CROWD,MP_CROWD,EP_NOVEH,MP_NOVEH,EP_GROUPQ,MP_GROUPQ,EPL_POV,EPL_UNEMP,EPL_PCI,EPL_NOHSDP,SPL_THEME1,RPL_THEME1,EPL_AGE65,EPL_AGE17,EPL_DISABL,EPL_SNGPNT,SPL_THEME2,RPL_THEME2,EPL_MINRTY,EPL_LIMENG,SPL_THEME3,RPL_THEME3,EPL_MUNIT,EPL_MOBILE,EPL_CROWD,EPL_NOVEH,EPL_GROUPQ,SPL_THEME4,RPL_THEME4,SPL_THEMES,RPL_THEMES,F_POV,F_UNEMP,F_PCI,F_THEME1,F_AGE65,F_AGE17,F_DISABL,F_SNGPNT,F_THEME2,F_MINRTY,F_LIMENG,F_THEME3,F_MUNIT,F_CROWD,F_NOVEH,F_GROUPQ,F_THEME4,F_TOTAL,E_UNINSUR,EP_UNINSUR,MP_UNINSUR,E_DAYPOP,State_of_emergency_issued,State_of_emergency_lifted,Date_closed_K-12_public_schools,Date_banned_visitors_to_nursing_homes,Stay_at_home/_shelter_in_place,End/relax_stay_at_home/shelter_in_place,Closed_other_non-essential_businesses,Began_to_reopen_businesses,Face_mask_mandate_in_public_spaces,Face_mask_mandate_for_employees_of_public-facing_businesses,Ended_face_mask_mandate,Allowed_restaurants_to_sell_takeout_alcohol,Allowed_restaurants_to_deliver_alcohol,Closed_restaurants_except_take_out,Reopen_restaurants,Closed_gyms,Reopened_gyms,Closed_movie_theaters,Reopened_movie_theaters,Closed_Bars,Reopen_bars,Reopened_hair_salons/barber_shops,Reopened_religious_gatherings,Reopened_other_non-essential_retail,Began_to_reclose_bars,Closed_bars_(x2),Reopened_bars_(x2),Date_vaccine_allocation_plan_last_updated,Vaccine_allocation_phase:_Frontline_Healthcare_Workers,Vaccine_allocation_phase:_Healthcare_Service_Workers,Vaccine_allocation_phase:_Home_Healthcare_Workers,Vaccine_allocation_phase:_Additional_Healthcare_Workers,Vaccine_allocation_phase:_Long-term_Care_Residents,Vaccine_allocation_phase:_EMS_Providers,Vaccine_allocation_phase:_Firefighters,Vaccine_allocation_phase:_Law_Enforcement_&_Public_Safety_Personnel,Vaccine_allocation_phase:_Correctional_Staff,Vaccine_allocation_phase:_Adults_Ages_75+,Vaccine_allocation_phase:_Adults_Ages_65+,Vaccine_allocation_phase:_Adults_w/_High-Risk_Medical_Conditions,Vaccine_allocation_phase:_Pre-K-12_School_Employees,Vaccine_allocation_phase:_Higher_Education_Employees,Vaccine_allocation_phase:_Public_Transit_Workers,Vaccine_allocation_phase:_Food_Supply_Workers,Vaccine_allocation_phase:_Grocery_Store_Workers,Vaccine_allocation_phase:_Frontline_Essential_Workers,Vaccine_allocation_phase:_Additional_Essential_Workers,Date_adults_ages_80+_became_eligible_for_COVID-19_vaccination,Date_adults_ages_75+_became_eligible_for_COVID-19_vaccination,Date_adults_ages_70+_became_eligible_for_COVID-19_vaccination,Date_adults_ages_65+_became_eligible_for_COVID-19_vaccination,Date_adults_ages_60+_became_eligible_for_COVID-19_vaccination,Date_adults_ages_55+_became_eligible_for_COVID-19_vaccination,Date_adults_ages_50+_became_eligible_for_COVID-19_vaccination,Date_adults_ages_45+_became_eligible_for_COVID-19_vaccination,Date_adults_ages_40+_became_eligible_for_COVID-19_vaccination,Date_adults_ages_30+_became_eligible_for_COVID-19_vaccination,Date_K-12_school_employees_became_eligible_for_COVID-19_vaccination,Date_grocery_store_workers_became_eligible_for_COVID-19_vaccination,Date_incarcerated_people_became_eligible_for_COVID-19_vaccination,Date_general_public_became_eligible_for_COVID-19_vaccination,First_overall_eviction_moratorium_start,First_overall_eviction_moratorium_end,Second_overall_eviction_moratorium_start,Second_overall_eviction_moratorium_end,First_eviction_initiation_ban_start,First_eviction_initiation_ban_end,Second_Eviction_Initiation_Ban_Start,Second_Eviction_Initiation_Ban_End,First_eviction_enforcement_ban_start,First_eviction_enforcement_ban_end,Second_Eviction_Enforcement_Ban_Start,Second_Eviction_Enforcement_Ban_End,COVID-19_hardship_limitation_start,COVID-19_hardship_limitation_end,Second_COVID-19_hardship_limitation_start,Second_COVID-19_hardship_limitation_end,CDC_moratorium_start,CDC_moratorium_end,Late_Fee_Ban_Start,Late_Fee_Ban_End,Second_Late_Fee_Ban_Start,Second_Late_Fee_Ban_End,SNAP_Waiver_-_Emergency_Allotments_to_Current_SNAP_Households,SNAP_Waiver_-_Pandemic_EBT_during_school_year_2019-2020,SNAP_Waiver_-_Temporary_Suspension_of_Claims_Collection,Modify_Medicaid_requirements_with_1135_waivers_(date_of_CMS_approval),Reopened_ACA_enrollment_using_a_special_enrollment_period,Allow_audio-only_telehealth,Allow/expand_Medicaid_telehealth_coverage,Stopped_personal_visitation_in_state_prisons,Resumed_visitation_in_state_prisons,Suspended_elective_medical_procedures,Resumed_elective_medical_procedures,Waived_one_week_waiting_period_for_unemployment_insurance,Extended_Benefits_program_activated,Extended_Benefits_program_deactivated,Extended_Benefits_program_activated_x2,Closed_casinos,Reopened_casinos,death,deathConfirmed,deathIncrease,deathProbable,hospitalized,hospitalizedCumulative,hospitalizedCurrently,hospitalizedIncrease,inIcuCumulative,inIcuCurrently,negative,negativeIncrease,negativeTestsAntibody,negativeTestsPeopleAntibody,negativeTestsViral,onVentilatorCumulative,onVentilatorCurrently,positive,positiveCasesViral,positiveIncrease,positiveTestsAntibody,positiveTestsAntigen,positiveTestsPeopleAntibody,positiveTestsPeopleAntigen,positiveTestsViral,recovered,totalTestEncountersViral,totalTestEncountersViralIncrease,totalTestResults,totalTestResultsIncrease,totalTestsAntibody,totalTestsAntigen,totalTestsPeopleAntibody,totalTestsPeopleAntigen,totalTestsPeopleViral,totalTestsPeopleViralIncrease,totalTestsViral,metrics.testPositivityRatio,metrics.vaccinationsInitiatedRatio,metrics.vaccinationsCompletedRatio,CDPHE_TP,TLGRF_TP,CDPHE_FP,TLGRF_FP
5,8041.0,El Paso,2020-03-30,0.175648,5.114566,5.910797,166.428571,369.000000,29.232794,202.571429,1.0,4.0,0.0,0.0,1.0,1.0,1.0,0.0,2020-03-30,El Paso,244.0,11.0,2020-03-30,69.0,166.428571,38.827383,-104.527472,2126.844422,688153.0,268622.0,253379.0,72948.0,20584.0,32348.0,27792.0,83244.0,168985.0,81446.0,22428.0,210157.0,9985.0,33487.0,8254.0,7106.0,10895.0,18465.0,10.9,0.5,6.2,0.3,32348.0,381.0,6.3,0.3,12.1,0.1,24.6,0.0,12.4,0.3,8.9,0.4,30.5,0.1,1.6,0.2,12.5,0.4,3.1,0.2,2.8,0.2,4.3,0.3,2.7,0.1,0.2427,0.6207,0.1624,0.0834,1.1092,0.2379,0.0675,0.7927,0.2120,0.6234,1.6956,0.2646,0.6985,0.7052,1.4037,0.7539,0.9201,0.1258,0.7249,0.2563,0.625,2.6521,0.5782,6.8606,0.3927,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,48537.0,7.4,0.4,610628.0,20.0,0.0,8.0,19.0,5.0,0.0,12.0,0.0,0.0,0.0,0.0,11.0,11.0,14.0,0.0,14.0,0.0,14.0,0.0,14.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,5.0,11.0,0.0,11.0,20.0,0.0,8.0,0.0,11.0,0.0,0.0,0.0,14.0,0.0,51.0,NaN,4.0,NaN,414.0,414.0,503.0,88.0,NaN,NaN,12737.0,0.0,NaN,NaN,NaN,NaN,NaN,2627.0,NaN,320.0,NaN,NaN,NaN,NaN,NaN,NaN,17107.0,1633.0,17107.0,1633.0,NaN,NaN,NaN,NaN,15364.0,894.0,NaN,0.112,0.000,0.000,False,True,False,False
10,8041.0,El Paso,2020-04-09,0.071055,6.089693,6.339099,441.285714,566.285714,31.355676,125.000000,1.0,5.0,0.0,0.0,1.0,1.0,1.0,0.0,2020-04-09,El Paso,526.0,32.0,2020-04-09,79.0,441.285714,38.827383,-104.527472,2126.844422,688153.0,268622.0,253379.0,72948.0,20584.0,32348.0,27792.0,83244.0,168985.0,81446.0,22428.0,210157.0,9985.0,33487.0,8254.0,7106.0,10895.0,18465.0,10.9,0.5,6.2,0.3,32348.0,381.0,6.3,0.3,12.1,0.1,24.6,0.0,12.4,0.3,8.9,0.4,30.5,0.1,1.6,0.2,12.5,0.4,3.1,0.2,2.8,0.2,4.3,0.3,2.7,0.1,0.2427,0.6207,0.1624,0.0834,1.1092,0.2379,0.0675,0.7927,0.2120,0.6234,1.6956,0.2646,0.6985,0.7052,1.4037,0.7539,0.9201,0.1258,0.7249,0.2563,0.625,2.6521,0.5782,6.8606,0.3927,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,48537.0,7.4,0.4,610628.0,30.0,0.0,18.0,29.0,15.0,0.0,22.0,0.0,0.0,0.0,0.0,21.0,21.0,24.0,0.0,24.0,0.0,24.0,0.0,24.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0,0.0,0.0,15.0,21.0,9.0,21.0,30.0,0.0,18.0,0.0,21.0,0.0,0.0,0.0,24.0,0.0,226.0,NaN,33.0,NaN,1221.0,1221.0,842.0,59.0,NaN,NaN,26143.0,2599.0,NaN,NaN,NaN,NaN,NaN,6202.0,NaN,547.0,NaN,NaN,NaN,NaN,NaN,NaN,33967.0,2199.0,33967.0,2199.0,NaN,NaN,NaN,NaN,31180.0,1981.0,NaN,0.057,0.000,0.000,False,True,False,False
25,8075.0,Logan,2020-04-28,0.160098,4.972785,5.605802,144.428571,272.000000,23.122744,127.571429,1.0,4.0,0.0,0.0,1.0,1.0,1.0,0.0,2020-04-28,Logan,255.0,1.0,2020-04-28,98.0,144.428571,40.728091,-103.090464,1838.597644,21689.0,9098.0,8183.0,3117.0,462.0,25776.0,1540.0,3647.0,4637.0,2931.0,597.0,4819.0,629.0,699.0,859.0,226.0,695.0,1049.0,15.0,2.6,4.1,1.9,25776.0,1558.0,10.5,1.9,16.8,0.4,21.4,0.7,13.8,1.5,7.3,2.3,22.2,0.1,3.1,1.1,7.7,2.7,9.4,2.1,2.8,1.5,8.5,2.0,4.8,1.2,0.5127,0.2611,0.5379,0.3868,1.6985,0.4159,0.3664,0.3629,0.3314,0.3435,1.4042,0.1283,0.5934,0.8494,1.4428,0.7752,0.8195,0.4390,0.7249,0.8284,0.801,3.6128,0.9634,8.1583,0.6280,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1929.0,9.1,2.0,19379.0,49.0,0.0,37.0,48.0,34.0,2.0,41.0,0.0,0.0,6.0,0.0,40.0,40.0,43.0,0.0,43.0,0.0,43.0,0.0,43.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,28.0,6.0,19.0,34.0,40.0,28.0,40.0,49.0,0.0,37.0,2.0,40.0,0.0,0.0,0.0,43.0,0.0,736.0,NaN,30.0,NaN,2571.0,2571.0,964.0,86.0,NaN,NaN,54714.0,2252.0,NaN,NaN,NaN,NaN,NaN,14316.0,12741.0,437.0,NaN,NaN,NaN,NaN,NaN,NaN,75105.0,2702.0,75105.0,2702.0,NaN,NaN,NaN,NaN,67094.0,753.0,NaN,0.602,0.000,0.000,False,True,False,False
33,8075.0,Logan,2020-05-08,0.038284,5.669388,6.059457,289.857143,428.142857,11.097022,138.285714,1.0,4.0,0.0,0.0,1.0,1.0,1.0,0.0,2020-05-08,Logan,333.0,2.0,2020-05-08,108.0,289.857143,40.728091,-103.090464,1838.597644,21689.0,9098.0,8183.0,3117.0,462.0,25776.0,1540.0,3647.0,4637.0,2931.0,597.0,4819.0,629.0,699.0,859.0,226.0,695.0,1049.0,15.0,2.6,4.1,1.9,25776.0,1558.0,10.5,1.9,16.8,0.4,21.4,0.7,13.8,1.5,7.3,2.3,22.2,0.1,3.1,1.1,7.7,2.7,9.4,2.1,2.8,1.5,8.5,2.0,4.8,1.2,0.5127,0.2611,0.5379,0.3868,1.6985,0.4159,0.3664,0.3629,0.3314,0.3435,1.4042,0.1283,0.5934,0.8494,1.4428,0.7752,0.8195,0.4390,0.7249,0.8284,0.801,3.6128,0.9634,8.1583,0.6280,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1929.0,9.1,2.0,19379.0,59.0,0.0,47.0,58.0,44.0,12.0,51.0,8.0,0.0,16.0,0.0,50.0,50.0,53.0,0.0,53.0,0.0,53.0,0.0,53.0,0.0,8.0,0.0,8.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0,0.0,0.0,0.0,9.0,0.0,0.0,0.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0,0.0,0.0,0.0,38.0,16.0,29.0,44.0,50.0,38.0,50.0,59.0,0.0,47.0,12.0,50.0,0.0,0.0,0.0,53.0,0.0,960.0,NaN,16.0,NaN,3600.0,3600.0,790.0,43.0,NaN,NaN,77945.0,2210.0,NaN,NaN,NaN,NaN,NaN,18827.0,16969.0,456.0,NaN,NaN,NaN,NaN,NaN,NaN,108509.0,5376.0,108509.0,5376.0,NaN,NaN,NaN,NaN,96772.0,4505.0,NaN,0.311,0.000,0.000,False,True,False,False
38,8041.0,El Paso,2020-05-21,0.019576,6.163315,6.307838,475.000000,548.857143,9.298637,73.857143,1.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,2020-05-21,El Paso,521.0,88.0,2020-05-21,121.0,475.000000,38.827383,-104.527472,2126.844422,688153.0,268622.0,253379.0,72948.0,20584.0,32348.0,27792.0,83244.0,168985.0,81446.0,22428.0,210157.0,9985.0,33487.0,8254.0,7106.0,10895.0,18465.0,10.9,0.5,6.2,0.3,32348.0,381.0,6.3,0.3,12.1,0.1,24.6,0.0,12.4,0.3,8.9,0.4,30.5,0.1,1.6,0.2,12.5,0.4,3.1,0.2,2.8,0.2,4.3,0.3,2.7,0.1,0.2427,0.6207,0.1624,0.0834,1.1092,0.2379,0.0675,0.7927,0.2120,0.6234,1.6956,0.2646,0.6985,0.7052,1.4037,0.7539,0.9201,0.1258,0.7249,0.2563,0.625,2.6521,0.5782,6.8606,0.3927,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,48537.0,7.4,0.4,610628.0,72.0,0.0,60.0,71.0,57.0,25.0,64.0,21.0,0.0,29.0,0.0,63.0,63.0,66.0,0.0,66.0,0.0,66.0,0.0,66.0,0.0,21.0,0.0,21.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,22.0,0.0,0.0,0.0,22.0,0.0,0.0,0.0,22.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,21.0,0.0,0.0,0.0,51.0,29.0,42.0,57.0,63.0,51.0,63.0,72.0,0.0,60.0,25.0,63.0,0.0,0.0,0.0,66.0,0.0,1310.0,1036.0,11.0,273.0,4037.0,4037.0,620.0,47.0,NaN,NaN,119034.0,6220.0,38142.0,NaN,NaN,NaN,NaN,23191.0,20903.0,394.0,3315.0,NaN,NaN,NaN,NaN,NaN,158918.0,5121.0,158918.0,5121.0,41457.0,NaN,NaN,NaN,139937.0,4326.0,NaN,0.052,0.000,0.000,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2079,8041.0,El Paso,2022-11-15,0.015991,7.972170,8.094858,2899.142857,3277.571429,46.361577,378.428571,1.0,2.0,0.0,0.0,1.0,1.0,1.0,0.0,2022-11-15,El Paso,3025.0,1824.0,2022-11-15,1029.0,2899.142857,38.827383,-104.527472,2126.844422,688153.0,268622.0,253379.0,72948.0,20584.0,32348.0,27792.0,83244.0,168985.0,81446.0,22428.0,210157.0,9985.0,33487.0,8254.0,7106.0,10895.0,18465.0,10.9,0.5,6.2,0.3,32348.0,381.0,6.3,0.3,12.1,0.1,24.6,0.0,12.4,0.3,8.9,0.4,30.5,0.1,1.6,0.2,12.5,0.4,3.1,0.2,2.8,0.2,4.3,0.3,2.7,0.1,0.2427,0.6207,0.1624,0.0834,1.1092,0.2379,0.0675,0.7927,0.2120,0.6234,1.6956,0.2646,0.6985,0.7052,1.4037,0.7539,0.9201,0.1258,0.7249,0.2563,0.625,2.6521,0.5782,6.8606,0.3927,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,48537.0,7.4,0.4,610628.0,980.0,496.0,968.0,979.0,965.0,933.0,972.0,929.0,853.0,937.0,550.0,971.0,971.0,974.0,903.0,974.0,895.0,974.0,881.0,974.0,881.0,929.0,895.0,929.0,869.0,869.0,569.0,610.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,686.0,686.0,686.0,621.0,621.0,607.0,607.0,593.0,593.0,593.0,646.0,621.0,593.0,593.0,930.0,885.0,756.0,684.0,930.0,885.0,756.0,684.0,930.0,885.0,756.0,684.0,901.0,885.0,756.0,684.0,762.0,685.0,929.0,885.0,762.0,568.0,959.0,937.0,950.0,965.0,971.0,959.0,971.0,980.0,539.0,968.0,933.0,971.0,899.0,718.0,626.0,974.0,814.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.134,0.778,0.674,False,True,False,False
2096,8041.0,El Paso,2022-11-18,0.015843,8.020270,8.129722,3042.000000,3393.857143,48.193411,351.857143,1.0,2.0,0.0,0.0,1.0,1.0,1.0,0.0,2022-11-18,El Paso,3243.0,1830.0,2022-11-18,1032.0,3042.000000,38.827383,-104.527472,2126.844422,688153.0,268622.0,253379.0,72948.0,20584.0,32348.0,27792.0,83244.0,168985.0,81446.0,22428.0,210157.0,9985.0,33487.0,8254.0,7106.0,10895.0,18465.0,10.9,0.5,6.2,0.3,32348.0,381.0,6.3,0.3,12.1,0.1,24.6,0.0,12.4,0.3,8.9,0.4,30.5,0.1,1.6,0.2,12.5,0.4,3.1,0.2,2.8,0.2,4.3,0.3,2.7,0.1,0.2427,0.6207,0.1624,0.0834,1.1092,0.2379,0.0675,0.7927,0.2120,0.6234,1.6956,0.2646,0.6985,0.7052,1.4037,0.7539,0.9201,0.1258,0.7249,0.2563,0.625,2.6521,0.5782,6.8606,0.3927,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,48537.0,7.4,0.4,610628.0,983.0,499.0,971.0,982.0,968.0,936.0,975.0,932.0,856.0,940.0,553.0,974.0,974.0,977.0,906.0,977.0,898.0,977.0,884.0,977.0,884.0,932.0,898.0,932.0,872.0,872.0,572.0,613.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,689.0,689.0,689.0,624.0,624.0,610.0,610.0,596.0,596.0,596.0,649.0,624.0,596.0,596.0,933.0,888.0,759.0,687.0,933.0,888.0,759.0,687.0,933.0,888.0,759.0,687.0,904.0,888.0,759.0,687.0,765.0,688.0,932.0,888.0,765.0,571.0,962.0,940.0,953.0,968.0,974.0,962.0,974.0,983.0,542.0,971.0,936.0,974.0,902.0,721.0,629.0,977.0,817.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.134,0.779,0.675,False,True,False,False
2111,8041.0,El Paso,2022-11-21,0.014198,8.068761,8.155977,3193.142857,3484.142857,45.337543,291.000000,1.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,2022-11-21,El Paso,3519.0,1831.0,2022-11-21,1035.0,3193.142857,38.827383,-104.527472,2126.844422,688153.0,268622.0,253379.0,72948.0,20584.0,32348.0,27792.0,83244.0,168985.0,81446.0,22428.0,210157.0,9985.0,33487.0,8254.0,7106.0,10895.0,18465.0,10.9,0.5,6.2,0.3,32348.0,381.0,6.3,0.3,12.1,0.1,24.6,0.0,12.4,0.3,8.9,0.4,30.5,0.1,1.6,0.2,12.5,0.4,3.1,0.2,2.8,0.2,4.3,0.3,2.7,0.1,0.2427,0.6207,0.1624,0.0834,1.1092,0.2379,0.0675,0.7927,0.2120,0.6234,1.6956,0.2646,0.6985,0.7052,1.4037,0.7539,0.9201,0.1258,0.7249,0.2563,0.625,2.6521,0.5782,6.8606,0.3927,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,48537.0,7.4,0.4,610628.0,986.0,502.0,974.0,985.0,971.0,939.0,978.0,935.0,859.0,943.0,556.0,977.0,977.0,980.0,909.0,980.0,901.0,980.0,887.0,980.0,887.0,935.0,901.0,935.0,875.0,875.0,575.0,616.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,692.0,692.0,692.0,627.0,627.0,613.0,613.0,599.0,599.0,599.0,652.0,627.0,599.0,599.0,936.0,891.0,762.0,690.0,936.0,891.0,762.0,690.0,936.0,891.0,762.0,690.0,907.0,891.0,762.0,690.0,768.0,691.0,935.0,891.0,768.0,574.0,965.0,943.0,956.0,971.0,977.0,965.0,977.0,986.0,545.0,974.0,939.0,977.0,905.0,724.0,632.0,980.0,820.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.134,0.779,0.675,False,True,False,False

In [23]:
CDPHE_TP_TLGRF_FP.describe()

,fips,tau.hat,log_rolled_cases,shifted_log_rolled_cases,rolled_cases_x,shifted_rolled_cases,predictor,delta cases,capacity,rank_unfiltered,changepoint,outbreak,rank_filtered,delta_ranked,TLGRF_decision,CDPHE_decision,cases,deaths,days_from_start,rolled_cases_y,LAT,LON,AREA_SQMI,E_TOTPOP,E_HU,E_HH,E_POV,E_UNEMP,E_PCI,E_NOHSDP,E_AGE65,E_AGE17,E_DISABL,E_SNGPNT,E_MINRTY,E_LIMENG,E_MUNIT,E_MOBILE,E_CROWD,E_NOVEH,E_GROUPQ,EP_POV,MP_POV,EP_UNEMP,MP_UNEMP,EP_PCI,MP_PCI,EP_NOHSDP,MP_NOHSDP,EP_AGE65,MP_AGE65,EP_AGE17,MP_AGE17,EP_DISABL,MP_DISABL,EP_SNGPNT,MP_SNGPNT,EP_MINRTY,MP_MINRTY,EP_LIMENG,MP_LIMENG,EP_MUNIT,MP_MUNIT,EP_MOBILE,MP_MOBILE,EP_CROWD,MP_CROWD,EP_NOVEH,MP_NOVEH,EP_GROUPQ,MP_GROUPQ,EPL_POV,EPL_UNEMP,EPL_PCI,EPL_NOHSDP,SPL_THEME1,RPL_THEME1,EPL_AGE65,EPL_AGE17,EPL_DISABL,EPL_SNGPNT,SPL_THEME2,RPL_THEME2,EPL_MINRTY,EPL_LIMENG,SPL_THEME3,RPL_THEME3,EPL_MUNIT,EPL_MOBILE,EPL_CROWD,EPL_NOVEH,EPL_GROUPQ,SPL_THEME4,RPL_THEME4,SPL_THEMES,RPL_THEMES,F_POV,F_UNEMP,F_PCI,F_THEME1,F_AGE65,F_AGE17,F_DISABL,F_SNGPNT,F_THEME2,F_MINRTY,F_LIMENG,F_THEME3,F_MUNIT,F_CROWD,F_NOVEH,F_GROUPQ,F_THEME4,F_TOTAL,E_UNINSUR,EP_UNINSUR,MP_UNINSUR,E_DAYPOP,State_of_emergency_issued,State_of_emergency_lifted,Date_closed_K-12_public_schools,Date_banned_visitors_to_nursing_homes,Stay_at_home/_shelter_in_place,End/relax_stay_at_home/shelter_in_place,Closed_other_non-essential_businesses,Began_to_reopen_businesses,Face_mask_mandate_in_public_spaces,Face_mask_mandate_for_employees_of_public-facing_businesses,Ended_face_mask_mandate,Allowed_restaurants_to_sell_takeout_alcohol,Allowed_restaurants_to_deliver_alcohol,Closed_restaurants_except_take_out,Reopen_restaurants,Closed_gyms,Reopened_gyms,Closed_movie_theaters,Reopened_movie_theaters,Closed_Bars,Reopen_bars,Reopened_hair_salons/barber_shops,Reopened_religious_gatherings,Reopened_other_non-essential_retail,Began_to_reclose_bars,Closed_bars_(x2),Reopened_bars_(x2),Date_vaccine_allocation_plan_last_updated,Vaccine_allocation_phase:_Frontline_Healthcare_Workers,Vaccine_allocation_phase:_Healthcare_Service_Workers,Vaccine_allocation_phase:_Home_Healthcare_Workers,Vaccine_allocation_phase:_Additional_Healthcare_Workers,Vaccine_allocation_phase:_Long-term_Care_Residents,Vaccine_allocation_phase:_EMS_Providers,Vaccine_allocation_phase:_Firefighters,Vaccine_allocation_phase:_Law_Enforcement_&_Public_Safety_Personnel,Vaccine_allocation_phase:_Correctional_Staff,Vaccine_allocation_phase:_Adults_Ages_75+,Vaccine_allocation_phase:_Adults_Ages_65+,Vaccine_allocation_phase:_Adults_w/_High-Risk_Medical_Conditions,Vaccine_allocation_phase:_Pre-K-12_School_Employees,Vaccine_allocation_phase:_Higher_Education_Employees,Vaccine_allocation_phase:_Public_Transit_Workers,Vaccine_allocation_phase:_Food_Supply_Workers,Vaccine_allocation_phase:_Grocery_Store_Workers,Vaccine_allocation_phase:_Frontline_Essential_Workers,Vaccine_allocation_phase:_Additional_Essential_Workers,Date_adults_ages_80+_became_eligible_for_COVID-19_vaccination,Date_adults_ages_75+_became_eligible_for_COVID-19_vaccination,Date_adults_ages_70+_became_eligible_for_COVID-19_vaccination,Date_adults_ages_65+_became_eligible_for_COVID-19_vaccination,Date_adults_ages_60+_became_eligible_for_COVID-19_vaccination,Date_adults_ages_55+_became_eligible_for_COVID-19_vaccination,Date_adults_ages_50+_became_eligible_for_COVID-19_vaccination,Date_adults_ages_45+_became_eligible_for_COVID-19_vaccination,Date_adults_ages_40+_became_eligible_for_COVID-19_vaccination,Date_adults_ages_30+_became_eligible_for_COVID-19_vaccination,Date_K-12_school_employees_became_eligible_for_COVID-19_vaccination,Date_grocery_store_workers_became_eligible_for_COVID-19_vaccination,Date_incarcerated_people_became_eligible_for_COVID-19_vaccination,Date_general_public_became_eligible_for_COVID-19_vaccination,First_overall_eviction_moratorium_start,First_overall_eviction_moratorium_end,Second_overall_eviction_moratorium_start,Second_overall_eviction_moratorium_end,First_eviction_initiation_ban_start,First_eviction_initiation_ban_end,Second_Eviction_Initiation_Ban_Start,Second_Eviction_Initiation_Ban_End,First_eviction_enforcement_ban_start,First_eviction_enforcement_ban_end,Second_Eviction_Enforcement_Ban_Start,Second_Eviction_Enforcement_Ban_End,COVID-19_hardship_limitation_start,COVID-19_hardship_limitation_end,Second_COVID-19_hardship_limitation_start,Second_COVID-19_hardship_limitation_end,CDC_moratorium_start,CDC_moratorium_end,Late_Fee_Ban_Start,Late_Fee_Ban_End,Second_Late_Fee_Ban_Start,Second_Late_Fee_Ban_End,SNAP_Waiver_-_Emergency_Allotments_to_Current_SNAP_Households,SNAP_Waiver_-_Pandemic_EBT_during_school_year_2019-2020,SNAP_Waiver_-_Temporary_Suspension_of_Claims_Collection,Modify_Medicaid_requirements_with_1135_waivers_(date_of_CMS_approval),Reopened_ACA_enrollment_using_a_special_enrollment_period,Allow_audio-only_telehealth,Allow/expand_Medicaid_telehealth_coverage,Stopped_personal_visitation_in_state_prisons,Resumed_visitation_in_state_prisons,Suspended_elective_medical_procedures,Resumed_elective_medical_procedures,Waived_one_week_waiting_period_for_unemployment_insurance,Extended_Benefits_program_activated,Extended_Benefits_program_deactivated,Extended_Benefits_program_activated_x2,Closed_casinos,Reopened_casinos,death,deathConfirmed,deathIncrease,deathProbable,hospitalized,hospitalizedCumulative,hospitalizedCurrently,hospitalizedIncrease,inIcuCumulative,inIcuCurrently,negative,negativeIncrease,negativeTestsAntibody,negativeTestsPeopleAntibody,negativeTestsViral,onVentilatorCumulative,onVentilatorCurrently,positive,positiveCasesViral,positiveIncrease,positiveTestsAntibody,positiveTestsAntigen,positiveTestsPeopleAntibody,positiveTestsPeopleAntigen,positiveTestsViral,recovered,totalTestEncountersViral,totalTestEncountersViralIncrease,totalTestResults,totalTestResultsIncrease,totalTestsAntibody,totalTestsAntigen,totalTestsPeopleAntibody,totalTestsPeopleAntigen,totalTestsPeopleViral,totalTestsPeopleViralIncrease,totalTestsViral,metrics.testPositivityRatio,metrics.vaccinationsInitiatedRatio,metrics.vaccinationsCompletedRatio
count,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.0,7.0,7.000000,7.000000,7.0,7.0,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.00000,7.000000,7.0,7.000000,7.000000,7.000000,7.0,7.000000,7.0,7.0,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.0,7.0,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,7.000000,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,7.000000,7.000000,7.000000
mean,8070.714286,0.017289,4.182486,4.418066,89.244898,115.632653,2.958128,26.387755,1.142857,11.714286,1.0,1.0,4.142857,1.142857,0.0,1.0,101.714286,24.000000,695.000000,89.244898,38.700475,-105.859658,1834.294994,20264.428571,9749.571429,7724.714286,2493.857143,544.428571,29604.428571,1457.142857,3117.428571,4807.428571,2306.714286,574.000000,6328.142857,647.428571,886.142857,1138.000000,311.000000,317.428571,411.428571,14.671429,2.800000,5.685714,1.800000,29604.428571,2292.142857,10.385714,1.928571,16.914286,0.242857,23.542857,0.300000,13.042857,1.557143,7.685714,2.242857,31.185714,0.285714,2.985714,1.128571,6.842857,1.542857,12.471429,2.114286,3.385714,1.371429,4.942857,1.642857,2.571429,0.857143,0.456329,0.438829,0.499471,0.385229,1.779857,0.438900,0.421386,0.646986,0.368700,0.419643,1.856714,0.436814,0.666757,0.728057,1.394814,0.731271,0.579486,0.533629,0.733300,0.375129,0.376271,2.597814,0.517400,7.62920,0.519257,0.0,0.285714,0.142857,0.428571,0.0,0.285714,0.0,0.0,0.285714,0.142857,0.285714,0.428571,0.142857,0.142857,0.0,0.0,0.285714,1.428571,2896.000000,12.457143,2.328571,18952.714286,646.000000,227.000000,634.000000,645.000000,631.000000,599.000000,638.000000,595.000000,525.000000,603.000000,265.571429,637.000000,637.000000,640.000000,569.000000,640.000000,561.000000,640.000000,549.000000,640.000000,549.000000,595.000000,561.000000,595.000000,538.714286,538.714286,281.571429,316.714286,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,381.857143,381.857143,381.857143,326.142857,326.142857,314.142857,314.142857,302.142857,302.142857,302.142857,347.571429,326.142857,302.142857,302.142857,596.000000,552.428571,441.857143,380.142857,596.000000,552.428571,441.857143,380.142857,596.000000,552.428571,441.857143,380.142857,567.000000,552.428571,441.857143,380.142857,447.000000,381.000000,595.000000,552.428571,447.000000,280.714286,625.000000,603.000000,616.000000,631.000000,637.000000,625.000000,637.000000,646.000000,257.714286,634.000000,599.000000,637.000000,565.000000,409.285714,330.428571,640.000000,491.571429,1494.0,1182.0,20.0,312.0,4443.0,4443.0,356.0,24.0,NaN,NaN,170140.0,2751.0,64531.0,NaN,NaN,NaN,NaN,27060.0,24557.0,272.0,4934.0,NaN,NaN,NaN,NaN,NaN,226370.0,4859.0,226370.0,4859.0,69465.0,NaN,NaN,NaN,194697.0,3997.0,NaN,0.081000,0.452143,0.397000
std,48.365671,0.036995,0.844195,0.885588,75.786431,99.424290,4.191555,26.572544,0.377964,6.237368,0.0,0.0,3.184785,0.377964,0.0,0.0,91.799990,20.493902,322.199731,75.786431,1.272548,2.300472,847.221021,18283.344924,7530.338524,6568.239889,1622.679823,446.309630,12427.836965,1548.665385,2253.087871,4740.205054,1750.129016,466.036479,6013.787559,963.300378,1300.362440,885.275287,414.791112,185.315818,416.241459,6.558637,1.132843,3.403150,0.959166,12427.836965,2209.289662,3.591856,0.460848,3.291620,0.097590,3.800376,0.294392,5.830911,0.450397,0.760326,0.734523,16.919853,0.195180,2.337683,0.531395,8.607140,1.032565,5.586506,0.698638,1.442716,0.415188,2.013171,0.752456,2.601739,0.838366,0.346761,0.361756,0.332913,0.218997,1.137611,0.334985,0.256982,0.319763,0.353671,0.124579,0.611688,0.327969,0.189458,0.218451,0.363584,0.201815,0.301264,0.211023,0.225984,0.272949,0.344577,0.642154,0.251536,2.30815,0.327895,0.0,0.487950,0.377964,0.786796,0.0,0.487950,0.0,0.0,0.487950,0.377964,0.487950,0.534522,0.377964,0.377964,0.0,0.0,0.487950,1.397276,3244.199644,3.720599,0.672593,17549.910823,322.199731,217.387519,322.199731,322.199731,322.199731,322.199731,322.199731,322.199731,310.178443,322.199731,236.904240,322.199731,322.199731,322.199731,322.199731,322.199731,322.199731,322.199731,318.155098,322.199731,318.155098,322.199731,322.199731,322.199731,314.717712,314.717712,240.900296,249.241325,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,266.401594,266.401594,266.401594,251.594534,251.594534,248.607742,248.607742,245.698615,245.698615,245.698615,257.112723,251.594534,245.698615,245.698615,322.199731,319.306988,283.865830,265.924443,322.199731,319.306988,283.865830,265.924443,322.199731,319.306988,283.865830,265.924443,322.199731,319.306988,283.865830,265.924443,285.427165,266.162857,322.199731,319.306988,285.427165,240.705708,322.199731,322.199731,322.199731,322.199731,322.199731,322.199731,322.199731,322.199731,232.819468,322.199731,322.199731,322.199731,322.199731,274.206561,252.679545,322.199731,299.337523,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.083433,0.326934,0.293301
min,8003.000000,-0.050677,3.195753,3.381966,24.428571,29.428571,-1.237975,5.000000,1.000000,6.000000,1.0,1.0,2.000000,1.000000,0.0,1.0,22.000000,2.000000,134.000000,24.428571,37.213406,-108.595786,722.576715,4840.000000,2406.000000,2030.000000,480.000000,64.000000,19545.000000,254.000000,944.000000,1108.000000,538.000000,171.000000,611.000000,44.000000,20.000000,185.000000,44.000000,97.000000,62.000000,7.200000,1.200000,2.600000,0.900000,19545.000000,1044.000000,3.700000,1.300000,12.000000,0.100000,16.000000,0.000000,3.800000,0.800000,6.300000,1.300000,12.600000,0.100000,0.600000,0.400000,0.800000,0.400000,4.200000,1.200000,1.400000,1.000000,2.400000,0.700000,0.700000,0.300000,0.056700,0.086000,0.002500,0.008900,0.360500,0.027100,0.064000,0.028300,0.000000,0.206900,0.927400,0.035000,0.415500,0.418700,0.971000,0.494100,0.136900,0.186600,0.296400,0.050300,0.072900,2.012800,0.260700,4.27170,0.065600,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,229.000000,5.000000,1.400000,3059.000000,85.000000,0.000000,73.000000,84.000000,70.000000,38.000000,77.000000,34.000000,0.000000,42.000000,0.000000,76.000000,76.000000,79.000000,8.000000,79.000000,0.000000,79.000000,0.000000,79.000000,0.000000,34.000000,0.000000,34.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,35.000000,0.000000,0.000000,0.000000,35.000000,0.000000,0.000000,0.000000,35.000000,0.000000,0.000000,0.000000,6.000000,0.000000,0.000000,0.000000,0.000000,0.000000,34.000000,0.000000,0.000000,0.000000,64.000000,42.000000,55.000000,70.000000,76.000000,64.000000,76.000000,85.000000,0.000000,73.000000,38.000000,76.000000,4.000000,0.000000,0.000000,79.000000,0.000000,1494.0,1182.0,20.0,312.0,4443.0,4443.0,356.0,24.0,NaN,NaN,170140.0,2751.0,64531.0,NaN,NaN,NaN,NaN,27060.0,24557.0,272.0,4934.0,NaN,NaN,NaN,NaN,NaN,226370.0,4859.0,226370.0,4859.0,69465.0,NaN,NaN,NaN,194697.0,3997.0,NaN,0.000000,0.000000,0.000000
25%,8033.000000,0.001570,3.553169,3.756203,35.071429,43.214286,-0.045368,7.285714,1.000000,8.500000,1.0,1.0,2.500000,1.000000,0.0,1.0,37.000000,9.500000,548.000000,35.071429,37.453233,-107.412970,1129.068515,9105.500000,4461.500000,3559.500000,1363.500000,254.000000,23244.500000,606.000000,1647.500000,2455.500000,937.000000,292.000000,2541.000000,137.500000,133.500000,561.000000,104.500000,188.000000,124.500000,9.400000,2.000000,3.500000,1.150000,23244.500000,1222.000000,9.000000,1.600000,15.000000,0.200000,22.650000,0.100000,10.000000,1.350000,7.300000,1.800000,19.600000,0.200000,0.900000,0.800000,1.950000,0.850000,8.900000,1.650000,2.600000,1.050000,3.650000,1.150000,0.900000,0.350000,0.157500,0.193650,0.312550,0.274100,0.997200,0.203350,0.252150,0.537750,0.094200,0.343000,1.514000,0.191850,0.545050,0.545200,1.036300,0.531000,0.365350,0.415450,0.671150,0.181450,0.123050,2.174050,0.328250,6.38150,0.316600,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.500000,1104.500000,12.100000,1.800000,6486.000000,499.000000,43.000000,487.000000,498.000000,484.000000,452.000000,491.000000,448.000000,372.000000,456.000000,70.000000,490.000000,490.000000,493.000000,422.000000,493.000000,414.000000,493.000000,400.000000,493.000000,400.000000,448.000000,414.000000,448.000000,388.000000,388.000000,88.000000,129.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,205.000000,205.000000,205.000000,140.000000,140.000000,126.000000,126.000000,112.000000,112.000000,112.000000,165.000000,140.000000,112.000000,112.000000,449.000000,404.000000,275.000000,203.000000,449.000000,404.000000,275.000000,203.000000,449.000000,404.000000,275.000000,203.000000,420.000000,404.000000,275.000000,203.000000,281.000000,204.000000,448.000000,404.000000,281.000000,87.000000,478.000000,456.000000,469.000000,484.000000,490.000000,478.000000,490.000000,499.000000,64.500000,487.000000,452.000000,490.000000,418.000000,237.000000,145.000000,493.000000,333.000000,1494.0,1182.0,20.0,312.0,4443.0,4443.0,356.0,24.0,NaN,NaN,170140.0,2751.0,64531.0,NaN,NaN,NaN,NaN,27060.0,24557.0,272.0,4934.0,NaN,NaN,NaN,NaN,NaN,226370.0,4859.0,226370.0,4859.0,69465.0,NaN,NaN,NaN,194697.0,3997.0,NaN,0.020500,0.225000,0.189000
50%,8083.000000,0.032697,4.007333,4.163337,55.000000,64.285714,1.041620,11.000000,1.000000,10.000000,1.0,1.0,3.000000,1.000000,0.0,1.0,58.000000,24.000000,692.000000,55.000000,39.217538,-106.176447,2029.327837,16444.000000,6936.000000,6153.000000,1813.000000,531.000000,25846.000000,786.000000,2113.000000,2874.000000,1607.000000,387.000000,4558.000000,203.000000,235.000000,813.000000,178.000000,255.000000,265.000000,14.500000,2.700000,4.300000,1.400000,25846.000000,1631.000000,11.900000,2.000000,18.000000,0.200000,23.900000,0.200000,12.000000,1.500000,8.100000,2.200000,27.300000,0.200000,2.700000,1.100000,4.000000,1.200000,11.900000,2.200000,3.200000,1.200000,4.800000,1.700000,1.200000,0.400000,0.479900,0.292400,0.531800,0.485200,1.582900,0.379600,0.489300,0.712200,0.184000,0.490000,1.926100,0.425000,0.659300,0.827400,1.574000,0.843700,0.624000,0.542500,0.795300,0.338100,0.218400,2.565700,0.528500,7.39630,0.494600,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,1.000000,2237.000000,13.400000,2.400000,16662.000000,643.000000,159.000000,631.000000,642.000000,628.000000,596.000000,635.000000,592.000000,516.000000,600.000000,213.000000,634.000000,634.000000,637.000000,566.000000,637.000000,558.000000,637.000000,544.000000,637.000000,544.000000,592.000000,558.000000,592.000000,532.000000,532.000000,232.000000,273.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,349.000000,349.000000,349.000000,284.000000,284.000000,270.000000,270.000000,256.000000,256.000000,256.000000,309.000000,284.000000,256.000000,256.000000,593.000000,548.000000,419.000000,347.000000,593.000000,548.000000,419.000000,347.000000,593.000000,548.000000,419.000000,347.000000,564.000000,548.000000,419.000000,347.000000,425.000000,348.000000,592.000000,548.000000,425.000000,231.000000,622.000000,600.000000,613.000000,628.000000,634.000000,622.000000,634.000000,643.000000,202.000000,631.000000,596.000000,634.000000,562.000000,381.000000,289.000000,637.000000,477.000000,1494.0,1182.0,20.0,312.0,4443.0,4443.0,356.0,24.0,NaN,NaN,170140.0,2751.0,64531.0,NaN,NaN,NaN,NaN,27060.0,24557.0,272.0,4934.0,NaN,NaN,NaN,NaN,NaN,226370.0,4859.0,226370.0,4859.0,69465.0,NaN,NaN,NaN,194697.0,3997.0,NaN,0.066000,0.506000,0.453000

In [24]:
CDPHE_FP_TLGRF_TP.describe()

,fips,tau.hat,log_rolled_cases,shifted_log_rolled_cases,rolled_cases_x,shifted_rolled_cases,predictor,delta cases,capacity,rank_unfiltered,changepoint,outbreak,rank_filtered,delta_ranked,TLGRF_decision,CDPHE_decision,cases,deaths,days_from_start,rolled_cases_y,LAT,LON,AREA_SQMI,E_TOTPOP,E_HU,E_HH,E_POV,E_UNEMP,E_PCI,E_NOHSDP,E_AGE65,E_AGE17,E_DISABL,E_SNGPNT,E_MINRTY,E_LIMENG,E_MUNIT,E_MOBILE,E_CROWD,E_NOVEH,E_GROUPQ,EP_POV,MP_POV,EP_UNEMP,MP_UNEMP,EP_PCI,MP_PCI,EP_NOHSDP,MP_NOHSDP,EP_AGE65,MP_AGE65,EP_AGE17,MP_AGE17,EP_DISABL,MP_DISABL,EP_SNGPNT,MP_SNGPNT,EP_MINRTY,MP_MINRTY,EP_LIMENG,MP_LIMENG,EP_MUNIT,MP_MUNIT,EP_MOBILE,MP_MOBILE,EP_CROWD,MP_CROWD,EP_NOVEH,MP_NOVEH,EP_GROUPQ,MP_GROUPQ,EPL_POV,EPL_UNEMP,EPL_PCI,EPL_NOHSDP,SPL_THEME1,RPL_THEME1,EPL_AGE65,EPL_AGE17,EPL_DISABL,EPL_SNGPNT,SPL_THEME2,RPL_THEME2,EPL_MINRTY,EPL_LIMENG,SPL_THEME3,RPL_THEME3,EPL_MUNIT,EPL_MOBILE,EPL_CROWD,EPL_NOVEH,EPL_GROUPQ,SPL_THEME4,RPL_THEME4,SPL_THEMES,RPL_THEMES,F_POV,F_UNEMP,F_PCI,F_THEME1,F_AGE65,F_AGE17,F_DISABL,F_SNGPNT,F_THEME2,F_MINRTY,F_LIMENG,F_THEME3,F_MUNIT,F_CROWD,F_NOVEH,F_GROUPQ,F_THEME4,F_TOTAL,E_UNINSUR,EP_UNINSUR,MP_UNINSUR,E_DAYPOP,State_of_emergency_issued,State_of_emergency_lifted,Date_closed_K-12_public_schools,Date_banned_visitors_to_nursing_homes,Stay_at_home/_shelter_in_place,End/relax_stay_at_home/shelter_in_place,Closed_other_non-essential_businesses,Began_to_reopen_businesses,Face_mask_mandate_in_public_spaces,Face_mask_mandate_for_employees_of_public-facing_businesses,Ended_face_mask_mandate,Allowed_restaurants_to_sell_takeout_alcohol,Allowed_restaurants_to_deliver_alcohol,Closed_restaurants_except_take_out,Reopen_restaurants,Closed_gyms,Reopened_gyms,Closed_movie_theaters,Reopened_movie_theaters,Closed_Bars,Reopen_bars,Reopened_hair_salons/barber_shops,Reopened_religious_gatherings,Reopened_other_non-essential_retail,Began_to_reclose_bars,Closed_bars_(x2),Reopened_bars_(x2),Date_vaccine_allocation_plan_last_updated,Vaccine_allocation_phase:_Frontline_Healthcare_Workers,Vaccine_allocation_phase:_Healthcare_Service_Workers,Vaccine_allocation_phase:_Home_Healthcare_Workers,Vaccine_allocation_phase:_Additional_Healthcare_Workers,Vaccine_allocation_phase:_Long-term_Care_Residents,Vaccine_allocation_phase:_EMS_Providers,Vaccine_allocation_phase:_Firefighters,Vaccine_allocation_phase:_Law_Enforcement_&_Public_Safety_Personnel,Vaccine_allocation_phase:_Correctional_Staff,Vaccine_allocation_phase:_Adults_Ages_75+,Vaccine_allocation_phase:_Adults_Ages_65+,Vaccine_allocation_phase:_Adults_w/_High-Risk_Medical_Conditions,Vaccine_allocation_phase:_Pre-K-12_School_Employees,Vaccine_allocation_phase:_Higher_Education_Employees,Vaccine_allocation_phase:_Public_Transit_Workers,Vaccine_allocation_phase:_Food_Supply_Workers,Vaccine_allocation_phase:_Grocery_Store_Workers,Vaccine_allocation_phase:_Frontline_Essential_Workers,Vaccine_allocation_phase:_Additional_Essential_Workers,Date_adults_ages_80+_became_eligible_for_COVID-19_vaccination,Date_adults_ages_75+_became_eligible_for_COVID-19_vaccination,Date_adults_ages_70+_became_eligible_for_COVID-19_vaccination,Date_adults_ages_65+_became_eligible_for_COVID-19_vaccination,Date_adults_ages_60+_became_eligible_for_COVID-19_vaccination,Date_adults_ages_55+_became_eligible_for_COVID-19_vaccination,Date_adults_ages_50+_became_eligible_for_COVID-19_vaccination,Date_adults_ages_45+_became_eligible_for_COVID-19_vaccination,Date_adults_ages_40+_became_eligible_for_COVID-19_vaccination,Date_adults_ages_30+_became_eligible_for_COVID-19_vaccination,Date_K-12_school_employees_became_eligible_for_COVID-19_vaccination,Date_grocery_store_workers_became_eligible_for_COVID-19_vaccination,Date_incarcerated_people_became_eligible_for_COVID-19_vaccination,Date_general_public_became_eligible_for_COVID-19_vaccination,First_overall_eviction_moratorium_start,First_overall_eviction_moratorium_end,Second_overall_eviction_moratorium_start,Second_overall_eviction_moratorium_end,First_eviction_initiation_ban_start,First_eviction_initiation_ban_end,Second_Eviction_Initiation_Ban_Start,Second_Eviction_Initiation_Ban_End,First_eviction_enforcement_ban_start,First_eviction_enforcement_ban_end,Second_Eviction_Enforcement_Ban_Start,Second_Eviction_Enforcement_Ban_End,COVID-19_hardship_limitation_start,COVID-19_hardship_limitation_end,Second_COVID-19_hardship_limitation_start,Second_COVID-19_hardship_limitation_end,CDC_moratorium_start,CDC_moratorium_end,Late_Fee_Ban_Start,Late_Fee_Ban_End,Second_Late_Fee_Ban_Start,Second_Late_Fee_Ban_End,SNAP_Waiver_-_Emergency_Allotments_to_Current_SNAP_Households,SNAP_Waiver_-_Pandemic_EBT_during_school_year_2019-2020,SNAP_Waiver_-_Temporary_Suspension_of_Claims_Collection,Modify_Medicaid_requirements_with_1135_waivers_(date_of_CMS_approval),Reopened_ACA_enrollment_using_a_special_enrollment_period,Allow_audio-only_telehealth,Allow/expand_Medicaid_telehealth_coverage,Stopped_personal_visitation_in_state_prisons,Resumed_visitation_in_state_prisons,Suspended_elective_medical_procedures,Resumed_elective_medical_procedures,Waived_one_week_waiting_period_for_unemployment_insurance,Extended_Benefits_program_activated,Extended_Benefits_program_deactivated,Extended_Benefits_program_activated_x2,Closed_casinos,Reopened_casinos,death,deathConfirmed,deathIncrease,deathProbable,hospitalized,hospitalizedCumulative,hospitalizedCurrently,hospitalizedIncrease,inIcuCumulative,inIcuCurrently,negative,negativeIncrease,negativeTestsAntibody,negativeTestsPeopleAntibody,negativeTestsViral,onVentilatorCumulative,onVentilatorCurrently,positive,positiveCasesViral,positiveIncrease,positiveTestsAntibody,positiveTestsAntigen,positiveTestsPeopleAntibody,positiveTestsPeopleAntigen,positiveTestsViral,recovered,totalTestEncountersViral,totalTestEncountersViralIncrease,totalTestResults,totalTestResultsIncrease,totalTestsAntibody,totalTestsAntigen,totalTestsPeopleAntibody,totalTestsPeopleAntigen,totalTestsPeopleViral,totalTestsPeopleViralIncrease,totalTestsViral,metrics.testPositivityRatio,metrics.vaccinationsInitiatedRatio,metrics.vaccinationsCompletedRatio
count,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.0,107.0,107.000000,107.000000,107.0,107.0,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.00000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.0,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,107.000000,28.000000,24.000000,28.000000,24.000000,28.000000,28.000000,28.000000,28.000000,0.0,0.0,2.800000e+01,28.000000,24.000000,0.0,0.0,0.0,0.0,28.000000,26.000000,28.000000,24.000000,0.0,0.0,0.0,0.0,0.0,2.800000e+01,28.000000,2.800000e+01,28.000000,24.000000,0.0,0.0,0.0,2.800000e+01,28.000000,0.0,107.000000,107.000000,107.000000
mean,8047.224299,0.030132,7.392594,7.608428,4357.695594,5115.526035,107.741046,757.830441,1.252336,3.214953,0.0,0.0,1.093458,1.093458,1.0,0.0,4738.869159,744.336449,581.663551,4357.695594,38.709640,-105.039705,2038.314646,521236.971963,204267.850467,192079.065421,55206.336449,15550.037383,32363.785047,21101.373832,63338.009346,127693.420561,61576.214953,16923.785047,158647.196262,7547.579439,25351.140187,6588.934579,5383.514019,8239.523364,14041.373832,11.313084,0.993458,5.904673,0.645794,32363.785047,1013.700935,6.747664,0.653271,13.495327,0.188785,23.428037,0.135514,12.553271,0.672897,8.421495,0.833645,28.797196,0.275701,1.593458,0.389720,11.421495,0.701869,5.373832,0.657944,2.720561,0.46729,4.364486,0.597196,3.219626,0.446729,0.266186,0.554864,0.207166,0.120249,1.148465,0.250207,0.151238,0.667960,0.240710,0.549869,1.609778,0.269450,0.672658,0.674446,1.347104,0.719351,0.853172,0.226972,0.695254,0.271261,0.607450,2.654109,0.580182,6.759456,0.385555,0.009346,0.018692,0.028037,0.056075,0.037383,0.009346,0.037383,0.009346,0.093458,0.009346,0.009346,0.018692,0.785047,0.009346,0.0,0.037383,0.831776,1.000000,36972.102804,8.085047,0.876636,462949.467290,532.663551,135.149533,520.663551,531.663551,517.663551,486.074766,524.663551,482.168224,409.588785,490.000000,167.411215,523.663551,523.663551,526.663551,457.112150,526.663551,449.485981,526.663551,436.140187,526.663551,436.140187,482.168224,449.485981,482.168224,424.700935,424.700935,179.233645,207.429907,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,264.420561,264.420561,264.420561,215.457944,215.457944,205.271028,205.271028,195.308411,195.308411,195.308411,234.000000,215.457944,195.308411,195.308411,483.140187,439.953271,321.495327,262.887850,483.140187,439.953271,321.495327,262.887850,483.140187,439.953271,321.495327,262.887850,455.205607,439.953271,321.495327,262.887850,326.869159,263.654206,482.168224,439.953271,326.869159,178.588785,511.672897,490.000000,502.757009,517.663551,523.663551,511.672897,523.663551,532.663551,160.728972,520.663551,486.074766,523.663551,453.299065,289.046729,219.149533,526.663551,373.962617,2447.607143,2331.958333,20.964286,441.041667,9911.321429,9911.321429,982.678571,138.535714,NaN,NaN,9.983991e+05,8701.035714,174903.625000,NaN,NaN,NaN,NaN,141164.035714,143702.461538,2171.928571,16911.583333,NaN,NaN,NaN,NaN,NaN,2.061587e+06,24064.821429,2.061587e+06,24064.821429,192303.791667,NaN,NaN,NaN,1.132378e+06,10685.857143,NaN,0.107523,0.389720,0.334729
std,16.980182,0.029628,1.777198,1.696876,5786.905654,6644.972696,211.256867,1530.480263,0.477680,3.389852,0.0,0.0,0.292443,0.292443,0.0,0.0,6234.461754,648.681012,266.485546,5786.905654,0.626785,1.377146,425.718939,288870.898500,111413.431719,106097.986882,30695.759839,8709.368899,5262.032580,11581.608717,34465.087993,71444.512013,34376.519658,9521.320598,89117.245107,4222.932974,14082.126322,2968.179530,2982.151197,4593.786569,7659.968169,2.784190,1.114677,1.535024,0.812320,5262.032580,1437.961668,1.882509,0.745846,3.440666,0.478269,2.692050,0.713912,3.175951,0.879061,1.298114,0.940287,5.725011,1.242095,0.655351,0.448884,4.355977,0.662041,4.604332,0.956017,0.490810,0.54544,1.193556,0.662536,3.502033,1.165731,0.145796,0.167690,0.176544,0.123977,0.489885,0.143242,0.200587,0.263569,0.193176,0.179705,0.415644,0.160274,0.076929,0.128301,0.183583,0.106913,0.188679,0.199826,0.115148,0.152451,0.168944,0.257195,0.114736,1.027987,0.147822,0.096674,0.136071,0.165856,0.359028,0.190592,0.096674,0.190592,0.096674,0.376997,0.096674,0.096674,0.136071,0.412723,0.096674,0.0,0.190592,0.375826,0.598741,20035.025486,1.751862,0.982448,255613.753365,266.485546,174.006983,266.485546,266.485546,266.485546,265.709577,266.485546,265.537706,259.723581,265.848162,192.100698,266.485546,266.485546,266.485546,263.851564,266.485546,263.202460,266.485546,262.089084,266.485546,262.089084,265.537706,263.202460,265.537706,261.157843,261.157843,198.523350,210.676857,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,231.072726,231.072726,231.072726,213.665286,213.665286,209.843588,209.843588,205.918394,205.918394,205.918394,220.412007,213.665286,205.918394,205.918394,265.589144,262.404246,246.811913,230.533889,265.589144,262.404246,246.811913,230.533889,265.589144,262.404246,246.811913,230.533889,263.688415,262.404246,246.811913,230.533889,247.640644,230.803073,265.537706,262.404246,247.640644,198.200011,266.467414,265.848162,266.305749,266.485546,266.485546,266.467414,266.485546,266.485546,188.341399,266.485546,265.709577,266.485546,263.525847,239.815235,215.004335,266.485546,254.548173,1391.071139,1093.250696,22.128383,120.429478,5794.010375,5794.010375,597.925553,167.818350,NaN,NaN,6.529334e+05,5617.150619,61802.376785,NaN,NaN,NaN,NaN,120673.758206,113486.325975,1906.659400,11800.562138,NaN,NaN,NaN,NaN,NaN,1.668982e+06,18224.495185,1.668982e+06,18224.495185,73635.985720,NaN,NaN,NaN,7.627239e+05,7217.585201,NaN,0.082415,0.318838,0.282982
min,8011.000000,0.003411,3.522150,3.678107,33.857143,39.571429,0.432717,0.857143,1.000000,1.000000,0.0,0.0,1.000000,1.000000,1.0,0.0,38.000000,0.000000,69.000000,33.857143,37.213406,-108.595786,787.427181,1841.000000,1495.000000,740.000000,250.000000,9.000000,14777.000000,115.000000,471.000000,356.000000,411.000000,55.000000,167.000000,0.000000,0.000000,151.000000,13.000000,12.000000,0.000000,7.200000,0.500000,1.000000,0.300000,14777.000000,381.000000,3.700000,0.300000,12.000000,0.000000,12.700000,0.000000,3.800000,0.300000,4.800000,0.400000,9.100000,0.100000,0.000000,0.200000,0.000000,0.400000,2.200000,0.200000,0.700000,0.20000,1.600000,0.300000,0.000000,0.100000,0.056700,0.014000,0.002500,0.008900,0.263400,0.012400,0.064000,0.003800,0.000000,0.073500,0.483900,0.007600,0.316500,0.000000,0.316500,0.127000,0.000000,0.083100,0.078000,0.020100,0.000000,1.214300,0.044600,3.873200,0.033100,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,93.000000,5.100000,0.400000,1315.000000,20.000000,0.000000,8.000000,19.000000,5.000000,0.000000,12.000000,0.000000,0.000000,0.000000,0.000000,11.000000,11.000000,14.000000,0.000000,14.000000,0.000000,14.000000,0.000000,14.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,11.000000,0.000000,11.000000,20.000000,0.000000,8.000000,0.000000,11.000000,0.000000,0.000000,0.000000,14.000000,0.000000,51.000000,1036.000000,0.000000,273.000000,414.000000,414.000000,270.000000,14.000000,NaN,NaN,1.273700e+04,0.000000,38142.000000,NaN,NaN,NaN,NaN,2627.000000,12741.000000,320.000000,3315.000000,NaN,NaN,NaN,NaN,NaN,1.710700e+04,1633.000000,1.710700e+04,1633.000000,41457.000000,NaN,NaN,NaN,1.536400e+04,753.000000,NaN,0.000000,0.000000,0.000000
25%,8041.000000,0.010715,6.126504,6.487335,458.142857,664.000000,14.582311,89.428571,1.000000,1.000000,0.0,0.0,1.000000,1.000000,1.0,0.0,556.000000,89.500000,381.500000,458.142857,38.827383,-104.527472,2126.844422,373345.500000,148032.000000,137586.000000,39046.500000,10993.500000,32348.000000,16266.000000,45939.000000,92006.500000,43462.000000,11975.000000,114308.500000,6375.000000,18507.500000,5950.500000,4168.000000,5795.000000,10176.500000,10.900000,0.500000,6.200000,0.300000,32348.000000,381.000000,6.300000,0.300000,12.100000,0.100000,24.600000,0.000000,12.400000,0.300000,8.900000,0.400000,30.500000,0.100000,1.600000,0.200000,12.500000,0.400000,3.100000,0.200000,2.800000,0.20000,4.300000,0.300000,2.700000,0.100000,0.242700,0.620700,0.162400,0.083400,1.109200,0.237900,0.067500,0.792700,0.212000,0.623400,1.695600,0.264600,0.698500,0.705200,1.403700,0.753900,0.920100,0.125800,0.724900,0.256300,0.625000,2.652100,0.578200,6.860600,0.392700,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.0,0.000000,1.000000,1.000000,29207.500000,7.400000,0.400000,332452.000000,332.500000,0.000000,320.500000,331.500000,317.500000,285.500000,324.500000,281.500000,205.500000,289.500000,0.000000,323.500000,323.500000,326.500000,255.500000,326.500000,247.500000,326.500000,233.500000,326.500000,233.500000,281.500000,247.500000,281.500000,221.500000,221.500000,0.000000,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,38.500000,38.500000,38.500000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.500000,0.000000,0.000000,0.000000,282.500000,237.500000,108.500000,36.500000,282.500000,237.500000,108.500000,36.500000,282.500000,237.500000,108.500000,36.500000,253.500000,237.500000,108.500000,36.500000,114.500000,37.500000,281.500000,237.500000,114.500000,0.000000,311.500000,289.500000,302.500000,317.500000,323.500000,311.500000,323.500000,332.500000,0.000000,320.500000,285.500000,323.500000,251.500000,70.500000,0.000000,326.500000,166.500000,1740.500000,1672.750000,4.000000,360.000000,5959.750000,5959.750000,459.000000,38.000000,NaN,NaN,3.811455e+05,5280.500000,152358.500000,NaN,NaN,NaN,NaN,38355.000000,42369.750000,524.250000,11452.250000,NaN,NaN,NaN,NaN,NaN,5.189678e+05,8568.000000,5.189678e+05,8568.000000,163810.750000,NaN,NaN,NaN,4.164702e+05,5449.250000,NaN,0.072000,0.000000,0.000000

### t-test

In [25]:
def t_test_results(df1, df2):
    LAT_loc = df1.columns.get_loc("LAT")
    CDPHE_TP_loc = df1.columns.get_loc("CDPHE_TP")
    t_test_results = pd.DataFrame(columns=['Column', 't-statistic', 'p-value', 'Standard Error', 'Confidence Interval'])

    for column in df1.columns[LAT_loc:CDPHE_TP_loc]:
        t_statistic, p_value = ttest_ind(df1[column], df2[column])
        mean1, mean2 = df1[column].mean(), df2[column].mean()
        std1, std2 = df1[column].std(), df2[column].std()
        n1, n2 = len(df1[column]), len(df2[column])

        standard_error = np.sqrt((std1 ** 2 / n1) + (std2 ** 2 / n2))
        confidence_interval = (mean1 - mean2) - (1.96 * standard_error), (mean1 - mean2) + (1.96 * standard_error)


        if not math.isnan(t_statistic) and not math.isinf(t_statistic):
            t_test_results = t_test_results.append({
            'Column': column,
            't-statistic': t_statistic,
            'p-value': p_value,
            'Standard Error': standard_error,
            'Confidence Interval': confidence_interval
        }, ignore_index=True)
            #print("Column:", column)
            #print("T-statistic:", t_statistic)
            #print("P-value:", p_value)
            #print()
    return t_test_results

In [26]:
CDPHE_right_vs_TLGRF_right = t_test_results(CDPHE_TP_TLGRF_FP, CDPHE_FP_TLGRF_TP)
CDPHE_right_vs_TLGRF_right = CDPHE_right_vs_TLGRF_right[CDPHE_right_vs_TLGRF_right["p-value"] <= 0.05].T
CDPHE_right_vs_TLGRF_right

,3,4,5,6,7,9,10,11,12,13,14,15,16,17,18,19,20,21,22,24,26,27,28,29,34,36,39,40,41,42,43,44,45,46,48,51,53,54,55,56,57,62,67,68,71,75,77,79,81,85,86,87,88,89,91,93,94,95,96
Column,E_TOTPOP,E_HU,E_HH,E_POV,E_UNEMP,E_NOHSDP,E_AGE65,E_AGE17,E_DISABL,E_SNGPNT,E_MINRTY,E_LIMENG,E_MUNIT,E_MOBILE,E_CROWD,E_NOVEH,E_GROUPQ,EP_POV,MP_POV,MP_UNEMP,MP_PCI,EP_NOHSDP,MP_NOHSDP,EP_AGE65,MP_DISABL,MP_SNGPNT,EP_LIMENG,MP_LIMENG,EP_MUNIT,MP_MUNIT,EP_MOBILE,MP_MOBILE,EP_CROWD,MP_CROWD,MP_NOVEH,EPL_POV,EPL_PCI,EPL_NOHSDP,SPL_THEME1,RPL_THEME1,EPL_AGE65,RPL_THEME2,EPL_MUNIT,EPL_MOBILE,EPL_GROUPQ,RPL_THEMES,F_UNEMP,F_THEME1,F_AGE17,F_MINRTY,F_LIMENG,F_THEME3,F_MUNIT,F_CROWD,F_THEME4,E_UNINSUR,EP_UNINSUR,MP_UNINSUR,E_DAYPOP
t-statistic,-4.568835,-4.599507,-4.577662,-4.524236,-4.539199,-4.466744,-4.603176,-4.531312,-4.542365,-4.524077,-4.502784,-4.29883,-4.576323,-4.826527,-4.4792,-4.543534,-4.687868,2.7724,4.150551,3.604177,2.200115,4.636503,4.457232,2.552866,2.630845,3.882277,4.267731,4.174374,-2.506326,3.137885,3.902197,3.954351,2.926134,4.297591,4.014428,2.990615,3.980215,5.191577,2.972375,3.032959,3.394309,2.473738,-3.572746,3.921496,-3.243656,2.107614,3.933415,2.423941,4.820009,2.664333,4.820009,5.798464,-4.005697,2.664333,-3.657716,-4.477984,5.868925,3.843234,-4.57596
p-value,0.000013,0.000011,0.000012,0.000015,0.000014,0.000019,0.000011,0.000015,0.000014,0.000015,0.000017,0.000037,0.000012,0.000004,0.000018,0.000014,0.000008,0.006519,0.000065,0.000469,0.029852,0.00001,0.00002,0.01203,0.009717,0.000175,0.000041,0.000059,0.013635,0.002175,0.000163,0.000135,0.004156,0.000037,0.000108,0.003424,0.000123,0.000001,0.003618,0.00301,0.000952,0.014871,0.000522,0.000152,0.001556,0.037295,0.000146,0.016954,0.000005,0.008853,0.000005,0.0,0.000112,0.008853,0.000389,0.000018,0.0,0.000202,0.000012
Standard Error,28768.511358,11140.456062,10553.041671,3030.188191,858.698771,1263.411694,3438.972306,7135.393764,3388.496905,937.163399,8910.091427,547.018299,1447.374501,440.790417,328.166222,449.587727,757.044602,2.493501,0.441526,0.370939,846.525091,1.369738,0.188518,1.287812,0.190267,0.292126,0.88583,0.205483,3.280335,0.395486,2.157908,0.279767,0.547356,0.165548,0.291525,0.131819,0.126981,0.083636,0.432577,0.127367,0.099047,0.124925,0.115319,0.082065,0.131258,0.124754,0.184896,0.299399,0.184664,0.143163,0.184664,0.202458,0.148324,0.143163,0.187972,2292.372176,1.416416,0.271379,25585.915605
Confidence Interval,"(-557358.8256530971, -444586.2611292794)","(-216353.57292004646, -172682.98515739013)","(-205038.31280999738, -163670.38945969552)","(-58651.64816013898, -46773.310451342986)","(-16688.658402926794, -13322.559220571206)","(-22120.517894767097, -17167.94405449859)","(-66960.96649490841, -53480.195053823234)","(-136871.36376650207, -108900.62021213613)","(-65910.95460129385, -52628.04673381963)","(-18186.625307921375, -14512.944785536569)","(-169782.832600808, -134855.27420827077)","(-7972.306733915086, -5827.9950017324445)","(-27301.851352184993, -21628.143307361064)","(-6314.883797126655, -4586.985361751849)","(-5715.719812964098, -4429.308224419079)","(-8803.286738376355, -7040.902847738465)","(-15113.752679951986, -12146.137840742276)","(-1.5289177871921336, 8.245606705750214)","(0.9411504051880055, 2.6719337069615277)","(0.42716573536668745, 1.8812454795865858)","(-380.7472564005052, 2937.6311015273413)","(0.9533649519605074, 6.322736516664335)","(0.9058049242369142, 1.6447958768311792)","(0.8948466123534953, 5.943070610610464)","(0.5113222661319188, 1.2571690556304331)","(0.8366445712355645, 1.9817799948525532)","(-0.3439697531000496, 3.1284824366781594)","(0.3361050120257979, 1.141598592780611)","(-11.008094689703817, 1.8508183212124978)","(0.06583543555089477, 1.6161405324063818)","(2.8680979746363073, 11.327095616818951)","(0.9079981671336494, 2.0046854109704872)","(-0.40766367415339944, 1.7379707502548574)","(0.5796640070457182, 1.2286136965590877)","(0.4742722004513228, 1.617049561898479)","(-0.06822252508202414, 0.44850770532234546)","(0.04342163839369101, 0.541188508468792)","(0.10105270919259265, 0.4289072374028683)","(-0.21645903426656488, 1.479242478859354)","(-0.0609467077164598, 0.4383336236043105)","(0.07601558321773119, 0.4642792098396785)","(-0.07748990475856352, 0.41221754160769475)","(-0.49971077902787475, -0.04766171763434257)","(0.14580879431042124, 0.46750442331307596)","(-0.48844496145148053, 0.02608688401489856)","(-0.11081567469534692, 0.37821968003580053)","(-0.09537406928534997, 0.6294194631438279)","(-0.21432635711396758, 0.9593196815465443)","(-0.08557377878290517, 0.6383107614264298)","(-0.14708719077222948, 0.41410988770146845)","(-0.08557377878290517, 0.6383107614264298)","(0.013061557072335639, 0.8066981225004279)","(-0.9329054187836778, -0.3514737534459615)","(-0.14708719077222948, 0.41410988770146845)","(-0.9144874670678268, -0.17763536337276065)","(-38569.15226953278, -29583.05333794385)","(1.5959213484770753, 7.148270907864733)","(0.9200334944429942, 1.9838383346624786)","(-494145.1475904467, -393848.358417564)"

In [27]:
CDPHE_TP = reduced_decision_set_augmented[reduced_decision_set_augmented["CDPHE_TP"] == 1]
TLGRF_FP = reduced_decision_set_augmented[reduced_decision_set_augmented["TLGRF_FP"] == 1]
CDPHE_TP_TLGRF_FP_t_test = t_test_results(CDPHE_TP, TLGRF_FP)
CDPHE_TP_TLGRF_FP_t_test = CDPHE_TP_TLGRF_FP_t_test[CDPHE_TP_TLGRF_FP_t_test["p-value"] <= 0.10]
CDPHE_TP_TLGRF_FP_t_test

,Column,t-statistic,p-value,Standard Error,Confidence Interval
17,E_MOBILE,-2.506026,0.014805,479.890634,"(-3102.764914975792, -1221.5936284415743)"
20,E_GROUPQ,-1.797327,0.077077,1516.809490,"(-6878.429794393585, -932.5365921610351)"
71,EPL_GROUPQ,-2.171059,0.033701,0.085730,"(-0.3659362430263178, -0.02987636201569885)"
76,F_UNEMP,1.975121,0.052640,0.099013,"(-0.07081663181013857, 0.31731523124991445)"
80,F_AGE17,3.671664,0.000498,0.113804,"(-0.008769987622679332, 0.4373414161941079)"
83,F_THEME2,2.159915,0.034592,0.140489,"(-0.035861776453116306, 0.5148533730917718)"
84,F_MINRTY,1.949966,0.055633,0.071429,"(-0.06857142857142856, 0.2114285714285714)"
178,metrics.testPositivityRatio,2.126852,0.037355,0.068831,"(-0.05194323597010839, 0.21787320795890394)"

In [28]:
CDPHE_FP = reduced_decision_set_augmented[reduced_decision_set_augmented["CDPHE_FP"] == 1]
TLGRF_TP = reduced_decision_set_augmented[reduced_decision_set_augmented["TLGRF_TP"] == 1]
CDPHE_FP_TLGRF_TP_t_test = t_test_results(CDPHE_FP, TLGRF_TP)
CDPHE_FP_TLGRF_TP_t_test = CDPHE_FP_TLGRF_TP_t_test[CDPHE_FP_TLGRF_TP_t_test["p-value"] <= 0.10]
CDPHE_FP_TLGRF_TP_t_test

,Column,t-statistic,p-value,Standard Error,Confidence Interval
1,LON,-1.919448,5.600958e-02,0.203413,"(-0.8051176568717431, -0.007737684362354613)"
2,AREA_SQMI,-4.104536,5.409961e-05,90.759062,"(-574.3992983023662, -218.62377442228225)"
3,E_TOTPOP,-18.407931,3.438089e-49,28735.231742,"(-521162.31975350034, -408520.21132585366)"
4,E_HU,-18.325152,6.705465e-49,11125.773691,"(-201172.17508478236, -157559.1422150898)"
5,E_HH,-18.364381,4.885678e-49,10597.014207,"(-191992.12443408612, -150451.82874355998)"
...,...,...,...,...,...
94,E_UNINSUR,-18.505654,1.563335e-49,2011.136082,"(-36558.7907610032, -28675.13732079069)"
95,EP_UNINSUR,6.791267,7.378981e-11,0.342909,"(1.845006671656144, 3.1892096638846965)"
96,MP_UNINSUR,11.075112,1.189632e-23,0.123979,"(1.1197813008746547, 1.6057792893426073)"
97,E_DAYPOP,-18.500794,1.625811e-49,25471.898679,"(-463753.6915388886, -363903.848719041)"
179,metrics.testPositivityRatio,-3.472532,6.026091e-04,0.013705,"(-0.07348391879549619, -0.01976192760859365)"

In [29]:
CDPHE_FP_TLGRF_FP_t_test = t_test_results(CDPHE_FP, TLGRF_FP)
CDPHE_FP_TLGRF_FP_t_test = CDPHE_FP_TLGRF_FP_t_test[CDPHE_FP_TLGRF_FP_t_test["p-value"] <= 0.10]
CDPHE_FP_TLGRF_FP_t_test

,Column,t-statistic,p-value,Standard Error,Confidence Interval
2,AREA_SQMI,-2.454025,1.498211e-02,164.327913,"(-697.6437924173192, -53.478371988962465)"
3,E_TOTPOP,-6.509432,5.951014e-10,41130.351346,"(-244673.1840033743, -83442.2067251025)"
4,E_HU,-6.473679,7.239669e-10,15863.341547,"(-94367.34265322104, -32183.043790098025)"
5,E_HH,-6.476045,7.146526e-10,15124.428634,"(-90011.14515291149, -30723.384908119544)"
6,E_POV,-6.523226,5.516572e-10,4368.733199,"(-25686.234666082222, -8560.800524152814)"
7,E_UNEMP,-6.696405,2.112545e-10,1236.926963,"(-7376.126750870245, -2527.373054349856)"
8,E_PCI,-1.868522,6.315163e-02,1441.372846,"(-5616.620839669088, 33.56071760701434)"
9,E_NOHSDP,-6.289641,1.964896e-09,1644.569722,"(-9663.845422081546, -3217.1321133034694)"
10,E_AGE65,-6.259051,2.315590e-09,4939.559735,"(-29010.576686616063, -9647.502523876085)"
11,E_AGE17,-6.575683,4.131361e-10,10143.745558,"(-60393.195649943984, -20629.71306321015)"
12,E_DISABL,-6.582003,3.989543e-10,4885.043202,"(-28863.522359598785, -9714.15300723669)"
13,E_SNGPNT,-6.679336,2.323711e-10,1348.921464,"(-8049.484304069612, -2761.712163921556)"
14,E_MINRTY,-6.777326,1.342122e-10,12604.079199,"(-75840.06677974126, -26432.076318557672)"
15,E_LIMENG,-5.917959,1.395885e-08,597.784566,"(-3451.4131050287097, -1108.0976078657195)"
16,E_MUNIT,-6.053420,6.892255e-09,2009.008177,"(-11814.574349159619, -3939.262295431992)"
17,E_MOBILE,-6.761726,1.465145e-10,455.556432,"(-2917.577919389743, -1131.796707282118)"
18,E_CROWD,-6.958981,4.791958e-11,421.985832,"(-2571.5543781173496, -917.3699174286829)"
19,E_NOVEH,-6.420217,9.693441e-10,654.118530,"(-3852.432271681446, -1288.2876348242035)"
20,E_GROUPQ,-5.987728,9.717499e-09,1111.781953,"(-6414.815650087287, -2056.6303958807684)"
21,EP_POV,2.672020,8.161259e-03,0.725145,"(0.9352529867868362, 3.777823237080219)"
22,MP_POV,4.391641,1.822112e-05,0.208734,"(0.48427136662861603, 1.3025095709119663)"
24,MP_UNEMP,4.020685,8.219138e-05,0.145825,"(0.36499515743004707, 0.9366280083925732)"
25,EP_PCI,-1.868522,6.315163e-02,1441.372846,"(-5616.620839669088, 33.56071760701434)"
28,MP_NOHSDP,2.736653,6.765670e-03,0.172703,"(0.09129126464929477, 0.7682854137041677)"
29,EP_AGE65,3.352755,9.568556e-04,0.646378,"(1.2468892331792603, 3.7806916004787112)"
30,MP_AGE65,1.773729,7.762960e-02,0.095009,"(0.022327343040850794, 0.39476134673969654)"
32,MP_AGE17,1.698183,9.102843e-02,0.113443,"(0.012828377513698946, 0.4575261219019612)"
33,EP_DISABL,1.886452,6.068313e-02,0.783125,"(0.10875736894441368, 3.178607908292289)"
34,MP_DISABL,4.089834,6.253980e-05,0.133893,"(0.25673592727044714, 0.7815967567965564)"
36,MP_SNGPNT,3.373598,8.908953e-04,0.168374,"(0.188802576670125, 0.848828899761508)"
40,MP_LIMENG,2.528223,1.223684e-02,0.107928,"(0.05285539822836671, 0.47593307080162994)"
42,MP_MUNIT,1.827146,6.916819e-02,0.128575,"(-0.020647849315226285, 0.4833669767012803)"
44,MP_MOBILE,3.455039,6.717583e-04,0.169263,"(0.23894965154250825, 0.9024605549241809)"
46,MP_CROWD,2.834798,5.056207e-03,0.126274,"(0.08853792630852406, 0.5835306362158216)"
48,MP_NOVEH,2.412000,1.676843e-02,0.152881,"(0.022402373883316673, 0.6216957951856382)"
51,EPL_POV,2.928085,3.806038e-03,0.039571,"(0.055055575459783665, 0.21017249881628486)"
53,EPL_PCI,2.669897,8.211226e-03,0.046824,"(0.042778146157730276, 0.22632677528104367)"
55,SPL_THEME1,2.177820,3.058949e-02,0.145406,"(0.058813774618699244, 0.6288068720505628)"
56,RPL_THEME1,2.205506,2.855785e-02,0.042747,"(0.01813814144121663, 0.18570826811598395)"
57,EPL_AGE65,3.390305,8.411163e-04,0.045624,"(0.07911492087748938, 0.257961173136274)"
58,EPL_AGE17,-1.775118,7.739930e-02,0.054125,"(-0.20285125205563542, 0.009319658756063928)"
59,EPL_DISABL,2.649657,8.701504e-03,0.047180,"(0.045819067268399044, 0.23076306492222518)"
63,EPL_MINRTY,-1.772496,7.783451e-02,0.021961,"(-0.08534119678228147, 0.0007470921205501233)"
67,EPL_MUNIT,-2.764943,6.225856e-03,0.048160,"(-0.22839463318230585, -0.03960749641125434)"
68,EPL_MOBILE,1.698434,9.098107e-02,0.039397,"(-0.01502700098014155, 0.13940900331749928)"
76,F_POV,1.788964,7.513405e-02,0.019330,"(0.021714889724662526, 0.0974904082885825)"
78,F_PCI,1.854473,6.514371e-02,0.038982,"(0.016829716864257938, 0.1696395728383781)"
79,F_THEME1,2.117344,3.546623e-02,0.064587,"(0.0794869321185723, 0.3326673335612096)"
80,F_AGE65,2.889060,4.289879e-03,0.036924,"(0.08682932476757463, 0.23157088299765063)"
81,F_AGE17,2.359938,1.924087e-02,0.024423,"(0.05146938506941966, 0.14720611161932207)"
84,F_THEME2,3.700375,2.782353e-04,0.062112,"(0.16458665941932446, 0.40806624280116643)"
88,F_MUNIT,-3.084376,2.328197e-03,0.076848,"(-0.36371170379378814, -0.06246671459343425)"
90,F_NOVEH,-1.729190,8.531806e-02,0.019608,"(-0.05803921568627452, 0.018823529411764718)"
92,F_THEME4,-2.756195,6.388439e-03,0.091637,"(-0.42983574115506906, -0.0706187452752646)"
94,E_UNINSUR,-6.711317,1.943586e-10,2853.976369,"(-17190.19064492845, -6002.603277938708)"
96,MP_UNINSUR,3.125900,2.036514e-03,0.191421,"(0.1536942495852387, 0.904064483046884)"
97,E_DAYPOP,-6.603687,3.538393e-10,36404.718835,"(-218190.465382001, -75483.96754878717)"

In [30]:
CDPHE_FP.shape

(151, 267)

In [31]:
TLGRF_FP.shape

(51, 267)