In [1]:
list.of.packages <- c("ggplot2", "Rcpp", "grf", "caret", "mltools", "rpart", "minpack.lm", "doParallel", "rattle", "anytime","rlist")
list.of.packages <- c(list.of.packages, "zoo", "dtw", "foreach", "evaluate","rlist","data.table","plyr","dplyr")


new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[,"Package"])]
if(length(new.packages)) install.packages(new.packages, lib='/home/zwang937/local/R_libs', repos="http://cran.us.r-project.org", dependencies = TRUE, INSTALL_opts = '--no-lock')


lapply(list.of.packages, require, character.only = TRUE)

Loading required package: ggplot2

Loading required package: Rcpp

Warning message:
“package ‘Rcpp’ was built under R version 4.3.2”
Loading required package: grf

Loading required package: caret

Loading required package: lattice

Error: package or namespace load failed for ‘caret’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 there is no package called ‘recipes’

Loading required package: mltools

Loading required package: rpart

Loading required package: minpack.lm

Loading required package: doParallel

Loading required package: foreach

Loading required package: iterators

Loading required package: parallel

Loading required package: rattle

Loading required package: tibble

Warning message:
“package ‘tibble’ was built under R version 4.3.2”
Loading required package: bitops

Rattle: A free graphical interface for data science with R.
Version 5.5.1 Copyright (c) 2006-2021 Togaware Pty Ltd.
Type 'rattle()' to shake, rattle, and roll your data.

Loading required package: anytime

Loading required package: rlist

Loading required package: zoo


Attaching package: ‘zoo’


The following objects are masked from ‘package:base’:

    as.Date, as.Date.numeric


Loading required package: dtw

Loading required package: proxy


Attaching package: ‘proxy’


The following objects are masked from ‘package:stats’:

    as.dist, dist


The following object is masked from ‘package:base’:

    as.matrix


Loaded dtw v1.22-3. See ?dtw for help, citation("dtw") for use in publication.


Loading required package: evaluate

Loading required package: data.table

Warning message:
“package ‘data.table’ was built under R version 4.3.2”

Attaching package: ‘data.table’


The following objects are masked from ‘package:zoo’:

    yearmon, yearqtr


Loading required package: plyr

Loading required package: dplyr

Warning message:
“package ‘dplyr’ was built under R version 4.3.2”

Attaching package: ‘dplyr’


The following objects are masked from ‘package:plyr’:

    arrange, count, desc, failwith, id, mutate, rename, summarise,
    summarize


The following objects are masked from ‘package:data.table’:

    between, first, last


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

[[1]]
[1] TRUE

[[2]]
[1] TRUE

[[3]]
[1] TRUE

[[4]]
[1] FALSE

[[5]]
[1] TRUE

[[6]]
[1] TRUE

[[7]]
[1] TRUE

[[8]]
[1] TRUE

[[9]]
[1] TRUE

[[10]]
[1] TRUE

[[11]]
[1] TRUE

[[12]]
[1] TRUE

[[13]]
[1] TRUE

[[14]]
[1] TRUE

[[15]]
[1] TRUE

[[16]]
[1] TRUE

[[17]]
[1] TRUE

[[18]]
[1] TRUE

[[19]]
[1] TRUE

In [2]:
# SET PARAMS
windowsize=2
num_trees = 200


print("Reading in data")
destfile <- paste("imputed_shifted_block.csv")
augmented_panel_data <- as.data.frame(fread(file = destfile))
# Time variant
#hhs_X_w_clusters_fpath = "../benchmark_tcv_kmeans_code/hhs_X_w_clusters.csv"
#hhs_X_w_clusters = as.data.frame(fread(file = hhs_X_w_clusters_fpath))

start_day = min(augmented_panel_data$days_from_start)
end_day = max(augmented_panel_data$days_from_start)

cutoff_list <- start_day:end_day

[1] "Reading in data"

In [3]:
augmented_panel_data

        date       county        state    cases deaths datetime
1       2020-04-17 Autauga       Alabama  20    2      2020-04-17
2       2020-04-18 Autauga       Alabama  19    2      2020-04-18
3       2020-04-19 Autauga       Alabama  21    2      2020-04-19
4       2020-04-20 Autauga       Alabama  22    1      2020-04-20
5       2020-04-21 Autauga       Alabama  23    1      2020-04-21
6       2020-04-22 Autauga       Alabama  25    2      2020-04-22
7       2020-04-23 Autauga       Alabama  23    2      2020-04-23
8       2020-04-24 Autauga       Alabama  26    2      2020-04-24
9       2020-04-25 Autauga       Alabama  25    2      2020-04-25
10      2020-04-26 Autauga       Alabama  25    2      2020-04-26
11      2020-04-27 Autauga       Alabama  27    3      2020-04-27
12      2020-04-28 Autauga       Alabama  28    4      2020-04-28
13      2020-04-29 Autauga       Alabama  31    4      2020-04-29
14      2020-04-30 Autauga       Alabama  30    4      2020-04-30
15      2020-05-01 Autauga       Alabama  25    3      2020-05-01
16      2020-05-02 Autauga       Alabama  28    3      2020-05-02
17      2020-05-03 Autauga       Alabama  29    3      2020-05-03
18      2020-05-04 Autauga       Alabama  34    3      2020-05-04
19      2020-05-05 Autauga       Alabama  34    3      2020-05-05
20      2020-05-06 Autauga       Alabama  35    3      2020-05-06
21      2020-05-07 Autauga       Alabama  36    3      2020-05-07
22      2020-05-08 Autauga       Alabama  42    4      2020-05-08
23      2020-05-09 Autauga       Alabama  42    4      2020-05-09
24      2020-05-10 Autauga       Alabama  49    4      2020-05-10
25      2020-05-11 Autauga       Alabama  57    4      2020-05-11
26      2020-05-12 Autauga       Alabama  63    4      2020-05-12
27      2020-05-13 Autauga       Alabama  63    4      2020-05-13
28      2020-05-14 Autauga       Alabama  72    4      2020-05-14
29      2020-05-15 Autauga       Alabama  70    4      2020-05-15
30      2020-05-16 Autauga       Alabama  74    4      2020-05-16
⋮       ⋮          ⋮             ⋮        ⋮     ⋮      ⋮
2646402 2023-02-22 New York City New York 26840 45043  2023-02-22
2646403 2023-02-23 New York City New York 27116 45074  2023-02-23
2646404 2023-02-24 New York City New York 25659 45076  2023-02-24
2646405 2023-02-25 New York City New York 23467 45076  2023-02-25
2646406 2023-02-26 New York City New York 23467 45076  2023-02-26
2646407 2023-02-27 New York City New York 25778 44968  2023-02-27
2646408 2023-02-28 New York City New York 21981 44976  2023-02-28
2646409 2023-03-01 New York City New York 21640 44988  2023-03-01
2646410 2023-03-02 New York City New York 21955 45013  2023-03-02
2646411 2023-03-03 New York City New York 20862 45014  2023-03-03
2646412 2023-03-04 New York City New York 19306 45014  2023-03-04
2646413 2023-03-05 New York City New York 19306 45014  2023-03-05
2646414 2023-03-06 New York City New York 21157 45018  2023-03-06
2646415 2023-03-07 New York City New York 18089 45022  2023-03-07
2646416 2023-03-08 New York City New York 17637 45032  2023-03-08
2646417 2023-03-09 New York City New York 17220 45023  2023-03-09
2646418 2023-03-10 New York City New York 16384 44996  2023-03-10
2646419 2023-03-11 New York City New York 15281 44996  2023-03-11
2646420 2023-03-12 New York City New York 15281 44996  2023-03-12
2646421 2023-03-13 New York City New York 16877 44998  2023-03-13
2646422 2023-03-14 New York City New York 17166 45004  2023-03-14
2646423 2023-03-15 New York City New York 13140 45017  2023-03-15
2646424 2023-03-16 New York City New York 13795 45002  2023-03-16
2646425 2023-03-17 New York City New York 12892 45008  2023-03-17
2646426 2023-03-18 New York City New York 11968 45008  2023-03-18
2646427 2023-03-19 New York City New York 11968 45008  2023-03-19
2646428 2023-03-20 New York City New York 12294 45008  2023-03-20
2646429 2023-03-21 New York City New York 11154 45005  2023-03-21
2646430 2023-03-22 New York City New York 11013 45155  2023-03-22
2646431 2023-03-23 New York City New York 11200 45123  2023-03-23
        days_from_start rolled_cases LAT      LON       ⋯ Variant % XBB
1        87             20.71429     32.53224 -86.64644 ⋯ 0
2        88             20.71429     32.53224 -86.64644 ⋯ 0
3        89             21.00000     32.53224 -86.64644 ⋯ 0
4        90             21.42857     32.53224 -86.64644 ⋯ 0
5        91             21.42857     32.53224 -86.64644 ⋯ 0
6        92             21.57143     32.53224 -86.64644 ⋯ 0
7        93             21.85714     32.53224 -86.64644 ⋯ 0
8        94             22.71429     32.53224 -86.64644 ⋯ 0
9        95             23.57143     32.53224 -86.64644 ⋯ 0
10       96             24.14286     32.53224 -86.64644 ⋯ 0
11       97             24.85714     32.53224 -86.64644 ⋯ 0
12       98             25.57143     32.53224 -86.64644 ⋯ 0
13       99             26.42857     32.53224 -86.64644 ⋯ 0
14      100             27.42857     32.53224 -86.64644 ⋯ 0
15      101             27.28571     32.53224 -86.64644 ⋯ 0
16      102             27.71429     32.53224 -86.64644 ⋯ 0
17      103             28.28571     32.53224 -86.64644 ⋯ 0
18      104             29.28571     32.53224 -86.64644 ⋯ 0
19      105             30.14286     32.53224 -86.64644 ⋯ 0
20      106             30.71429     32.53224 -86.64644 ⋯ 0
21      107             31.57143     32.53224 -86.64644 ⋯ 0
22      108             34.00000     32.53224 -86.64644 ⋯ 0
23      109             36.00000     32.53224 -86.64644 ⋯ 0
24      110             38.85714     32.53224 -86.64644 ⋯ 0
25      111             42.14286     32.53224 -86.64644 ⋯ 0
26      112             46.28571     32.53224 -86.64644 ⋯ 0
27      113             50.28571     32.53224 -86.64644 ⋯ 0
28      114             55.42857     32.53224 -86.64644 ⋯ 0
29      115             59.42857     32.53224 -86.64644 ⋯ 0
30      116             64.00000     32.53224 -86.64644 ⋯ 0
⋮       ⋮               ⋮            ⋮        ⋮         ⋱ ⋮
2646402 1128            30569.29     40.65857 -73.95064 ⋯ 0.01082159
2646403 1129            29730.86     40.65857 -73.95064 ⋯ 0.01082159
2646404 1130            28893.14     40.65857 -73.95064 ⋯ 0.01082159
2646405 1131            27742.29     40.65857 -73.95064 ⋯ 0.01474782
2646406 1132            26591.43     40.65857 -73.95064 ⋯ 0.01474782
2646407 1133            25770.71     40.65857 -73.95064 ⋯ 0.01474782
2646408 1134            24901.14     40.65857 -73.95064 ⋯ 0.01474782
2646409 1135            24158.29     40.65857 -73.95064 ⋯ 0.01474782
2646410 1136            23421.00     40.65857 -73.95064 ⋯ 0.01474782
2646411 1137            22735.71     40.65857 -73.95064 ⋯ 0.01474782
2646412 1138            22141.29     40.65857 -73.95064 ⋯ 0.01176315
2646413 1139            21546.86     40.65857 -73.95064 ⋯ 0.01176315
2646414 1140            20886.71     40.65857 -73.95064 ⋯ 0.01176315
2646415 1141            20330.71     40.65857 -73.95064 ⋯ 0.01176315
2646416 1142            19758.86     40.65857 -73.95064 ⋯ 0.01176315
2646417 1143            19082.43     40.65857 -73.95064 ⋯ 0.01176315
2646418 1144            18442.71     40.65857 -73.95064 ⋯ 0.01176315
2646419 1145            17867.71     40.65857 -73.95064 ⋯ 0.01531821
2646420 1146            17292.71     40.65857 -73.95064 ⋯ 0.01531821
2646421 1147            16681.29     40.65857 -73.95064 ⋯ 0.01531821
2646422 1148            16549.43     40.65857 -73.95064 ⋯ 0.01531821
2646423 1149            15907.00     40.65857 -73.95064 ⋯ 0.01531821
2646424 1150            15417.71     40.65857 -73.95064 ⋯ 0.01531821
2646425 1151            14918.86     40.65857 -73.95064 ⋯ 0.01531821
2646426 1152            14445.57     40.65857 -73.95064 ⋯ 0.01241962
2646427 1153            13972.29     40.65857 -73.95064 ⋯ 0.01241962
2646428 1154            13317.57     40.65857 -73.95064 ⋯ 0.01241962
2646429 1155            12458.71     40.65857 -73.95064 ⋯ 0.01241962
2646430 1156            12154.86     40.65857 -73.95064 ⋯ 0.01241962
2646431 1157            11784.14     40.65857 -73.95064 ⋯ 0.01241962
        Variant % XBB.1.16 Variant % XBB.1.5 Variant % XBB.1.5.1
1       0                  0                 0
2       0                  0                 0
3       0                  0                 0
4       0                  0                 0
5       0                  0                 0
6       0                  0                 0
7       0                  0                 0
8       0                  0                 0
9       0                  0                 0
10      0                  0                 0
11      0                  0                 0
12      0                  0                 0
13      0                  0                 0
14      0                  0                 0
15      0                  0                 0
16      0                  0                 0
17      0                  0                 0
18      0                  0                 0
19      0                  0                 0
20      0                  0                 0
21      0                  0                 0
22      0                  0                 0
23      0                  0                 0
24      0                  0                 0
25      0                  0                 0
26      0                  0                 0
27      0                  0                 0
28      0                  0                 0
29      0                  0                 0
30      0                  0                 0
⋮       ⋮                  ⋮                 ⋮
2646402 0.0000000000       0.8659418         0.01710694
2646403 0.0000000000       0.8659418         0.01710694
2646404 0.0000000000       0.8659418         0.01710694
2646405 0.0000000000       0.9010727         0.01797043
2646406 0.0000000000       0.9010727         0.01797043
2646407 0.0000000000       0.9010727         0.01797043
2646408 0.0000000000       0.9010727         0.01797043
2646409 0.0000000000       0.9010727         0.01797043
2646410 0.0000000000       0.9010727         0.01797043
2646411 0.0000000000       0.9010727         0.01797043
2646412 0.0016448150       0.9062040         0.01199684
2646413 0.0016448150       0.9062040         0.01199684
2646414 0.0016448150       0.9062040         0.01199684
2646415 0.0016448150       0.9062040         0.01199684
2646416 0.0016448150       0.9062040         0.01199684
2646417 0.0016448150       0.9062040         0.01199684
2646418 0.0016448150       0.9062040         0.01199684
2646419 0.0009603487       0.8831368         0.02679503
2646420 0.0009603487       0.8831368         0.02679503
2646421 0.0009603487       0.8831368         0.02679503
2646422 0.0009603487       0.8831368         0.02679503
2646423 0.0009603487       0.8831368         0.02679503
2646424 0.0009603487       0.8831368         0.02679503
2646425 0.0009603487       0.8831368         0.02679503
2646426 0.0058001898       0.8691683         0.03012894
2646427 0.0058001898       0.8691683         0.03012894
2646428 0.0058001898       0.8691683         0.03012894
2646429 0.0058001898       0.8691683         0.03012894
2646430 0.0058001898       0.8691683         0.03012894
2646431 0.0058001898       0.8691683         0.03012894
        Variant % XBB.1.9.1 Variant % XBB.1.9.2 Variant % XBB.2.3 fips
1       0                   0                   0                 1001
2       0                   0                   0                 1001
3       0                   0                   0                 1001
4       0                   0                   0                 1001
5       0                   0                   0                 1001
6       0                   0                   0                 1001
7       0                   0                   0                 1001
8       0                   0                   0                 1001
9       0                   0                   0                 1001
10      0                   0                   0                 1001
11      0                   0                   0                 1001
12      0                   0                   0                 1001
13      0                   0                   0                 1001
14      0                   0                   0                 1001
15      0                   0                   0                 1001
16      0                   0                   0                 1001
17      0                   0                   0                 1001
18      0                   0                   0                 1001
19      0                   0                   0                 1001
20      0                   0                   0                 1001
21      0                   0                   0                 1001
22      0                   0                   0                 1001
23      0                   0                   0                 1001
24      0                   0                   0                 1001
25      0                   0                   0                 1001
26      0                   0                   0                 1001
27      0                   0                   0                 1001
28      0                   0                   0                 1001
29      0                   0                   0                 1001
30      0                   0                   0                 1001
⋮       ⋮                   ⋮                   ⋮                 ⋮
2646402 0.001935909         0.001024818         0.000000000       99999
2646403 0.001935909         0.001024818         0.000000000       99999
2646404 0.001935909         0.001024818         0.000000000       99999
2646405 0.008500152         0.000000000         0.000000000       99999
2646406 0.008500152         0.000000000         0.000000000       99999
2646407 0.008500152         0.000000000         0.000000000       99999
2646408 0.008500152         0.000000000         0.000000000       99999
2646409 0.008500152         0.000000000         0.000000000       99999
2646410 0.008500152         0.000000000         0.000000000       99999
2646411 0.008500152         0.000000000         0.000000000       99999
2646412 0.007724691         0.003968848         0.000372916       99999
2646413 0.007724691         0.003968848         0.000372916       99999
2646414 0.007724691         0.003968848         0.000372916       99999
2646415 0.007724691         0.003968848         0.000372916       99999
2646416 0.007724691         0.003968848         0.000372916       99999
2646417 0.007724691         0.003968848         0.000372916       99999
2646418 0.007724691         0.003968848         0.000372916       99999
2646419 0.014619014         0.004801743         0.003142194       99999
2646420 0.014619014         0.004801743         0.003142194       99999
2646421 0.014619014         0.004801743         0.003142194       99999
2646422 0.014619014         0.004801743         0.003142194       99999
2646423 0.014619014         0.004801743         0.003142194       99999
2646424 0.014619014         0.004801743         0.003142194       99999
2646425 0.014619014         0.004801743         0.003142194       99999
2646426 0.017495075         0.009923106         0.004536750       99999
2646427 0.017495075         0.009923106         0.004536750       99999
2646428 0.017495075         0.009923106         0.004536750       99999
2646429 0.017495075         0.009923106         0.004536750       99999
2646430 0.017495075         0.009923106         0.004536750       99999
2646431 0.017495075         0.009923106         0.004536750       99999
        log_rolled_cases log_shifted_rolled_cases
1       3.030824          0.020906685
2       3.030824          0.000000000
3       3.044522          0.013698844
4       3.064725          0.020202707
5       3.064725          0.000000000
6       3.071370          0.006644543
7       3.084528          0.013158085
8       3.122994          0.038466281
9       3.160035          0.037041272
10      3.183989          0.023953241
11      3.213145          0.029156584
12      3.241476          0.028330507
13      3.274446          0.032970019
14      3.311585          0.037139547
15      3.306363         -0.005221944
16      3.321948          0.015584731
17      3.342357          0.020408872
18      3.377100          0.034742948
19      3.405948          0.028848154
20      3.424728          0.018779895
21      3.452253          0.027524673
22      3.526361          0.074107972
23      3.583519          0.057158414
24      3.659892          0.076372979
25      3.741065          0.081173290
26      3.834833          0.093768159
27      3.917721          0.082887660
28      4.015095          0.097374164
29      4.084775          0.069679921
30      4.158883          0.074107972
⋮       ⋮                ⋮
2646402 10.327751        -0.028966307
2646403 10.299941        -0.027810303
2646404 10.271360        -0.028581172
2646405 10.230713        -0.040646486
2646406 10.188344        -0.042368880
2646407 10.156994        -0.031350188
2646408 10.122669        -0.034325042
2646409 10.092383        -0.030286285
2646410 10.061388        -0.030994359
2646411 10.031692        -0.029696051
2646412 10.005199        -0.026493007
2646413  9.977985        -0.027214032
2646414  9.946869        -0.031116689
2646415  9.919888        -0.026980515
2646416  9.891357        -0.028530908
2646417  9.856523        -0.034833912
2646418  9.822425        -0.034098539
2646419  9.790751        -0.031673990
2646420  9.758041        -0.032710140
2646421  9.722043        -0.035997798
2646422  9.714107        -0.007935901
2646423  9.674515        -0.039592310
2646424  9.643272        -0.031242137
2646425  9.610381        -0.032891134
2646426  9.578143        -0.032238101
2646427  9.544831        -0.033312116
2646428  9.496840        -0.047991452
2646429  9.430176        -0.066664003
2646430  9.405484        -0.024691466
2646431  9.374510        -0.030974053

In [9]:
cutoff=200

print(paste0("Computing LLF for ", toString(cutoff)))
# START TRY

start_time <- Sys.time()
# Given my current cutoff, which block numbers should I use?
fname <- paste("llf_",toString(cutoff),".csv",sep="")        
# SLICE THE DATA ACCORDINGLY
early_data <- augmented_panel_data[augmented_panel_data$days_from_start <= cutoff, ]
early_data <- early_data[early_data$days_from_start >= max(cutoff-90, 0), ]

cutoff_parity <- cutoff %% 2

# Filter the dataframe based on the parity of t
early_data <- early_data %>%
  filter((days_from_start %% 2) == cutoff_parity)


case_number_columns <- c("fips","date", "datetime","county","state","days_from_start", "shifted_log_rolled_cases","log_rolled_cases")
early_data_case_numbers <- early_data[, names(early_data) %in% case_number_columns]
# Format data to be fed to ll_regression_forest
#WYX <- merge(early_data_case_numbers, X_time_invariant, by="fips", all.x=TRUE)
XY <- early_data
XY <- XY[order(XY$fips, XY$days_from_start),]

Y <- XY$log_shifted_rolled_cases
X <- XY[, !names(XY) %in% case_number_columns]
X <- X %>%
  select_if(is.numeric)

[1] "Computing LLF for 200"

In [8]:
XY

      date       county        state    cases deaths datetime   days_from_start
1     2020-05-10 Autauga       Alabama   49    4     2020-05-10 110
2     2020-05-12 Autauga       Alabama   63    4     2020-05-12 112
3     2020-05-14 Autauga       Alabama   72    4     2020-05-14 114
4     2020-05-16 Autauga       Alabama   74    4     2020-05-16 116
5     2020-05-18 Autauga       Alabama   83    4     2020-05-18 118
6     2020-05-20 Autauga       Alabama   96    3     2020-05-20 120
7     2020-05-22 Autauga       Alabama  107    3     2020-05-22 122
8     2020-05-24 Autauga       Alabama  114    3     2020-05-24 124
9     2020-05-26 Autauga       Alabama  136    3     2020-05-26 126
10    2020-05-28 Autauga       Alabama  147    3     2020-05-28 128
11    2020-05-30 Autauga       Alabama  149    4     2020-05-30 130
12    2020-06-01 Autauga       Alabama  160    5     2020-06-01 132
13    2020-06-03 Autauga       Alabama  149    5     2020-06-03 134
14    2020-06-05 Autauga       Alabama  145    5     2020-06-05 136
15    2020-06-07 Autauga       Alabama  156    5     2020-06-07 138
16    2020-06-09 Autauga       Alabama  163    5     2020-06-09 140
17    2020-06-11 Autauga       Alabama  180    6     2020-06-11 142
18    2020-06-13 Autauga       Alabama  186    6     2020-06-13 144
19    2020-06-15 Autauga       Alabama  209    6     2020-06-15 146
20    2020-06-17 Autauga       Alabama  186    7     2020-06-17 148
21    2020-06-19 Autauga       Alabama  206    8     2020-06-19 150
22    2020-06-21 Autauga       Alabama  218    9     2020-06-21 152
23    2020-06-23 Autauga       Alabama  219    9     2020-06-23 154
24    2020-06-25 Autauga       Alabama  239   11     2020-06-25 156
25    2020-06-27 Autauga       Alabama  249   12     2020-06-27 158
26    2020-06-29 Autauga       Alabama  261   12     2020-06-29 160
27    2020-07-01 Autauga       Alabama  270   12     2020-07-01 162
28    2020-07-03 Autauga       Alabama  252   13     2020-07-03 164
29    2020-07-05 Autauga       Alabama  280   13     2020-07-05 166
30    2020-07-07 Autauga       Alabama  276   13     2020-07-07 168
⋮     ⋮          ⋮             ⋮        ⋮     ⋮      ⋮          ⋮
74797 2020-06-11 New York City New York 13879 21468  2020-06-11 142
74798 2020-06-13 New York City New York 12944 21551  2020-06-13 144
74799 2020-06-15 New York City New York 12080 21600  2020-06-15 146
74800 2020-06-17 New York City New York 11575 21645  2020-06-17 148
74801 2020-06-19 New York City New York 10567 21710  2020-06-19 150
74802 2020-06-21 New York City New York  9650 21753  2020-06-21 152
74803 2020-06-23 New York City New York  9253 21817  2020-06-23 154
74804 2020-06-25 New York City New York  8741 21856  2020-06-25 156
74805 2020-06-27 New York City New York  8429 21913  2020-06-27 158
74806 2020-06-29 New York City New York  7942 21941  2020-06-29 160
74807 2020-07-01 New York City New York  7674 22574  2020-07-01 162
74808 2020-07-03 New York City New York  7757 22610  2020-07-03 164
74809 2020-07-05 New York City New York  7395 22661  2020-07-05 166
74810 2020-07-07 New York City New York  7145 22690  2020-07-07 168
74811 2020-07-09 New York City New York  7037 22719  2020-07-09 170
74812 2020-07-11 New York City New York  6961 22750  2020-07-11 172
74813 2020-07-13 New York City New York  6788 22795  2020-07-13 174
74814 2020-07-15 New York City New York  6859 22825  2020-07-15 176
74815 2020-07-17 New York City New York  6985 22848  2020-07-17 178
74816 2020-07-19 New York City New York  6947 22872  2020-07-19 180
74817 2020-07-21 New York City New York  7109 22895  2020-07-21 182
74818 2020-07-23 New York City New York  7374 22934  2020-07-23 184
74819 2020-07-25 New York City New York  7192 22947  2020-07-25 186
74820 2020-07-27 New York City New York  7103 22970  2020-07-27 188
74821 2020-07-29 New York City New York  7081 22982  2020-07-29 190
74822 2020-07-31 New York City New York  7111 23002  2020-07-31 192
74823 2020-08-02 New York City New York  7028 23012  2020-08-02 194
74824 2020-08-04 New York City New York  6987 23027  2020-08-04 196
74825 2020-08-06 New York City New York  6938 23563  2020-08-06 198
74826 2020-08-08 New York City New York  6857 23575  2020-08-08 200
      rolled_cases LAT      LON       ⋯ Variant % XBB Variant % XBB.1.16
1      38.85714    32.53224 -86.64644 ⋯ 0             0
2      46.28571    32.53224 -86.64644 ⋯ 0             0
3      55.42857    32.53224 -86.64644 ⋯ 0             0
4      64.00000    32.53224 -86.64644 ⋯ 0             0
5      71.14286    32.53224 -86.64644 ⋯ 0             0
6      79.42857    32.53224 -86.64644 ⋯ 0             0
7      89.28571    32.53224 -86.64644 ⋯ 0             0
8     100.71429    32.53224 -86.64644 ⋯ 0             0
9     112.85714    32.53224 -86.64644 ⋯ 0             0
10    125.14286    32.53224 -86.64644 ⋯ 0             0
11    136.57143    32.53224 -86.64644 ⋯ 0             0
12    147.85714    32.53224 -86.64644 ⋯ 0             0
13    152.14286    32.53224 -86.64644 ⋯ 0             0
14    151.57143    32.53224 -86.64644 ⋯ 0             0
15    153.14286    32.53224 -86.64644 ⋯ 0             0
16    154.57143    32.53224 -86.64644 ⋯ 0             0
17    161.85714    32.53224 -86.64644 ⋯ 0             0
18    171.00000    32.53224 -86.64644 ⋯ 0             0
19    184.71429    32.53224 -86.64644 ⋯ 0             0
20    193.14286    32.53224 -86.64644 ⋯ 0             0
21    200.85714    32.53224 -86.64644 ⋯ 0             0
22    207.28571    32.53224 -86.64644 ⋯ 0             0
23    211.00000    32.53224 -86.64644 ⋯ 0             0
24    221.57143    32.53224 -86.64644 ⋯ 0             0
25    231.57143    32.53224 -86.64644 ⋯ 0             0
26    240.85714    32.53224 -86.64644 ⋯ 0             0
27    253.14286    32.53224 -86.64644 ⋯ 0             0
28    257.71429    32.53224 -86.64644 ⋯ 0             0
29    265.14286    32.53224 -86.64644 ⋯ 0             0
30    266.28571    32.53224 -86.64644 ⋯ 0             0
⋮     ⋮            ⋮        ⋮         ⋱ ⋮             ⋮
74797 15022.571    40.65857 -73.95064 ⋯ 0             0
74798 14062.143    40.65857 -73.95064 ⋯ 0             0
74799 13313.857    40.65857 -73.95064 ⋯ 0             0
74800 12573.714    40.65857 -73.95064 ⋯ 0             0
74801 11819.429    40.65857 -73.95064 ⋯ 0             0
74802 10982.857    40.65857 -73.95064 ⋯ 0             0
74803 10240.286    40.65857 -73.95064 ⋯ 0             0
74804  9501.429    40.65857 -73.95064 ⋯ 0             0
74805  8991.571    40.65857 -73.95064 ⋯ 0             0
74806  8576.857    40.65857 -73.95064 ⋯ 0             0
74807  8183.857    40.65857 -73.95064 ⋯ 0             0
74808  7916.286    40.65857 -73.95064 ⋯ 0             0
74809  7694.429    40.65857 -73.95064 ⋯ 0             0
74810  7513.857    40.65857 -73.95064 ⋯ 0             0
74811  7339.857    40.65857 -73.95064 ⋯ 0             0
74812  7137.143    40.65857 -73.95064 ⋯ 0             0
74813  7002.857    40.65857 -73.95064 ⋯ 0             0
74814  6919.714    40.65857 -73.95064 ⋯ 0             0
74815  6896.714    40.65857 -73.95064 ⋯ 0             0
74816  6905.857    40.65857 -73.95064 ⋯ 0             0
74817  6966.143    40.65857 -73.95064 ⋯ 0             0
74818  7086.857    40.65857 -73.95064 ⋯ 0             0
74819  7161.429    40.65857 -73.95064 ⋯ 0             0
74820  7204.143    40.65857 -73.95064 ⋯ 0             0
74821  7167.429    40.65857 -73.95064 ⋯ 0             0
74822  7100.143    40.65857 -73.95064 ⋯ 0             0
74823  7079.429    40.65857 -73.95064 ⋯ 0             0
74824  7043.714    40.65857 -73.95064 ⋯ 0             0
74825  7004.429    40.65857 -73.95064 ⋯ 0             0
74826  6943.571    40.65857 -73.95064 ⋯ 0             0
      Variant % XBB.1.5 Variant % XBB.1.5.1 Variant % XBB.1.9.1
1     0                 0                   0
2     0                 0                   0
3     0                 0                   0
4     0                 0                   0
5     0                 0                   0
6     0                 0                   0
7     0                 0                   0
8     0                 0                   0
9     0                 0                   0
10    0                 0                   0
11    0                 0                   0
12    0                 0                   0
13    0                 0                   0
14    0                 0                   0
15    0                 0                   0
16    0                 0                   0
17    0                 0                   0
18    0                 0                   0
19    0                 0                   0
20    0                 0                   0
21    0                 0                   0
22    0                 0                   0
23    0                 0                   0
24    0                 0                   0
25    0                 0                   0
26    0                 0                   0
27    0                 0                   0
28    0                 0                   0
29    0                 0                   0
30    0                 0                   0
⋮     ⋮                 ⋮                   ⋮
74797 0                 0                   0
74798 0                 0                   0
74799 0                 0                   0
74800 0                 0                   0
74801 0                 0                   0
74802 0                 0                   0
74803 0                 0                   0
74804 0                 0                   0
74805 0                 0                   0
74806 0                 0                   0
74807 0                 0                   0
74808 0                 0                   0
74809 0                 0                   0
74810 0                 0                   0
74811 0                 0                   0
74812 0                 0                   0
74813 0                 0                   0
74814 0                 0                   0
74815 0                 0                   0
74816 0                 0                   0
74817 0                 0                   0
74818 0                 0                   0
74819 0                 0                   0
74820 0                 0                   0
74821 0                 0                   0
74822 0                 0                   0
74823 0                 0                   0
74824 0                 0                   0
74825 0                 0                   0
74826 0                 0                   0
      Variant % XBB.1.9.2 Variant % XBB.2.3 fips  log_rolled_cases
1     0                   0                 1001  3.659892
2     0                   0                 1001  3.834833
3     0                   0                 1001  4.015095
4     0                   0                 1001  4.158883
5     0                   0                 1001  4.264690
6     0                   0                 1001  4.374858
7     0                   0                 1001  4.491842
8     0                   0                 1001  4.612288
9     0                   0                 1001  4.726123
10    0                   0                 1001  4.829456
11    0                   0                 1001  4.916848
12    0                   0                 1001  4.996247
13    0                   0                 1001  5.024820
14    0                   0                 1001  5.021057
15    0                   0                 1001  5.031371
16    0                   0                 1001  5.040656
17    0                   0                 1001  5.086714
18    0                   0                 1001  5.141664
19    0                   0                 1001  5.218810
20    0                   0                 1001  5.263430
21    0                   0                 1001  5.302594
22    0                   0                 1001  5.334098
23    0                   0                 1001  5.351858
24    0                   0                 1001  5.400745
25    0                   0                 1001  5.444888
26    0                   0                 1001  5.484204
27    0                   0                 1001  5.533954
28    0                   0                 1001  5.551852
29    0                   0                 1001  5.580269
30    0                   0                 1001  5.584570
⋮     ⋮                   ⋮                 ⋮     ⋮
74797 0                   0                 99999 9.617309
74798 0                   0                 99999 9.551242
74799 0                   0                 99999 9.496561
74800 0                   0                 99999 9.439364
74801 0                   0                 99999 9.377500
74802 0                   0                 99999 9.304091
74803 0                   0                 99999 9.234085
74804 0                   0                 99999 9.159197
74805 0                   0                 99999 9.104043
74806 0                   0                 99999 9.056823
74807 0                   0                 99999 9.009919
74808 0                   0                 99999 8.976677
74809 0                   0                 99999 8.948252
74810 0                   0                 99999 8.924504
74811 0                   0                 99999 8.901075
74812 0                   0                 99999 8.873068
74813 0                   0                 99999 8.854074
74814 0                   0                 99999 8.842130
74815 0                   0                 99999 8.838800
74816 0                   0                 99999 8.840125
74817 0                   0                 99999 8.848817
74818 0                   0                 99999 8.865997
74819 0                   0                 99999 8.876465
74820 0                   0                 99999 8.882412
74821 0                   0                 99999 8.877302
74822 0                   0                 99999 8.867870
74823 0                   0                 99999 8.864948
74824 0                   0                 99999 8.859891
74825 0                   0                 99999 8.854298
74826 0                   0                 99999 8.845572
      log_shifted_rolled_cases
1      0.076372979
2      0.093768159
3      0.097374164
4      0.074107972
5      0.053621091
6      0.061186830
7      0.061024702
8      0.059915653
9      0.062683702
10     0.050332449
11     0.038384243
12     0.039413969
13     0.009434032
14    -0.005639113
15     0.002802431
16     0.006490519
17     0.027742271
18     0.024525542
19     0.036224433
20     0.012653686
21     0.018665294
22     0.008304546
23     0.009523882
24     0.020189549
25     0.018680493
26     0.024010757
27     0.023409576
28     0.003331486
29     0.020136735
30     0.006458580
⋮     ⋮
74797 -0.0369108966
74798 -0.0286208753
74799 -0.0270564268
74800 -0.0291011461
74801 -0.0313282216
74802 -0.0372150812
74803 -0.0345514339
74804 -0.0367686849
74805 -0.0246999752
74806 -0.0240269589
74807 -0.0210726833
74808 -0.0146003686
74809 -0.0149633322
74810 -0.0109104712
74811 -0.0124948436
74812 -0.0144467822
74813 -0.0094816307
74814 -0.0050041806
74815 -0.0016557323
74816  0.0005172931
74817  0.0062331132
74818  0.0084617602
74819  0.0038373953
74820  0.0038942252
74821 -0.0040776195
74822 -0.0040961445
74823 -0.0004438437
74824 -0.0014186987
74825 -0.0034408724
74826 -0.0043522066

In [10]:
llf <- ll_regression_forest(X,Y, num.trees=num_trees)

In [11]:
llf

GRF forest object of type ll_regression_forest
Number of trees: 200
Number of training samples: 74826
Variable importance:
    1     2     3     4     5     6     7     8     9    10    11    12    13
0.063 0.035 0.004 0.006 0.010 0.000 0.000 0.001 0.000 0.001 0.001 0.000 0.000
   14    15    16    17    18    19    20    21    22    23    24    25    26
0.000 0.000 0.000 0.000 0.001 0.001 0.000 0.001 0.001 0.000 0.000 0.000 0.000
   27    28    29    30    31    32    33    34    35    36    37    38    39
0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000
   40    41    42    43    44    45    46    47    48    49    50    51    52
0.000 0.000 0.000 0.001 0.000 0.000 0.000 0.001 0.001 0.000 0.000 0.000 0.000
   53    54    55    56    57    58    59    60    61    62    63    64    65
0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000
   66    67    68    69    70    71    72    73    74    75    76    77    78
0.000 0.000 0.001 0.001 0.000 0.000 0.001 0.000 0.000 0.000 0.000 0.000 0.000
   79    80    81    82    83    84    85    86    87    88    89    90    91
0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000
   92    93    94    95    96    97    98    99   100   101   102   103   104
0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.001 0.001 0.000 0.000 0.002
  105   106   107   108   109   110   111   112   113   114   115   116   117
0.038 0.000 0.039 0.000 0.000 0.002 0.001 0.000 0.032 0.011 0.000 0.060 0.000
  118   119   120   121   122   123   124   125   126   127   128   129   130
0.014 0.000 0.000 0.000 0.000 0.002 0.000 0.000 0.000 0.000 0.000 0.029 0.002
  131   132   133   134   135   136   137   138   139   140   141   142   143
0.000 0.000 0.003 0.039 0.000 0.011 0.058 0.006 0.020 0.006 0.024 0.057 0.000
  144   145   146   147   148   149   150   151   152   153   154   155   156
0.051 0.000 0.000 0.001 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000
  157   158   159   160   161   162   163   164   165   166   167   168   169
0.000 0.000 0.000 0.000 0.002 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000
  170   171   172   173   174   175   176   177   178   179   180   181   182
0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000
  183   184   185   186   187   188   189   190   191   192   193   194   195
0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000
  196   197   198   199   200   201   202   203   204   205   206   207   208
0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.001
  209   210   211   212   213   214   215   216   217   218   219   220   221
0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.001 0.000 0.000 0.000
  222   223   224   225   226   227   228   229   230   231   232   233   234
0.002 0.001 0.000 0.000 0.000 0.000 0.000 0.000 0.001 0.000 0.000 0.000 0.000
  235   236   237   238   239   240   241   242   243   244   245   246   247
0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.027
  248   249   250   251   252   253   254   255   256   257   258   259   260
0.001 0.000 0.000 0.003 0.000 0.028 0.000 0.000 0.006 0.020 0.000 0.000 0.000
  261   262   263   264   265   266   267   268   269   270   271   272   273
0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.027 0.000 0.000 0.000
  274   275   276   277   278   279   280   281   282   283   284   285   286
0.000 0.000 0.000 0.000 0.000 0.002 0.000 0.000 0.000 0.000 0.000 0.009 0.000
  287   288   289   290   291   292   293   294   295   296   297   298   299
0.000 0.000 0.000 0.000 0.000 0.000 0.001 0.001 0.001 0.003 0.002 0.002 0.000
  300   301   302   303   304   305   306   307   308   309   310   311   312
0.000 0.005 0.001 0.000 0.001 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000
  313   314   315   316   317   318   319   320   321   322   323   324   325
0.002 0.000 0.000 0.001 0.000 0.000 0.000 0.000 0.000 0.000 0.004 0.000 0.000
  326   327   328   329   330   331   332   333   334   335   336   337   338
0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000
  339   340   341   342   343   344   345   346   347   348   349   350   351
0.000 0.003 0.000 0.002 0.000 0.000 0.004 0.000 0.000 0.000 0.000 0.000 0.000
  352   353   354   355   356   357   358   359   360   361   362   363   364
0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000
  365   366   367   368   369   370   371   372   373   374   375   376   377
0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.007 0.001 0.000 0.000 0.000
  378   379   380   381   382   383   384   385   386   387   388   389   390
0.001 0.001 0.000 0.000 0.001 0.000 0.000 0.000 0.000 0.000 0.000 0.002 0.000
  391   392   393   394   395   396   397   398   399   400   401   402   403
0.000 0.017 0.000 0.000 0.000 0.000 0.000 0.001 0.000 0.000 0.000 0.001 0.000
  404   405   406   407   408   409   410   411   412   413   414   415   416
0.001 0.000 0.000 0.000 0.000 0.000 0.000 0.001 0.033 0.000 0.000 0.013 0.000
  417   418   419   420   421   422   423   424   425   426   427   428   429
0.000 0.000 0.000 0.002 0.000 0.000 0.000 0.000 0.000 0.005 0.005 0.007 0.000
  430   431   432   433   434   435   436   437   438   439   440   441   442
0.001 0.001 0.000 0.000 0.000 0.000 0.001 0.000 0.000 0.000 0.000 0.000 0.000
  443   444   445   446   447   448   449   450   451   452   453   454   455
0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000 0.000
  456   457   458   459   460   461   462   463   464   465   466   467   468
0.000 0.000 0.000 0.000 0.000 0.000 0.001 0.000 0.001 0.000 0.000 0.000 0.000
  469   470   471   472   473
0.000 0.000 0.000 0.000 0.074