In [15]:
import numpy as np
import pandas as pd
import polars as pl

pd.set_option('display.max_columns', None)

### Read Data used for TLGRF

In [16]:
augmented_df_pd = pd.read_csv("../../data/augmented_us-counties-states_latest_variants.csv")

In [17]:
augmented_df_pd.head()

,fips,date,county,state,cases,deaths,datetime,days_from_start,rolled_cases,LAT,LON,AREA_SQMI,E_TOTPOP,E_HU,E_HH,E_POV,E_UNEMP,E_PCI,E_NOHSDP,E_AGE65,E_AGE17,E_DISABL,E_SNGPNT,E_MINRTY,E_LIMENG,E_MUNIT,E_MOBILE,E_CROWD,E_NOVEH,E_GROUPQ,EP_POV,MP_POV,EP_UNEMP,MP_UNEMP,EP_PCI,MP_PCI,EP_NOHSDP,MP_NOHSDP,EP_AGE65,MP_AGE65,EP_AGE17,MP_AGE17,EP_DISABL,MP_DISABL,EP_SNGPNT,MP_SNGPNT,EP_MINRTY,MP_MINRTY,EP_LIMENG,MP_LIMENG,EP_MUNIT,MP_MUNIT,EP_MOBILE,MP_MOBILE,EP_CROWD,MP_CROWD,EP_NOVEH,MP_NOVEH,EP_GROUPQ,MP_GROUPQ,EPL_POV,EPL_UNEMP,EPL_PCI,EPL_NOHSDP,SPL_THEME1,RPL_THEME1,EPL_AGE65,EPL_AGE17,EPL_DISABL,EPL_SNGPNT,SPL_THEME2,RPL_THEME2,EPL_MINRTY,EPL_LIMENG,SPL_THEME3,RPL_THEME3,EPL_MUNIT,EPL_MOBILE,EPL_CROWD,EPL_NOVEH,EPL_GROUPQ,SPL_THEME4,RPL_THEME4,SPL_THEMES,RPL_THEMES,F_POV,F_UNEMP,F_PCI,F_NOHSDP,F_THEME1,F_AGE65,F_AGE17,F_DISABL,F_SNGPNT,F_THEME2,F_MINRTY,F_LIMENG,F_THEME3,F_MUNIT,F_MOBILE,F_CROWD,F_NOVEH,F_GROUPQ,F_THEME4,F_TOTAL,E_UNINSUR,EP_UNINSUR,MP_UNINSUR,E_DAYPOP,State_FIPS_Code,State_of_emergency_issued,State_of_emergency_lifted,Date_closed_K-12_public_schools,Closed_day_cares,Reopen_day_cares,Date_banned_visitors_to_nursing_homes,Stay_at_home/_shelter_in_place,Stay_at_home_order'_issued_but_did_not_specifically_restrict_movement_of_the_general_public,End/relax_stay_at_home/shelter_in_place,Closed_other_non-essential_businesses,Closed_businesses_overnight,Began_to_reopen_businesses,Religious_gatherings_exempt_without_clear_social_distance_mandate*,Face_mask_mandate_in_public_spaces,Face_mask_mandate_x2,Face_mask_mandate_enforced_by_fines,Face_mask_mandate_enforced_by_criminal_charge/citation,No_legal_enforcement_of_face_mask_mandate,Face_mask_mandate_for_employees_of_public-facing_businesses,Ended_face_mask_mandate,Ended_face_mask_mandate_x2,Attempted_to_prevent_local_governments_from_implementing_face_mask_orders,Banned_local_mask_mandates,Liquor_stores_remained_open,Allowed_restaurants_to_sell_takeout_alcohol,Allowed_restaurants_to_deliver_alcohol,Firearm_sellers_remained_open,Cannabis_dispensaries_considered_essential_business,Closed_restaurants_except_take_out,Reopen_restaurants,Initially_reopen_restaurants_for_outdoor_dining_only,Closed_gyms,Reopened_gyms,Closed_movie_theaters,Reopened_movie_theaters,Closed_Bars,Reopen_bars,Reopened_hair_salons/barber_shops,Reopened_religious_gatherings,Reopened_other_non-essential_retail,Allowed_businesses_to_reopen_overnight,Began_to_reclose_bars,Closed_bars_(x2),Closed_movie_theaters_(x2),Closed_hair_salons/barber_shops_(x2),Closed_gyms_(x2),Closed_restaurants_(x2),Reopened_restaurants_(x2),Reopened_bars_(x2),Reopened_gyms_(x2),Reopened_hair_salons/barber_shops_(x2),Reopened_movie_theaters_(x2),Closed_bars_(x3),Closed_restaurants_(x3),Reopened_bars_(x3),Reopened_restaurants_(x3),Mandate_quarantine_for_those_entering_the_state_from_specific_settings,Mandate_quarantine_for_all_individuals_entering_the_state,Date_all_mandated_quarantines_ended,Date_vaccine_allocation_plan_last_updated,Vaccine_allocation_phase:_Frontline_Healthcare_Workers,Vaccine_allocation_phase:_Healthcare_Service_Workers,Vaccine_allocation_phase:_Home_Healthcare_Workers,Vaccine_allocation_phase:_Additional_Healthcare_Workers,Vaccine_allocation_phase:_Long-term_Care_Residents,Vaccine_allocation_phase:_EMS_Providers,Vaccine_allocation_phase:_Firefighters,Vaccine_allocation_phase:_Law_Enforcement_&_Public_Safety_Personnel,Vaccine_allocation_phase:_Correctional_Staff,Vaccine_allocation_phase:_People_who_are_Incarcerated,Vaccine_allocation_phase:_Residents_of_Homeless_Shelters,Vaccine_allocation_phase:_Adults_Ages_75+,Vaccine_allocation_phase:_Adults_Ages_65+,Vaccine_allocation_phase:_Adults_w/_High-Risk_Medical_Conditions,Vaccine_allocation_phase:_Pre-K-12_School_Employees,Vaccine_allocation_phase:_Higher_Education_Employees,Vaccine_allocation_phase:_Public_Transit_Workers,Vaccine_allocation_phase:_Food_Supply_Workers,Vaccine_allocation_phase:_Grocery_Store_Workers,Vaccine_allocation_phase:_Frontline_Essential_Workers,Vaccine_allocation_phase:_Additional_Essential_Workers,Vaccine_allocation_phase:_General_Public,Date_adults_ages_80+_became_eligible_for_COVID-19_vaccination,Date_adults_ages_75+_became_eligible_for_COVID-19_vaccination,Date_adults_ages_70+_became_eligible_for_COVID-19_vaccination,Date_adults_ages_65+_became_eligible_for_COVID-19_vaccination,Date_adults_ages_60+_became_eligible_for_COVID-19_vaccination,Date_adults_ages_55+_became_eligible_for_COVID-19_vaccination,Date_adults_ages_50+_became_eligible_for_COVID-19_vaccination,Date_adults_ages_45+_became_eligible_for_COVID-19_vaccination,Date_adults_ages_40+_became_eligible_for_COVID-19_vaccination,Date_adults_ages_30+_became_eligible_for_COVID-19_vaccination,Date_K-12_school_employees_became_eligible_for_COVID-19_vaccination,Date_grocery_store_workers_became_eligible_for_COVID-19_vaccination,Date_incarcerated_people_became_eligible_for_COVID-19_vaccination,Date_general_public_became_eligible_for_COVID-19_vaccination,Adults_ages_65+_prioritized_ahead_of_essential_workers,Prioritization_by_race/ethnicity,Proof_of_work_eligibility_requirement_for_vaccination,Proof_of_age_eligibility_requirement_for_vaccination,Proof_of_residency_requirement_for_vaccination,Penalty_for_failure_to_comply_with_vaccine_distribution_requirements,Expanded_scope_of_practice_of_certain_health_providers_to_administer_vaccines,First_overall_eviction_moratorium_start,First_overall_eviction_moratorium_end,Second_overall_eviction_moratorium_start,Second_overall_eviction_moratorium_end,Third_overall_eviction_moratorium_start,Third_overall_eviction_moratorium_end,First_eviction_initiation_ban_start,First_eviction_initiation_ban_end,Second_Eviction_Initiation_Ban_Start,Second_Eviction_Initiation_Ban_End,First_eviction_hearing_ban_start,First_eviction_hearing_ban_end,Second_Eviction_Hearing_Ban_Start,Second_Eviction_Hearing_Ban_End,First_eviction_enforcement_ban_start,First_eviction_enforcement_ban_end,Second_Eviction_Enforcement_Ban_Start,Second_Eviction_Enforcement_Ban_End,COVID-19_hardship_limitation_start,COVID-19_hardship_limitation_end,Second_COVID-19_hardship_limitation_start,Second_COVID-19_hardship_limitation_end,Non-payment_limitation_start,Non-payment_limitation_end,Second_non-payment_limitation_start,Second_non-payment_limitation_end,CARES_Act_pleading_start,CARES_Act_pleading_end,CDC_moratorium_start,CDC_moratorium_end,Late_Fee_Ban_Start,Late_Fee_Ban_End,Second_Late_Fee_Ban_Start,Second_Late_Fee_Ban_End,Utilities_shutoff_moratorium_start,Utilities_shutoff_moratorium_expiration,Second_utilities_shutoff_moratorium_start,Utilities_reconnection_start,Utilities_reconnection_end,SNAP_Waiver_-_Emergency_Allotments_to_Current_SNAP_Households,SNAP_Waiver_-_Pandemic_EBT_during_school_year_2019-2020,SNAP_Waiver_-_Pandemic_EBT_during_school_year_2020-2021,SNAP_Waiver_-_Pandemic_EBT_during_summer_2021,SNAP_Waiver_-_Temporary_Suspension_of_Claims_Collection,2020_Q1_SNAP_ABAWD_Time_Limit_Waiver,Modify_Medicaid_requirements_with_1135_waivers_(date_of_CMS_approval),Reopened_ACA_enrollment_using_a_special_enrollment_period,State_previously_allowed_audio-only_telehealth,Allow_audio-only_telehealth,Allow/expand_Medicaid_telehealth_coverage,State_had_CHIP_premium_non-payment_lock-out_period_as_of_January_2019,Suspend_CHIP_premium_non-payment_lock-outs,Report_COVID-19_testing_by_race/ethnicity,Report_COVID-19_cases_by_race/ethnicity,Report_COVID-19_hospitalizations_by_race,Report_COVID-19_deaths_by_race/ethnicity,Report_COVID-19_vaccinations_by_race/ethnicity,Report_Indigenous_COVID-19_testing,Report_Indigenous_COVID-19_cases,Report_Indigenous_COVID-19_hospitalizations,Report_Indigenous_COVID-19_deaths,Report_Indigenous_COVID-19_vaccinations,Stopped_personal_visitation_in_state_prisons,Stopped_legal_visitation_in_state_prisons,Resumed_visitation_in_state_prisons,Stopped_visitation_in_state_prisons_x2,Resumed_visitation_in_state_prisons_x2,Does_not_charge_copays_for_incarcerated_individuals,Waived_COVID/respiratory_illness-related_copays_during_pandemic_for_incarcerated_individuals,Waived_all_copays_during_pandemic_for_incarcerated_individuals,Did_not_waive_copays_for_incarcerated_individuals,Suspended_elective_medical_procedures,Resumed_elective_medical_procedures,No_order_to_suspend_elective_medical_procedures_but_did_release_guidance_or_orders_to_resume,Suspended_elective_medical_procedures_x2,Resumed_elective_medical_procedures_x2,No_state_unemployment_waiting_period_prior_to_pandemic;_or_date_waiting_period_waived_not_found,Waived_one_week_waiting_period_for_unemployment_insurance,Reinstated_one_week_waiting_period_for_unemployment_insurance,Waived_work_search_requirement_for_unemployment_insurance,Reinstated_work_search_requirement_for_UI,Expanded_eligibility_of_unemployment_insurance_to_anyone_who_is_quarantined_and/or_taking_care_of_someone_who_is_quarantined,Expanded_eligibility_to_high-risk_individuals_in_preventative_quarantine,Expanded_eligibility_of_unemployment_insurance_to_those_who_have_lost_childcare/school_closures,Extended_the_amount_of_time_an_individual_can_be_on_unemployment_insurance,Weekly_unemployment_insurance_maximum_amount_(dollars),"Weekly_unemployment_insurance_maximum_amount_with_extra_stimulus_(through_July_31,_2020)_(dollars)",January_2020_unemployment_insurance_maximum_duration_(weeks),July_2020_unemployment_insurance_maximum_duration_(weeks),2021_unemployment_insurance_maximum_duration_(weeks),Extended_Benefits_program_activated,Extended_Benefits_program_deactivated,Extended_Benefits_program_activated_x2,Total_Unemployment_Rate_at_Extended_Benefits_program_shutoff,Total_Unemployment_Rate_relative_to_prior_year_(%),Total_Unemployment_Rate_relative_to_second_prior_year_(%),20-week_Extended_Benefits_program_activated,20-week_Extended_Benefits_program_deactivated,20-week_Extended_Benefits_program_activated_x2,Stopped_participating_in_pandemic-related_federal_unemployment_benefit_programs,Minimum_total_earnings_required_in_the_base_period_to_qualify_for_UI,Number_of_calendar_quarters_with_earnings_in_the_base_period_needed_to_qualify_for_UI,Minimum_total_earnings_required_outside_the_highest_earning_calendar_quarter_of_the_base_period_to_qualify_for_UI,Require_earnings_in_the_last_two_calendar_quarters_of_the_base_period_in_order_to_qualify_for_UI,Earnings_in_base_period_required_to_receive_a_$300_weekly_benefit_amount_for_UI,Taxable_Wage_Amount,Minimum_Tax_Rate_(%),Maximum_Tax_Rate_(%),Average_Benefit_Amount_(August),OSHA-approved_state_plan,State_department_in_charge_of_enforcing_programs,Aerosol_transmissable_diseases_standards,Air_or_ventilation_standards,Paid_sick_leave_prior_to_pandemic,Paid_sick_leave_expansion_during_pandemic,COVID-19_anti-retaliation_rules,COVID-19_business_liability_protections,COVID-19_liability_protections_for_healthcare_providers,Branch_of_government_implementing_COVID-19_liability_rules,COVID-19_workers'_compensation_expansion,Types_of_workers_eligible_for_workers'_compensation_expansion,Data_reporting_required_for_medical_treatment,Minimum_number_of_work_days_missed_by_workers_to_require_data_reporting,"Occupational_injuries,_illnesses,_and_fatalities_reporting_prior_to_pandemic",Made_Effort_to_Limit_Abortion_Access,Use_of_telemedicine/telephone_evaluations_to_initiate_buprenorphine_prescribing,Patients_can_receive_14-28_take-home_doses_of_opioid_medication,Home_delivery_of_take-home_medication_by_opioid_treatment_programs,Use_of_telemedicine_for_schedule_II-V_prescriptions,Exceptions_to_emergency_oral_prescriptions,Waive_requirement_to_obtain_separate_DEA_registration_to_dispense_outside_home_state,Medicaid_Expansion,Population_density_per_square_miles,Population_2018,Square_Miles,Number_Homeless_(2019),Percent_Unemployed_(2018),Percent_living_under_the_federal_poverty_line_(2018),Percent_at_risk_for_serious_illness_due_to_COVID,All-cause_deaths_2018,"Mental_health_professionals_per_100,000_population_in_2019",Were_there_casino(s)_in_State?_(Land_and_Non-Land_based),State_has_at_least_one_Indian/Alaska_Native_reservation,"COVID-19_is_not_an_acceptable_reason_to_request_application_for_mail-in_ballot_unless_sick_or_exposed_(as_of_September_16,_2020)","Witness_or_notary_signature_required_for_mail-in_ballot_(as_of_September_1,_2020)",Permanent_mail-in_ballot_system,"Automatic_mail-in_ballot_system_in_response_to_COVID-19_(0,1,2_2_being_conditional-_see_notes_for_details)","Automatic_applications_sent_for_mail-in_ballots_in_response_to_COVID-19_(0,1,2_2_being_conditional-_see_notes_for_details)",Last_date_of_receipt_of_mail-in_ballot_request_for_the_general_election_(by_mail_or_online),Closed_casinos,Reopened_casinos,Closed_casinos_(x2),Reopened_casinos_(x2),Mention_of_tribal_casinos,Jan_1_2019_Minimum_Wage,Mar_29_2019_Minimum_Wage,Jul_1_2019_Minimum_Wage,Oct_1_2019_Minimum_Wage,Jan_1_2020_Minimum_Wage,Jul_1_2020_Minimum_Wage,Sep_1_2020_Minimum_Wage,Oct_1_2020_Minimum_Wage,2020_Minimum_Wage_for_Tipped_Workers,2021_Minimum_Wage,Different_Minimum_Wage_for_Smaller_Businesses,death,deathConfirmed,deathIncrease,deathProbable,hospitalized,hospitalizedCumulative,hospitalizedCurrently,hospitalizedIncrease,inIcuCumulative,inIcuCurrently,negative,negativeIncrease,negativeTestsAntibody,negativeTestsPeopleAntibody,negativeTestsViral,onVentilatorCumulative,onVentilatorCurrently,positive,positiveCasesViral,positiveIncrease,positiveScore,positiveTestsAntibody,positiveTestsAntigen,positiveTestsPeopleAntibody,positiveTestsPeopleAntigen,positiveTestsViral,recovered,totalTestEncountersViral,totalTestEncountersViralIncrease,totalTestResults,totalTestResultsIncrease,totalTestsAntibody,totalTestsAntigen,totalTestsPeopleAntibody,totalTestsPeopleAntigen,totalTestsPeopleViral,totalTestsPeopleViralIncrease,totalTestsViral,totalTestsViralIncrease,metrics.testPositivityRatio,metrics.vaccinationsInitiatedRatio,metrics.vaccinationsCompletedRatio,hhs_region,Variant % A.2.5,Variant % AY.1,Variant % AY.2,Variant % AY.3,Variant % B.1,Variant % B.1.1,Variant % B.1.1.194,Variant % B.1.1.519,Variant % B.1.1.529,Variant % B.1.1.7,Variant % B.1.2,Variant % B.1.234,Variant % B.1.243,Variant % B.1.351,Variant % B.1.427,Variant % B.1.429,Variant % B.1.525,Variant % B.1.526,Variant % B.1.526.1,Variant % B.1.526.2,Variant % B.1.596,Variant % B.1.617,Variant % B.1.617.1,Variant % B.1.617.2,Variant % B.1.617.3,Variant % B.1.621,Variant % B.1.621.1,Variant % B.1.626,Variant % B.1.628,Variant % B.1.637,Variant % BA.1.1,Variant % BA.2,Variant % BA.2.12.1,Variant % BA.2.75,Variant % BA.2.75.2,Variant % BA.4,Variant % BA.4.6,Variant % BA.5,Variant % BA.5.2.6,Variant % BF.11,Variant % BF.7,Variant % BN.1,Variant % BQ.1,Variant % BQ.1.1,Variant % CH.1.1,Variant % FD.2,Variant % Other,Variant % P.1,Variant % P.2,Variant % R.1,Variant % XBB,Variant % XBB.1.16,Variant % XBB.1.5,Variant % XBB.1.5.1,Variant % XBB.1.9.1,Variant % XBB.1.9.2,Variant % XBB.2.3
0,1001.0,2021-10-02,Autauga,Alabama,570.0,142.0,2021-10-02,620.0,645.142857,32.532237,-86.64644,594.443459,55200.0,23315.0,21115.0,8422.0,1065.0,29372.0,4204.0,8050.0,13369.0,10465.0,1586.0,13788.0,426.0,886.0,4279.0,299.0,1191.0,546.0,15.4,2.1,4.2,1.0,29372.0,2306.0,11.3,1.3,14.6,0.1,24.2,0.1,19.3,1.3,7.5,1.5,25.0,0.1,0.8,0.4,3.8,1.3,18.4,2.0,1.4,0.7,5.6,1.3,1.0,0.3,0.5401,0.2745,0.286,0.4397,1.5403,0.3631,0.185,0.7529,0.7905,0.3792,2.1076,0.581,0.6336,0.5113,1.1449,0.5947,0.6017,0.7408,0.2964,0.4846,0.1525,2.276,0.3741,7.0688,0.4354,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3875.0,7.1,0.9,37301.0,1.0,569.0,89.0,562.0,562.0,498.0,563.0,547.0,0.0,521.0,554.0,0.0,521.0,0.0,444.0,0.0,0.0,0.0,1.0,510.0,177.0,0.0,0.0,0.0,1.0,558.0,558.0,1.0,NaN,563.0,510.0,0.0,554.0,510.0,554.0,499.0,563.0,510.0,510.0,510.0,521.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,195.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,258.0,258.0,237.0,237.0,195.0,195.0,181.0,181.0,181.0,181.0,237.0,237.0,174.0,181.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,548.0,489.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,548.0,489.0,0.0,0.0,0.0,0.0,0.0,0.0,513.0,489.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,558.0,530.0,0.0,0.0,0.0,0.0,559.0,0.0,0.0,560.0,566.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,569.0,569.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,563.0,521.0,0.0,0.0,0.0,0.0,566.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,275.0,875.0,14.0,14.0,14.0,490.0,372.0,0.0,7.0,250.0,175.0,0.0,0.0,0.0,106.0,2340.0,2.0,780.0,0.0,NaN,8000.0,0.65,6.8,250.77,3.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,3.0,1.0,1.0,0.0,0.0,0.0,562.0,0.0,0.0,0.0,93.24,4887871.0,52420.0,3261.0,5.6,16.8,43.1,54352.0,100.7,1.0,1.0,0.0,1.0,0.0,0.0,0.0,44133.0,554.0,499.0,0.0,0.0,0.0,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25,2.13,7.25,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.125,0.430,0.338,4.0,0.0,0.000129,0.000187,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,2.919009e-08,0.000000,0.000000,0.0,0.000001,0.0,0.0,0.000000,0.0,2.069298e-13,0.986619,0.0,0.0,0.0,0.0,0.000019,0.000002,0.000073,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.012969,0.0,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000
1,1001.0,2023-03-01,Autauga,Alabama,229.0,232.0,2023-03-01,1135.0,205.857143,32.532237,-86.64644,594.443459,55200.0,23315.0,21115.0,8422.0,1065.0,29372.0,4204.0,8050.0,13369.0,10465.0,1586.0,13788.0,426.0,886.0,4279.0,299.0,1191.0,546.0,15.4,2.1,4.2,1.0,29372.0,2306.0,11.3,1.3,14.6,0.1,24.2,0.1,19.3,1.3,7.5,1.5,25.0,0.1,0.8,0.4,3.8,1.3,18.4,2.0,1.4,0.7,5.6,1.3,1.0,0.3,0.5401,0.2745,0.286,0.4397,1.5403,0.3631,0.185,0.7529,0.7905,0.3792,2.1076,0.581,0.6336,0.5113,1.1449,0.5947,0.6017,0.7408,0.2964,0.4846,0.1525,2.276,0.3741,7.0688,0.4354,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3875.0,7.1,0.9,37301.0,1.0,1084.0,604.0,1077.0,1077.0,1013.0,1078.0,1062.0,0.0,1036.0,1069.0,0.0,1036.0,0.0,959.0,0.0,0.0,0.0,1.0,1025.0,692.0,0.0,0.0,0.0,1.0,1073.0,1073.0,1.0,NaN,1078.0,1025.0,0.0,1069.0,1025.0,1069.0,1014.0,1078.0,1025.0,1025.0,1025.0,1036.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,710.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,773.0,773.0,752.0,752.0,710.0,710.0,696.0,696.0,696.0,696.0,752.0,752.0,689.0,696.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1063.0,1004.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1063.0,1004.0,0.0,0.0,0.0,0.0,0.0,0.0,1028.0,1004.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1073.0,1045.0,0.0,0.0,0.0,0.0,1074.0,0.0,0.0,1075.0,1081.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1084.0,1084.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1078.0,1036.0,0.0,0.0,0.0,0.0,1081.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,275.0,875.0,14.0,14.0,14.0,1005.0,887.0,0.0,7.0,250.0,175.0,0.0,0.0,0.0,621.0,2340.0,2.0,780.0,0.0,NaN,8000.0,0.65,6.8,250.77,3.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,3.0,1.0,1.0,0.0,0.0,0.0,1077.0,0.0,0.0,0.0,93.24,4887871.0,52420.0,3261.0,5.6,16.8,43.1,54352.0,100.7,1.0,1.0,0.0,1.0,0.0,0.0,0.0,44133.0,1069.0,1014.0,0.0,0.0,0.0,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25,2.13,7.25,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.047,0.579,0.460,4.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000,0.0,0.000000,0.0,0.0,0.000000,0.0,0.000000e+00,0.000000,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.001248,0.000000,0.003185,0.0,0.000000,0.0,0.006027,0.001129,0.0,0.003816,0.001872,0.017715,0.09292,0.014748,0.006661,0.000587,0.0,0.000000,0.0,0.016237,0.0,0.803846,0.022301,0.004402,0.002056,0.001248

In [18]:
print(augmented_df_pd.columns)

Index(['fips', 'date', 'county', 'state', 'cases', 'deaths', 'datetime',
       'days_from_start', 'rolled_cases', 'LAT',
       ...
       'Variant % P.1', 'Variant % P.2', 'Variant % R.1', 'Variant % XBB',
       'Variant % XBB.1.16', 'Variant % XBB.1.5', 'Variant % XBB.1.5.1',
       'Variant % XBB.1.9.1', 'Variant % XBB.1.9.2', 'Variant % XBB.2.3'],
      dtype='object', length=478)

### CUSP Impute

In [19]:
def replace_nan_forward_fill(df, columns):
    # Replace NaN values with 0 until the first non-NaN value,
    # within each 'fips' group and by 'date' for the specified columns
    copy_df = df.copy()
    def fill_nan_forward_fill(group):
        # Forward fill NaN values within each group after replacing preceding NaNs with 0
        group_filled = group.fillna(0)
        group_filled = group_filled.mask(group_filled.eq(0)).fillna(method='ffill')
        return group_filled
    
    # Group by 'fips' and apply forward fill within each group
    filled_values = copy_df.groupby(['fips'])[columns].fillna(method="ffill").fillna(0)
    
    # Update the specified columns with filled values
    copy_df[columns] = filled_values
    
    return copy_df

In [20]:
cusp_start = augmented_df_pd.columns.get_loc("death")
cusp_end = augmented_df_pd.columns.get_loc("metrics.vaccinationsCompletedRatio")
print((cusp_start,cusp_end))

vaccination_start = augmented_df_pd.columns.get_loc("Date_all_mandated_quarantines_ended")
vaccination_end = augmented_df_pd.columns.get_loc("Expanded_scope_of_practice_of_certain_health_providers_to_administer_vaccines")
print((vaccination_start,vaccination_end))

(378, 419)
(168, 212)

In [21]:
impute_columns = augmented_df_pd.columns[list((vaccination_start,vaccination_end)) + list((cusp_start,cusp_end))]

In [22]:
imputed_augmented_df_pd = augmented_df_pd.groupby("fips").ffill().fillna(0)
imputed_augmented_df_pd["fips"] = augmented_df_pd["fips"]

In [23]:
imputed_augmented_df_pd

,date,county,state,cases,deaths,datetime,days_from_start,rolled_cases,LAT,LON,AREA_SQMI,E_TOTPOP,E_HU,E_HH,E_POV,E_UNEMP,E_PCI,E_NOHSDP,E_AGE65,E_AGE17,E_DISABL,E_SNGPNT,E_MINRTY,E_LIMENG,E_MUNIT,E_MOBILE,E_CROWD,E_NOVEH,E_GROUPQ,EP_POV,MP_POV,EP_UNEMP,MP_UNEMP,EP_PCI,MP_PCI,EP_NOHSDP,MP_NOHSDP,EP_AGE65,MP_AGE65,EP_AGE17,MP_AGE17,EP_DISABL,MP_DISABL,EP_SNGPNT,MP_SNGPNT,EP_MINRTY,MP_MINRTY,EP_LIMENG,MP_LIMENG,EP_MUNIT,MP_MUNIT,EP_MOBILE,MP_MOBILE,EP_CROWD,MP_CROWD,EP_NOVEH,MP_NOVEH,EP_GROUPQ,MP_GROUPQ,EPL_POV,EPL_UNEMP,EPL_PCI,EPL_NOHSDP,SPL_THEME1,RPL_THEME1,EPL_AGE65,EPL_AGE17,EPL_DISABL,EPL_SNGPNT,SPL_THEME2,RPL_THEME2,EPL_MINRTY,EPL_LIMENG,SPL_THEME3,RPL_THEME3,EPL_MUNIT,EPL_MOBILE,EPL_CROWD,EPL_NOVEH,EPL_GROUPQ,SPL_THEME4,RPL_THEME4,SPL_THEMES,RPL_THEMES,F_POV,F_UNEMP,F_PCI,F_NOHSDP,F_THEME1,F_AGE65,F_AGE17,F_DISABL,F_SNGPNT,F_THEME2,F_MINRTY,F_LIMENG,F_THEME3,F_MUNIT,F_MOBILE,F_CROWD,F_NOVEH,F_GROUPQ,F_THEME4,F_TOTAL,E_UNINSUR,EP_UNINSUR,MP_UNINSUR,E_DAYPOP,State_FIPS_Code,State_of_emergency_issued,State_of_emergency_lifted,Date_closed_K-12_public_schools,Closed_day_cares,Reopen_day_cares,Date_banned_visitors_to_nursing_homes,Stay_at_home/_shelter_in_place,Stay_at_home_order'_issued_but_did_not_specifically_restrict_movement_of_the_general_public,End/relax_stay_at_home/shelter_in_place,Closed_other_non-essential_businesses,Closed_businesses_overnight,Began_to_reopen_businesses,Religious_gatherings_exempt_without_clear_social_distance_mandate*,Face_mask_mandate_in_public_spaces,Face_mask_mandate_x2,Face_mask_mandate_enforced_by_fines,Face_mask_mandate_enforced_by_criminal_charge/citation,No_legal_enforcement_of_face_mask_mandate,Face_mask_mandate_for_employees_of_public-facing_businesses,Ended_face_mask_mandate,Ended_face_mask_mandate_x2,Attempted_to_prevent_local_governments_from_implementing_face_mask_orders,Banned_local_mask_mandates,Liquor_stores_remained_open,Allowed_restaurants_to_sell_takeout_alcohol,Allowed_restaurants_to_deliver_alcohol,Firearm_sellers_remained_open,Cannabis_dispensaries_considered_essential_business,Closed_restaurants_except_take_out,Reopen_restaurants,Initially_reopen_restaurants_for_outdoor_dining_only,Closed_gyms,Reopened_gyms,Closed_movie_theaters,Reopened_movie_theaters,Closed_Bars,Reopen_bars,Reopened_hair_salons/barber_shops,Reopened_religious_gatherings,Reopened_other_non-essential_retail,Allowed_businesses_to_reopen_overnight,Began_to_reclose_bars,Closed_bars_(x2),Closed_movie_theaters_(x2),Closed_hair_salons/barber_shops_(x2),Closed_gyms_(x2),Closed_restaurants_(x2),Reopened_restaurants_(x2),Reopened_bars_(x2),Reopened_gyms_(x2),Reopened_hair_salons/barber_shops_(x2),Reopened_movie_theaters_(x2),Closed_bars_(x3),Closed_restaurants_(x3),Reopened_bars_(x3),Reopened_restaurants_(x3),Mandate_quarantine_for_those_entering_the_state_from_specific_settings,Mandate_quarantine_for_all_individuals_entering_the_state,Date_all_mandated_quarantines_ended,Date_vaccine_allocation_plan_last_updated,Vaccine_allocation_phase:_Frontline_Healthcare_Workers,Vaccine_allocation_phase:_Healthcare_Service_Workers,Vaccine_allocation_phase:_Home_Healthcare_Workers,Vaccine_allocation_phase:_Additional_Healthcare_Workers,Vaccine_allocation_phase:_Long-term_Care_Residents,Vaccine_allocation_phase:_EMS_Providers,Vaccine_allocation_phase:_Firefighters,Vaccine_allocation_phase:_Law_Enforcement_&_Public_Safety_Personnel,Vaccine_allocation_phase:_Correctional_Staff,Vaccine_allocation_phase:_People_who_are_Incarcerated,Vaccine_allocation_phase:_Residents_of_Homeless_Shelters,Vaccine_allocation_phase:_Adults_Ages_75+,Vaccine_allocation_phase:_Adults_Ages_65+,Vaccine_allocation_phase:_Adults_w/_High-Risk_Medical_Conditions,Vaccine_allocation_phase:_Pre-K-12_School_Employees,Vaccine_allocation_phase:_Higher_Education_Employees,Vaccine_allocation_phase:_Public_Transit_Workers,Vaccine_allocation_phase:_Food_Supply_Workers,Vaccine_allocation_phase:_Grocery_Store_Workers,Vaccine_allocation_phase:_Frontline_Essential_Workers,Vaccine_allocation_phase:_Additional_Essential_Workers,Vaccine_allocation_phase:_General_Public,Date_adults_ages_80+_became_eligible_for_COVID-19_vaccination,Date_adults_ages_75+_became_eligible_for_COVID-19_vaccination,Date_adults_ages_70+_became_eligible_for_COVID-19_vaccination,Date_adults_ages_65+_became_eligible_for_COVID-19_vaccination,Date_adults_ages_60+_became_eligible_for_COVID-19_vaccination,Date_adults_ages_55+_became_eligible_for_COVID-19_vaccination,Date_adults_ages_50+_became_eligible_for_COVID-19_vaccination,Date_adults_ages_45+_became_eligible_for_COVID-19_vaccination,Date_adults_ages_40+_became_eligible_for_COVID-19_vaccination,Date_adults_ages_30+_became_eligible_for_COVID-19_vaccination,Date_K-12_school_employees_became_eligible_for_COVID-19_vaccination,Date_grocery_store_workers_became_eligible_for_COVID-19_vaccination,Date_incarcerated_people_became_eligible_for_COVID-19_vaccination,Date_general_public_became_eligible_for_COVID-19_vaccination,Adults_ages_65+_prioritized_ahead_of_essential_workers,Prioritization_by_race/ethnicity,Proof_of_work_eligibility_requirement_for_vaccination,Proof_of_age_eligibility_requirement_for_vaccination,Proof_of_residency_requirement_for_vaccination,Penalty_for_failure_to_comply_with_vaccine_distribution_requirements,Expanded_scope_of_practice_of_certain_health_providers_to_administer_vaccines,First_overall_eviction_moratorium_start,First_overall_eviction_moratorium_end,Second_overall_eviction_moratorium_start,Second_overall_eviction_moratorium_end,Third_overall_eviction_moratorium_start,Third_overall_eviction_moratorium_end,First_eviction_initiation_ban_start,First_eviction_initiation_ban_end,Second_Eviction_Initiation_Ban_Start,Second_Eviction_Initiation_Ban_End,First_eviction_hearing_ban_start,First_eviction_hearing_ban_end,Second_Eviction_Hearing_Ban_Start,Second_Eviction_Hearing_Ban_End,First_eviction_enforcement_ban_start,First_eviction_enforcement_ban_end,Second_Eviction_Enforcement_Ban_Start,Second_Eviction_Enforcement_Ban_End,COVID-19_hardship_limitation_start,COVID-19_hardship_limitation_end,Second_COVID-19_hardship_limitation_start,Second_COVID-19_hardship_limitation_end,Non-payment_limitation_start,Non-payment_limitation_end,Second_non-payment_limitation_start,Second_non-payment_limitation_end,CARES_Act_pleading_start,CARES_Act_pleading_end,CDC_moratorium_start,CDC_moratorium_end,Late_Fee_Ban_Start,Late_Fee_Ban_End,Second_Late_Fee_Ban_Start,Second_Late_Fee_Ban_End,Utilities_shutoff_moratorium_start,Utilities_shutoff_moratorium_expiration,Second_utilities_shutoff_moratorium_start,Utilities_reconnection_start,Utilities_reconnection_end,SNAP_Waiver_-_Emergency_Allotments_to_Current_SNAP_Households,SNAP_Waiver_-_Pandemic_EBT_during_school_year_2019-2020,SNAP_Waiver_-_Pandemic_EBT_during_school_year_2020-2021,SNAP_Waiver_-_Pandemic_EBT_during_summer_2021,SNAP_Waiver_-_Temporary_Suspension_of_Claims_Collection,2020_Q1_SNAP_ABAWD_Time_Limit_Waiver,Modify_Medicaid_requirements_with_1135_waivers_(date_of_CMS_approval),Reopened_ACA_enrollment_using_a_special_enrollment_period,State_previously_allowed_audio-only_telehealth,Allow_audio-only_telehealth,Allow/expand_Medicaid_telehealth_coverage,State_had_CHIP_premium_non-payment_lock-out_period_as_of_January_2019,Suspend_CHIP_premium_non-payment_lock-outs,Report_COVID-19_testing_by_race/ethnicity,Report_COVID-19_cases_by_race/ethnicity,Report_COVID-19_hospitalizations_by_race,Report_COVID-19_deaths_by_race/ethnicity,Report_COVID-19_vaccinations_by_race/ethnicity,Report_Indigenous_COVID-19_testing,Report_Indigenous_COVID-19_cases,Report_Indigenous_COVID-19_hospitalizations,Report_Indigenous_COVID-19_deaths,Report_Indigenous_COVID-19_vaccinations,Stopped_personal_visitation_in_state_prisons,Stopped_legal_visitation_in_state_prisons,Resumed_visitation_in_state_prisons,Stopped_visitation_in_state_prisons_x2,Resumed_visitation_in_state_prisons_x2,Does_not_charge_copays_for_incarcerated_individuals,Waived_COVID/respiratory_illness-related_copays_during_pandemic_for_incarcerated_individuals,Waived_all_copays_during_pandemic_for_incarcerated_individuals,Did_not_waive_copays_for_incarcerated_individuals,Suspended_elective_medical_procedures,Resumed_elective_medical_procedures,No_order_to_suspend_elective_medical_procedures_but_did_release_guidance_or_orders_to_resume,Suspended_elective_medical_procedures_x2,Resumed_elective_medical_procedures_x2,No_state_unemployment_waiting_period_prior_to_pandemic;_or_date_waiting_period_waived_not_found,Waived_one_week_waiting_period_for_unemployment_insurance,Reinstated_one_week_waiting_period_for_unemployment_insurance,Waived_work_search_requirement_for_unemployment_insurance,Reinstated_work_search_requirement_for_UI,Expanded_eligibility_of_unemployment_insurance_to_anyone_who_is_quarantined_and/or_taking_care_of_someone_who_is_quarantined,Expanded_eligibility_to_high-risk_individuals_in_preventative_quarantine,Expanded_eligibility_of_unemployment_insurance_to_those_who_have_lost_childcare/school_closures,Extended_the_amount_of_time_an_individual_can_be_on_unemployment_insurance,Weekly_unemployment_insurance_maximum_amount_(dollars),"Weekly_unemployment_insurance_maximum_amount_with_extra_stimulus_(through_July_31,_2020)_(dollars)",January_2020_unemployment_insurance_maximum_duration_(weeks),July_2020_unemployment_insurance_maximum_duration_(weeks),2021_unemployment_insurance_maximum_duration_(weeks),Extended_Benefits_program_activated,Extended_Benefits_program_deactivated,Extended_Benefits_program_activated_x2,Total_Unemployment_Rate_at_Extended_Benefits_program_shutoff,Total_Unemployment_Rate_relative_to_prior_year_(%),Total_Unemployment_Rate_relative_to_second_prior_year_(%),20-week_Extended_Benefits_program_activated,20-week_Extended_Benefits_program_deactivated,20-week_Extended_Benefits_program_activated_x2,Stopped_participating_in_pandemic-related_federal_unemployment_benefit_programs,Minimum_total_earnings_required_in_the_base_period_to_qualify_for_UI,Number_of_calendar_quarters_with_earnings_in_the_base_period_needed_to_qualify_for_UI,Minimum_total_earnings_required_outside_the_highest_earning_calendar_quarter_of_the_base_period_to_qualify_for_UI,Require_earnings_in_the_last_two_calendar_quarters_of_the_base_period_in_order_to_qualify_for_UI,Earnings_in_base_period_required_to_receive_a_$300_weekly_benefit_amount_for_UI,Taxable_Wage_Amount,Minimum_Tax_Rate_(%),Maximum_Tax_Rate_(%),Average_Benefit_Amount_(August),OSHA-approved_state_plan,State_department_in_charge_of_enforcing_programs,Aerosol_transmissable_diseases_standards,Air_or_ventilation_standards,Paid_sick_leave_prior_to_pandemic,Paid_sick_leave_expansion_during_pandemic,COVID-19_anti-retaliation_rules,COVID-19_business_liability_protections,COVID-19_liability_protections_for_healthcare_providers,Branch_of_government_implementing_COVID-19_liability_rules,COVID-19_workers'_compensation_expansion,Types_of_workers_eligible_for_workers'_compensation_expansion,Data_reporting_required_for_medical_treatment,Minimum_number_of_work_days_missed_by_workers_to_require_data_reporting,"Occupational_injuries,_illnesses,_and_fatalities_reporting_prior_to_pandemic",Made_Effort_to_Limit_Abortion_Access,Use_of_telemedicine/telephone_evaluations_to_initiate_buprenorphine_prescribing,Patients_can_receive_14-28_take-home_doses_of_opioid_medication,Home_delivery_of_take-home_medication_by_opioid_treatment_programs,Use_of_telemedicine_for_schedule_II-V_prescriptions,Exceptions_to_emergency_oral_prescriptions,Waive_requirement_to_obtain_separate_DEA_registration_to_dispense_outside_home_state,Medicaid_Expansion,Population_density_per_square_miles,Population_2018,Square_Miles,Number_Homeless_(2019),Percent_Unemployed_(2018),Percent_living_under_the_federal_poverty_line_(2018),Percent_at_risk_for_serious_illness_due_to_COVID,All-cause_deaths_2018,"Mental_health_professionals_per_100,000_population_in_2019",Were_there_casino(s)_in_State?_(Land_and_Non-Land_based),State_has_at_least_one_Indian/Alaska_Native_reservation,"COVID-19_is_not_an_acceptable_reason_to_request_application_for_mail-in_ballot_unless_sick_or_exposed_(as_of_September_16,_2020)","Witness_or_notary_signature_required_for_mail-in_ballot_(as_of_September_1,_2020)",Permanent_mail-in_ballot_system,"Automatic_mail-in_ballot_system_in_response_to_COVID-19_(0,1,2_2_being_conditional-_see_notes_for_details)","Automatic_applications_sent_for_mail-in_ballots_in_response_to_COVID-19_(0,1,2_2_being_conditional-_see_notes_for_details)",Last_date_of_receipt_of_mail-in_ballot_request_for_the_general_election_(by_mail_or_online),Closed_casinos,Reopened_casinos,Closed_casinos_(x2),Reopened_casinos_(x2),Mention_of_tribal_casinos,Jan_1_2019_Minimum_Wage,Mar_29_2019_Minimum_Wage,Jul_1_2019_Minimum_Wage,Oct_1_2019_Minimum_Wage,Jan_1_2020_Minimum_Wage,Jul_1_2020_Minimum_Wage,Sep_1_2020_Minimum_Wage,Oct_1_2020_Minimum_Wage,2020_Minimum_Wage_for_Tipped_Workers,2021_Minimum_Wage,Different_Minimum_Wage_for_Smaller_Businesses,death,deathConfirmed,deathIncrease,deathProbable,hospitalized,hospitalizedCumulative,hospitalizedCurrently,hospitalizedIncrease,inIcuCumulative,inIcuCurrently,negative,negativeIncrease,negativeTestsAntibody,negativeTestsPeopleAntibody,negativeTestsViral,onVentilatorCumulative,onVentilatorCurrently,positive,positiveCasesViral,positiveIncrease,positiveScore,positiveTestsAntibody,positiveTestsAntigen,positiveTestsPeopleAntibody,positiveTestsPeopleAntigen,positiveTestsViral,recovered,totalTestEncountersViral,totalTestEncountersViralIncrease,totalTestResults,totalTestResultsIncrease,totalTestsAntibody,totalTestsAntigen,totalTestsPeopleAntibody,totalTestsPeopleAntigen,totalTestsPeopleViral,totalTestsPeopleViralIncrease,totalTestsViral,totalTestsViralIncrease,metrics.testPositivityRatio,metrics.vaccinationsInitiatedRatio,metrics.vaccinationsCompletedRatio,hhs_region,Variant % A.2.5,Variant % AY.1,Variant % AY.2,Variant % AY.3,Variant % B.1,Variant % B.1.1,Variant % B.1.1.194,Variant % B.1.1.519,Variant % B.1.1.529,Variant % B.1.1.7,Variant % B.1.2,Variant % B.1.234,Variant % B.1.243,Variant % B.1.351,Variant % B.1.427,Variant % B.1.429,Variant % B.1.525,Variant % B.1.526,Variant % B.1.526.1,Variant % B.1.526.2,Variant % B.1.596,Variant % B.1.617,Variant % B.1.617.1,Variant % B.1.617.2,Variant % B.1.617.3,Variant % B.1.621,Variant % B.1.621.1,Variant % B.1.626,Variant % B.1.628,Variant % B.1.637,Variant % BA.1.1,Variant % BA.2,Variant % BA.2.12.1,Variant % BA.2.75,Variant % BA.2.75.2,Variant % BA.4,Variant % BA.4.6,Variant % BA.5,Variant % BA.5.2.6,Variant % BF.11,Variant % BF.7,Variant % BN.1,Variant % BQ.1,Variant % BQ.1.1,Variant % CH.1.1,Variant % FD.2,Variant % Other,Variant % P.1,Variant % P.2,Variant % R.1,Variant % XBB,Variant % XBB.1.16,Variant % XBB.1.5,Variant % XBB.1.5.1,Variant % XBB.1.9.1,Variant % XBB.1.9.2,Variant % XBB.2.3,fips
0,2021-10-02,Autauga,Alabama,570.0,142.0,2021-10-02,620.0,645.142857,32.532237,-86.64644,594.443459,55200.0,23315.0,21115.0,8422.0,1065.0,29372.0,4204.0,8050.0,13369.0,10465.0,1586.0,13788.0,426.0,886.0,4279.0,299.0,1191.0,546.0,15.4,2.1,4.2,1.0,29372.0,2306.0,11.3,1.3,14.6,0.1,24.2,0.1,19.3,1.3,7.5,1.5,25.0,0.1,0.8,0.4,3.8,1.3,18.4,2.0,1.4,0.7,5.6,1.3,1.0,0.3,0.5401,0.2745,0.2860,0.4397,1.5403,0.3631,0.1850,0.7529,0.7905,0.3792,2.1076,0.5810,0.6336,0.5113,1.1449,0.5947,0.6017,0.7408,0.2964,0.4846,0.1525,2.2760,0.3741,7.0688,0.4354,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3875.0,7.1,0.9,37301.0,1.0,569.0,89.0,562.0,562.0,498.0,563.0,547.0,0.0,521.0,554.0,0.0,521.0,0.0,444.0,0.0,0.0,0.0,1.0,510.0,177.0,0.0,0.0,0.0,1.0,558.0,558.0,1.0,0.0,563.0,510.0,0.0,554.0,510.0,554.0,499.0,563.0,510.0,510.0,510.0,521.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,195.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,258.0,258.0,237.0,237.0,195.0,195.0,181.0,181.0,181.0,181.0,237.0,237.0,174.0,181.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,548.0,489.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,548.0,489.0,0.0,0.0,0.0,0.0,0.0,0.0,513.0,489.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,558.0,530.0,0.0,0.0,0.0,0.0,559.0,0.0,0.0,560.0,566.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,569.0,569.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,563.0,521.0,0.0,0.0,0.0,0.0,566.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,275.0,875.0,14.0,14.0,14.0,490.0,372.0,0.0,7.0,250.0,175.0,0.0,0.0,0.0,106.0,2340.0,2.0,780.0,0.0,0.0,8000.0,0.65,6.8,250.77,3.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,3.0,1.0,1.0,0.0,0.0,0.0,562.0,0.0,0.0,0.0,93.24,4887871.0,52420.0,3261.0,5.6,16.8,43.1,54352.0,100.7,1.0,1.0,0.0,1.0,0.0,0.0,0.0,44133.0,554.0,499.0,0.0,0.0,0.0,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25,2.13,7.25,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.125,0.430,0.338,4.0,0.000000,0.000129,0.000187,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.919009e-08,0.000000,0.000000,0.0,0.000001,0.0,0.0,0.000000,0.0,2.069298e-13,0.986619,0.0,0.000000,0.000000,0.000000,0.000019,0.000002,0.000073,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.012969,0.000000,0.000000,0.0,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,1001.0

In [24]:
imputed_augmented_df_pd["Vaccine_allocation_phase:_Residents_of_Homeless_Shelters"].unique()

array([0., 2., 3., 1., 4.])

In [25]:
augmented_df_pd.columns.get_loc("Vaccine_allocation_phase:_Residents_of_Homeless_Shelters")

180

In [26]:
imputed_augmented_df_pd["E_POV"].unique()

array([  8422.,  21653.,   6597., ...,    984.,   1171., 295165.])

In [27]:
imputed_augmented_df_pd.to_parquet("imputed_augmented_us-counties-states_latest_variants.parquet")

In [28]:
imputed_augmented_df_pd.to_csv("imputed_augmented_us-counties-states_latest_variants.csv")