In [16]:
import os
import ast
import glob
import pickle
import itertools
from collections import Counter
from functools import reduce

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import matplotlib.dates as mdates

import statsmodels.api as sm
from statsmodels.regression.rolling import RollingOLS

import econml
from econml.grf import CausalForest

import dask
import dask.dataframe as dd
from dask.distributed import Client
from dask.diagnostics import ProgressBar

import concurrent.futures
from multiprocessing import Pool, cpu_count
from concurrent.futures import ThreadPoolExecutor
from joblib import Parallel, delayed

import dask_ml.cluster as dask_cluster

from tqdm.notebook import tqdm

from sklearn.metrics import pairwise_distances, mean_squared_error, mean_absolute_error
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split, cross_val_score

pd.set_option('display.max_columns', None)

# Uncomment the following line if needed
# from sklearn.cluster import KMeans

# Uncomment the following line if needed
# from tqdm import tqdm

from pprint import pprint

### Read Dataset

In [2]:
destfile = ("../../data/augmented_us-counties-states_latest_variants.csv")
augmented_panel_data = dd.read_csv(destfile, assume_missing=True)

hhs_X_w_clusters_fpath = "../benchmark_tcv_kmeans_code/hhs_X_w_clusters.csv"
hhs_X_w_clusters = dd.read_csv(hhs_X_w_clusters_fpath, assume_missing=True).compute()
hhs_X_w_clusters = hhs_X_w_clusters.sort_values(by="fips")

### Add Transformations

In [5]:
early_data = augmented_panel_data[augmented_panel_data["days_from_start"] <= 300]
early_data = early_data[early_data["rolled_cases"] >= 20]
early_data["log_rolled_cases"] = np.log(early_data["rolled_cases"] + 1)
early_data = early_data.compute()
early_data = early_data.sort_values(by=["fips", "days_from_start"])
early_data['shifted_days_from_start'] = early_data.groupby('fips')['days_from_start'].transform(lambda x: x - x.min())

NameError: name 'head' is not defined

In [6]:
early_data

,fips,date,county,state,cases,deaths,datetime,days_from_start,rolled_cases,LAT,LON,AREA_SQMI,E_TOTPOP,E_HU,E_HH,E_POV,E_UNEMP,E_PCI,E_NOHSDP,E_AGE65,E_AGE17,E_DISABL,E_SNGPNT,E_MINRTY,E_LIMENG,E_MUNIT,E_MOBILE,E_CROWD,E_NOVEH,E_GROUPQ,EP_POV,MP_POV,EP_UNEMP,MP_UNEMP,EP_PCI,MP_PCI,EP_NOHSDP,MP_NOHSDP,EP_AGE65,MP_AGE65,EP_AGE17,MP_AGE17,EP_DISABL,MP_DISABL,EP_SNGPNT,MP_SNGPNT,EP_MINRTY,MP_MINRTY,EP_LIMENG,MP_LIMENG,EP_MUNIT,MP_MUNIT,EP_MOBILE,MP_MOBILE,EP_CROWD,MP_CROWD,EP_NOVEH,MP_NOVEH,EP_GROUPQ,MP_GROUPQ,EPL_POV,EPL_UNEMP,EPL_PCI,EPL_NOHSDP,SPL_THEME1,RPL_THEME1,EPL_AGE65,EPL_AGE17,EPL_DISABL,EPL_SNGPNT,SPL_THEME2,RPL_THEME2,EPL_MINRTY,EPL_LIMENG,SPL_THEME3,RPL_THEME3,EPL_MUNIT,EPL_MOBILE,EPL_CROWD,EPL_NOVEH,EPL_GROUPQ,SPL_THEME4,RPL_THEME4,SPL_THEMES,RPL_THEMES,F_POV,F_UNEMP,F_PCI,F_NOHSDP,F_THEME1,F_AGE65,F_AGE17,F_DISABL,F_SNGPNT,F_THEME2,F_MINRTY,F_LIMENG,F_THEME3,F_MUNIT,F_MOBILE,F_CROWD,F_NOVEH,F_GROUPQ,F_THEME4,F_TOTAL,E_UNINSUR,EP_UNINSUR,MP_UNINSUR,E_DAYPOP,State_FIPS_Code,State_of_emergency_issued,State_of_emergency_lifted,Date_closed_K-12_public_schools,Closed_day_cares,Reopen_day_cares,Date_banned_visitors_to_nursing_homes,Stay_at_home/_shelter_in_place,Stay_at_home_order'_issued_but_did_not_specifically_restrict_movement_of_the_general_public,End/relax_stay_at_home/shelter_in_place,Closed_other_non-essential_businesses,Closed_businesses_overnight,Began_to_reopen_businesses,Religious_gatherings_exempt_without_clear_social_distance_mandate*,Face_mask_mandate_in_public_spaces,Face_mask_mandate_x2,Face_mask_mandate_enforced_by_fines,Face_mask_mandate_enforced_by_criminal_charge/citation,No_legal_enforcement_of_face_mask_mandate,Face_mask_mandate_for_employees_of_public-facing_businesses,Ended_face_mask_mandate,Ended_face_mask_mandate_x2,Attempted_to_prevent_local_governments_from_implementing_face_mask_orders,Banned_local_mask_mandates,Liquor_stores_remained_open,Allowed_restaurants_to_sell_takeout_alcohol,Allowed_restaurants_to_deliver_alcohol,Firearm_sellers_remained_open,Cannabis_dispensaries_considered_essential_business,Closed_restaurants_except_take_out,Reopen_restaurants,Initially_reopen_restaurants_for_outdoor_dining_only,Closed_gyms,Reopened_gyms,Closed_movie_theaters,Reopened_movie_theaters,Closed_Bars,Reopen_bars,Reopened_hair_salons/barber_shops,Reopened_religious_gatherings,Reopened_other_non-essential_retail,Allowed_businesses_to_reopen_overnight,Began_to_reclose_bars,Closed_bars_(x2),Closed_movie_theaters_(x2),Closed_hair_salons/barber_shops_(x2),Closed_gyms_(x2),Closed_restaurants_(x2),Reopened_restaurants_(x2),Reopened_bars_(x2),Reopened_gyms_(x2),Reopened_hair_salons/barber_shops_(x2),Reopened_movie_theaters_(x2),Closed_bars_(x3),Closed_restaurants_(x3),Reopened_bars_(x3),Reopened_restaurants_(x3),Mandate_quarantine_for_those_entering_the_state_from_specific_settings,Mandate_quarantine_for_all_individuals_entering_the_state,Date_all_mandated_quarantines_ended,Date_vaccine_allocation_plan_last_updated,Vaccine_allocation_phase:_Frontline_Healthcare_Workers,Vaccine_allocation_phase:_Healthcare_Service_Workers,Vaccine_allocation_phase:_Home_Healthcare_Workers,Vaccine_allocation_phase:_Additional_Healthcare_Workers,Vaccine_allocation_phase:_Long-term_Care_Residents,Vaccine_allocation_phase:_EMS_Providers,Vaccine_allocation_phase:_Firefighters,Vaccine_allocation_phase:_Law_Enforcement_&_Public_Safety_Personnel,Vaccine_allocation_phase:_Correctional_Staff,Vaccine_allocation_phase:_People_who_are_Incarcerated,Vaccine_allocation_phase:_Residents_of_Homeless_Shelters,Vaccine_allocation_phase:_Adults_Ages_75+,Vaccine_allocation_phase:_Adults_Ages_65+,Vaccine_allocation_phase:_Adults_w/_High-Risk_Medical_Conditions,Vaccine_allocation_phase:_Pre-K-12_School_Employees,Vaccine_allocation_phase:_Higher_Education_Employees,Vaccine_allocation_phase:_Public_Transit_Workers,Vaccine_allocation_phase:_Food_Supply_Workers,Vaccine_allocation_phase:_Grocery_Store_Workers,Vaccine_allocation_phase:_Frontline_Essential_Workers,Vaccine_allocation_phase:_Additional_Essential_Workers,Vaccine_allocation_phase:_General_Public,Date_adults_ages_80+_became_eligible_for_COVID-19_vaccination,Date_adults_ages_75+_became_eligible_for_COVID-19_vaccination,Date_adults_ages_70+_became_eligible_for_COVID-19_vaccination,Date_adults_ages_65+_became_eligible_for_COVID-19_vaccination,Date_adults_ages_60+_became_eligible_for_COVID-19_vaccination,Date_adults_ages_55+_became_eligible_for_COVID-19_vaccination,Date_adults_ages_50+_became_eligible_for_COVID-19_vaccination,Date_adults_ages_45+_became_eligible_for_COVID-19_vaccination,Date_adults_ages_40+_became_eligible_for_COVID-19_vaccination,Date_adults_ages_30+_became_eligible_for_COVID-19_vaccination,Date_K-12_school_employees_became_eligible_for_COVID-19_vaccination,Date_grocery_store_workers_became_eligible_for_COVID-19_vaccination,Date_incarcerated_people_became_eligible_for_COVID-19_vaccination,Date_general_public_became_eligible_for_COVID-19_vaccination,Adults_ages_65+_prioritized_ahead_of_essential_workers,Prioritization_by_race/ethnicity,Proof_of_work_eligibility_requirement_for_vaccination,Proof_of_age_eligibility_requirement_for_vaccination,Proof_of_residency_requirement_for_vaccination,Penalty_for_failure_to_comply_with_vaccine_distribution_requirements,Expanded_scope_of_practice_of_certain_health_providers_to_administer_vaccines,First_overall_eviction_moratorium_start,First_overall_eviction_moratorium_end,Second_overall_eviction_moratorium_start,Second_overall_eviction_moratorium_end,Third_overall_eviction_moratorium_start,Third_overall_eviction_moratorium_end,First_eviction_initiation_ban_start,First_eviction_initiation_ban_end,Second_Eviction_Initiation_Ban_Start,Second_Eviction_Initiation_Ban_End,First_eviction_hearing_ban_start,First_eviction_hearing_ban_end,Second_Eviction_Hearing_Ban_Start,Second_Eviction_Hearing_Ban_End,First_eviction_enforcement_ban_start,First_eviction_enforcement_ban_end,Second_Eviction_Enforcement_Ban_Start,Second_Eviction_Enforcement_Ban_End,COVID-19_hardship_limitation_start,COVID-19_hardship_limitation_end,Second_COVID-19_hardship_limitation_start,Second_COVID-19_hardship_limitation_end,Non-payment_limitation_start,Non-payment_limitation_end,Second_non-payment_limitation_start,Second_non-payment_limitation_end,CARES_Act_pleading_start,CARES_Act_pleading_end,CDC_moratorium_start,CDC_moratorium_end,Late_Fee_Ban_Start,Late_Fee_Ban_End,Second_Late_Fee_Ban_Start,Second_Late_Fee_Ban_End,Utilities_shutoff_moratorium_start,Utilities_shutoff_moratorium_expiration,Second_utilities_shutoff_moratorium_start,Utilities_reconnection_start,Utilities_reconnection_end,SNAP_Waiver_-_Emergency_Allotments_to_Current_SNAP_Households,SNAP_Waiver_-_Pandemic_EBT_during_school_year_2019-2020,SNAP_Waiver_-_Pandemic_EBT_during_school_year_2020-2021,SNAP_Waiver_-_Pandemic_EBT_during_summer_2021,SNAP_Waiver_-_Temporary_Suspension_of_Claims_Collection,2020_Q1_SNAP_ABAWD_Time_Limit_Waiver,Modify_Medicaid_requirements_with_1135_waivers_(date_of_CMS_approval),Reopened_ACA_enrollment_using_a_special_enrollment_period,State_previously_allowed_audio-only_telehealth,Allow_audio-only_telehealth,Allow/expand_Medicaid_telehealth_coverage,State_had_CHIP_premium_non-payment_lock-out_period_as_of_January_2019,Suspend_CHIP_premium_non-payment_lock-outs,Report_COVID-19_testing_by_race/ethnicity,Report_COVID-19_cases_by_race/ethnicity,Report_COVID-19_hospitalizations_by_race,Report_COVID-19_deaths_by_race/ethnicity,Report_COVID-19_vaccinations_by_race/ethnicity,Report_Indigenous_COVID-19_testing,Report_Indigenous_COVID-19_cases,Report_Indigenous_COVID-19_hospitalizations,Report_Indigenous_COVID-19_deaths,Report_Indigenous_COVID-19_vaccinations,Stopped_personal_visitation_in_state_prisons,Stopped_legal_visitation_in_state_prisons,Resumed_visitation_in_state_prisons,Stopped_visitation_in_state_prisons_x2,Resumed_visitation_in_state_prisons_x2,Does_not_charge_copays_for_incarcerated_individuals,Waived_COVID/respiratory_illness-related_copays_during_pandemic_for_incarcerated_individuals,Waived_all_copays_during_pandemic_for_incarcerated_individuals,Did_not_waive_copays_for_incarcerated_individuals,Suspended_elective_medical_procedures,Resumed_elective_medical_procedures,No_order_to_suspend_elective_medical_procedures_but_did_release_guidance_or_orders_to_resume,Suspended_elective_medical_procedures_x2,Resumed_elective_medical_procedures_x2,No_state_unemployment_waiting_period_prior_to_pandemic;_or_date_waiting_period_waived_not_found,Waived_one_week_waiting_period_for_unemployment_insurance,Reinstated_one_week_waiting_period_for_unemployment_insurance,Waived_work_search_requirement_for_unemployment_insurance,Reinstated_work_search_requirement_for_UI,Expanded_eligibility_of_unemployment_insurance_to_anyone_who_is_quarantined_and/or_taking_care_of_someone_who_is_quarantined,Expanded_eligibility_to_high-risk_individuals_in_preventative_quarantine,Expanded_eligibility_of_unemployment_insurance_to_those_who_have_lost_childcare/school_closures,Extended_the_amount_of_time_an_individual_can_be_on_unemployment_insurance,Weekly_unemployment_insurance_maximum_amount_(dollars),"Weekly_unemployment_insurance_maximum_amount_with_extra_stimulus_(through_July_31,_2020)_(dollars)",January_2020_unemployment_insurance_maximum_duration_(weeks),July_2020_unemployment_insurance_maximum_duration_(weeks),2021_unemployment_insurance_maximum_duration_(weeks),Extended_Benefits_program_activated,Extended_Benefits_program_deactivated,Extended_Benefits_program_activated_x2,Total_Unemployment_Rate_at_Extended_Benefits_program_shutoff,Total_Unemployment_Rate_relative_to_prior_year_(%),Total_Unemployment_Rate_relative_to_second_prior_year_(%),20-week_Extended_Benefits_program_activated,20-week_Extended_Benefits_program_deactivated,20-week_Extended_Benefits_program_activated_x2,Stopped_participating_in_pandemic-related_federal_unemployment_benefit_programs,Minimum_total_earnings_required_in_the_base_period_to_qualify_for_UI,Number_of_calendar_quarters_with_earnings_in_the_base_period_needed_to_qualify_for_UI,Minimum_total_earnings_required_outside_the_highest_earning_calendar_quarter_of_the_base_period_to_qualify_for_UI,Require_earnings_in_the_last_two_calendar_quarters_of_the_base_period_in_order_to_qualify_for_UI,Earnings_in_base_period_required_to_receive_a_$300_weekly_benefit_amount_for_UI,Taxable_Wage_Amount,Minimum_Tax_Rate_(%),Maximum_Tax_Rate_(%),Average_Benefit_Amount_(August),OSHA-approved_state_plan,State_department_in_charge_of_enforcing_programs,Aerosol_transmissable_diseases_standards,Air_or_ventilation_standards,Paid_sick_leave_prior_to_pandemic,Paid_sick_leave_expansion_during_pandemic,COVID-19_anti-retaliation_rules,COVID-19_business_liability_protections,COVID-19_liability_protections_for_healthcare_providers,Branch_of_government_implementing_COVID-19_liability_rules,COVID-19_workers'_compensation_expansion,Types_of_workers_eligible_for_workers'_compensation_expansion,Data_reporting_required_for_medical_treatment,Minimum_number_of_work_days_missed_by_workers_to_require_data_reporting,"Occupational_injuries,_illnesses,_and_fatalities_reporting_prior_to_pandemic",Made_Effort_to_Limit_Abortion_Access,Use_of_telemedicine/telephone_evaluations_to_initiate_buprenorphine_prescribing,Patients_can_receive_14-28_take-home_doses_of_opioid_medication,Home_delivery_of_take-home_medication_by_opioid_treatment_programs,Use_of_telemedicine_for_schedule_II-V_prescriptions,Exceptions_to_emergency_oral_prescriptions,Waive_requirement_to_obtain_separate_DEA_registration_to_dispense_outside_home_state,Medicaid_Expansion,Population_density_per_square_miles,Population_2018,Square_Miles,Number_Homeless_(2019),Percent_Unemployed_(2018),Percent_living_under_the_federal_poverty_line_(2018),Percent_at_risk_for_serious_illness_due_to_COVID,All-cause_deaths_2018,"Mental_health_professionals_per_100,000_population_in_2019",Were_there_casino(s)_in_State?_(Land_and_Non-Land_based),State_has_at_least_one_Indian/Alaska_Native_reservation,"COVID-19_is_not_an_acceptable_reason_to_request_application_for_mail-in_ballot_unless_sick_or_exposed_(as_of_September_16,_2020)","Witness_or_notary_signature_required_for_mail-in_ballot_(as_of_September_1,_2020)",Permanent_mail-in_ballot_system,"Automatic_mail-in_ballot_system_in_response_to_COVID-19_(0,1,2_2_being_conditional-_see_notes_for_details)","Automatic_applications_sent_for_mail-in_ballots_in_response_to_COVID-19_(0,1,2_2_being_conditional-_see_notes_for_details)",Last_date_of_receipt_of_mail-in_ballot_request_for_the_general_election_(by_mail_or_online),Closed_casinos,Reopened_casinos,Closed_casinos_(x2),Reopened_casinos_(x2),Mention_of_tribal_casinos,Jan_1_2019_Minimum_Wage,Mar_29_2019_Minimum_Wage,Jul_1_2019_Minimum_Wage,Oct_1_2019_Minimum_Wage,Jan_1_2020_Minimum_Wage,Jul_1_2020_Minimum_Wage,Sep_1_2020_Minimum_Wage,Oct_1_2020_Minimum_Wage,2020_Minimum_Wage_for_Tipped_Workers,2021_Minimum_Wage,Different_Minimum_Wage_for_Smaller_Businesses,death,deathConfirmed,deathIncrease,deathProbable,hospitalized,hospitalizedCumulative,hospitalizedCurrently,hospitalizedIncrease,inIcuCumulative,inIcuCurrently,negative,negativeIncrease,negativeTestsAntibody,negativeTestsPeopleAntibody,negativeTestsViral,onVentilatorCumulative,onVentilatorCurrently,positive,positiveCasesViral,positiveIncrease,positiveScore,positiveTestsAntibody,positiveTestsAntigen,positiveTestsPeopleAntibody,positiveTestsPeopleAntigen,positiveTestsViral,recovered,totalTestEncountersViral,totalTestEncountersViralIncrease,totalTestResults,totalTestResultsIncrease,totalTestsAntibody,totalTestsAntigen,totalTestsPeopleAntibody,totalTestsPeopleAntigen,totalTestsPeopleViral,totalTestsPeopleViralIncrease,totalTestsViral,totalTestsViralIncrease,metrics.testPositivityRatio,metrics.vaccinationsInitiatedRatio,metrics.vaccinationsCompletedRatio,hhs_region,Variant % A.2.5,Variant % AY.1,Variant % AY.2,Variant % AY.3,Variant % B.1,Variant % B.1.1,Variant % B.1.1.194,Variant % B.1.1.519,Variant % B.1.1.529,Variant % B.1.1.7,Variant % B.1.2,Variant % B.1.234,Variant % B.1.243,Variant % B.1.351,Variant % B.1.427,Variant % B.1.429,Variant % B.1.525,Variant % B.1.526,Variant % B.1.526.1,Variant % B.1.526.2,Variant % B.1.596,Variant % B.1.617,Variant % B.1.617.1,Variant % B.1.617.2,Variant % B.1.617.3,Variant % B.1.621,Variant % B.1.621.1,Variant % B.1.626,Variant % B.1.628,Variant % B.1.637,Variant % BA.1.1,Variant % BA.2,Variant % BA.2.12.1,Variant % BA.2.75,Variant % BA.2.75.2,Variant % BA.4,Variant % BA.4.6,Variant % BA.5,Variant % BA.5.2.6,Variant % BF.11,Variant % BF.7,Variant % BN.1,Variant % BQ.1,Variant % BQ.1.1,Variant % CH.1.1,Variant % FD.2,Variant % Other,Variant % P.1,Variant % P.2,Variant % R.1,Variant % XBB,Variant % XBB.1.16,Variant % XBB.1.5,Variant % XBB.1.5.1,Variant % XBB.1.9.1,Variant % XBB.1.9.2,Variant % XBB.2.3,log_rolled_cases,shifted_days_from_start
217,1001.0,2020-04-16,Autauga,Alabama,21.0,2.0,2020-04-16,86.0,20.285714,32.532237,-86.64644,594.443459,55200.0,23315.0,21115.0,8422.0,1065.0,29372.0,4204.0,8050.0,13369.0,10465.0,1586.0,13788.0,426.0,886.0,4279.0,299.0,1191.0,546.0,15.4,2.1,4.2,1.0,29372.0,2306.0,11.3,1.3,14.6,0.1,24.2,0.1,19.3,1.3,7.5,1.5,25.0,0.1,0.8,0.4,3.8,1.3,18.4,2.0,1.4,0.7,5.6,1.3,1.0,0.3,0.5401,0.2745,0.2860,0.4397,1.5403,0.3631,0.1850,0.7529,0.7905,0.3792,2.1076,0.5810,0.6336,0.5113,1.1449,0.5947,0.6017,0.7408,0.2964,0.4846,0.1525,2.2760,0.3741,7.0688,0.4354,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3875.0,7.1,0.9,37301.0,1.0,35.0,0.0,28.0,28.0,0.0,29.0,13.0,0.0,0.0,20.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,24.0,24.0,1.0,NaN,29.0,0.0,0.0,20.0,0.0,20.0,0.0,29.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,14.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,14.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,24.0,0.0,0.0,0.0,0.0,0.0,25.0,0.0,0.0,26.0,32.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,35.0,35.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,29.0,0.0,0.0,0.0,0.0,0.0,32.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,275.0,875.0,14.0,14.0,14.0,0.0,0.0,0.0,7.0,250.0,175.0,0.0,0.0,0.0,0.0,2340.0,2.0,780.0,0.0,NaN,8000.0,0.65,6.8,250.77,3.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,3.0,1.0,1.0,0.0,0.0,0.0,28.0,0.0,0.0,0.0,93.24,4887871.0,52420.0,3261.0,5.6,16.8,43.1,54352.0,100.7,1.0,1.0,0.0,1.0,0.0,0.0,0.0,44133.0,20.0,0.0,0.0,0.0,0.0,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25,2.13,7.25,0.0,133.0,NaN,12.0,NaN,553.0,553.0,360.0,28.0,227.0,NaN,32046.0,2082.0,NaN,NaN,NaN,137.0,NaN,4345.0,4345.0,232.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,36391.0,2314.0,NaN,NaN,NaN,NaN,36391.0,2314.0,NaN,0.0,0.065,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.053232,0.0,0.0,0.005078,0.0,0.000000,0.457294,0.044516,0.017216,0.0,0.005078,0.008237,0.0,0.000000,0.0,0.0,0.158909,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.240098,0.0,0.010343,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.009917,0.0
731,1001.0,2020-04-17,Autauga,Alabama,20.0,2.0,2020-04-17,87.0,20.714286,32.532237,-86.64644,594.443459,55200.0,23315.0,21115.0,8422.0,1065.0,29372.0,4204.0,8050.0,13369.0,10465.0,1586.0,13788.0,426.0,886.0,4279.0,299.0,1191.0,546.0,15.4,2.1,4.2,1.0,29372.0,2306.0,11.3,1.3,14.6,0.1,24.2,0.1,19.3,1.3,7.5,1.5,25.0,0.1,0.8,0.4,3.8,1.3,18.4,2.0,1.4,0.7,5.6,1.3,1.0,0.3,0.5401,0.2745,0.2860,0.4397,1.5403,0.3631,0.1850,0.7529,0.7905,0.3792,2.1076,0.5810,0.6336,0.5113,1.1449,0.5947,0.6017,0.7408,0.2964,0.4846,0.1525,2.2760,0.3741,7.0688,0.4354,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3875.0,7.1,0.9,37301.0,1.0,36.0,0.0,29.0,29.0,0.0,30.0,14.0,0.0,0.0,21.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,25.0,25.0,1.0,NaN,30.0,0.0,0.0,21.0,0.0,21.0,0.0,30.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,15.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,15.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,25.0,0.0,0.0,0.0,0.0,0.0,26.0,0.0,0.0,27.0,33.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,36.0,36.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,30.0,0.0,0.0,0.0,0.0,0.0,33.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,275.0,875.0,14.0,14.0,14.0,0.0,0.0,0.0,7.0,250.0,175.0,0.0,0.0,0.0,0.0,2340.0,2.0,780.0,0.0,NaN,8000.0,0.65,6.8,250.77,3.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,3.0,1.0,1.0,0.0,0.0,0.0,29.0,0.0,0.0,0.0,93.24,4887871.0,52420.0,3261.0,5.6,16.8,43.1,54352.0,100.7,1.0,1.0,0.0,1.0,0.0,0.0,0.0,44133.0,21.0,0.0,0.0,0.0,0.0,7.25,7.25,7.25,7.25,7.25,7.25,7.25,7.25,2.13,7.25,0.0,144.0,NaN,11.0,NaN,594.0,594.0,364.0,41.0,247.0,NaN,33318.0,1272.0,NaN,NaN,NaN,148.0,NaN,4530.0,4530.0,185.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,37848.0,1457.0,NaN,NaN,NaN,NaN,37848.0,1457.0,NaN,0.0,0.050,0.0,0.0,4.0,0.0,0.0,0.0,0.0,0.053232,0.0,0.0,0.005078,0.0,0.000000,0.457294,0.044516,0.017216,0.0,0.005078,0.008237,0.0,0.000000,0.0,0.0,0.158909,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.240098,0.0,0.010343,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.030824,1.0

In [7]:
case_number_columns = ["fips","date","county","state","days_from_start","log_rolled_cases", "shifted_days_from_start"]
early_data_case_numbers = early_data[case_number_columns]
X_time_invariant = hhs_X_w_clusters[list(set(early_data.columns).intersection(hhs_X_w_clusters.columns))]
X_time_invariant = X_time_invariant.drop(columns=["county","state"])

In [10]:
WYX = pd.merge(early_data_case_numbers, X_time_invariant, on="fips")
WYX

,fips,date,county,state,days_from_start,log_rolled_cases,shifted_days_from_start,EPL_MOBILE,F_DISABL,RPL_THEME3,Proof_of_residency_requirement_for_vaccination,Reinstated_work_search_requirement_for_UI,Different_Minimum_Wage_for_Smaller_Businesses,F_GROUPQ,Expanded_eligibility_of_unemployment_insurance_to_those_who_have_lost_childcare/school_closures,Were_there_casino(s)_in_State?_(Land_and_Non-Land_based),Waived_all_copays_during_pandemic_for_incarcerated_individuals,F_AGE17,MP_LIMENG,EP_NOHSDP,EP_MUNIT,E_CROWD,Vaccine_allocation_phase:_Healthcare_Service_Workers,RPL_THEME2,MP_MUNIT,Paid_sick_leave_prior_to_pandemic,F_CROWD,hhs_region,E_PCI,Adults_ages_65+_prioritized_ahead_of_essential_workers,F_POV,EP_MOBILE,Taxable_Wage_Amount,Vaccine_allocation_phase:_Frontline_Healthcare_Workers,Require_earnings_in_the_last_two_calendar_quarters_of_the_base_period_in_order_to_qualify_for_UI,Report_Indigenous_COVID-19_testing,Air_or_ventilation_standards,F_MINRTY,Waived_work_search_requirement_for_unemployment_insurance,Vaccine_allocation_phase:_Frontline_Essential_Workers,EPL_PCI,Vaccine_allocation_phase:_Correctional_Staff,Branch_of_government_implementing_COVID-19_liability_rules,EPL_MINRTY,Minimum_total_earnings_required_in_the_base_period_to_qualify_for_UI,MP_AGE17,Vaccine_allocation_phase:_Adults_w/_High-Risk_Medical_Conditions,Proof_of_work_eligibility_requirement_for_vaccination,Proof_of_age_eligibility_requirement_for_vaccination,MP_UNEMP,Firearm_sellers_remained_open,EP_UNINSUR,EP_AGE17,Total_Unemployment_Rate_at_Extended_Benefits_program_shutoff,F_LIMENG,Closed_businesses_overnight,Mention_of_tribal_casinos,MP_AGE65,SPL_THEMES,Report_COVID-19_cases_by_race/ethnicity,Oct_1_2019_Minimum_Wage,COVID-19_anti-retaliation_rules,Number_Homeless_(2019),RPL_THEME1,Reinstated_one_week_waiting_period_for_unemployment_insurance,"Mental_health_professionals_per_100,000_population_in_2019",Vaccine_allocation_phase:_Additional_Healthcare_Workers,Vaccine_allocation_phase:_Adults_Ages_65+,Extended_the_amount_of_time_an_individual_can_be_on_unemployment_insurance,EPL_MUNIT,Vaccine_allocation_phase:_Long-term_Care_Residents,Aerosol_transmissable_diseases_standards,Report_COVID-19_vaccinations_by_race/ethnicity,Report_Indigenous_COVID-19_vaccinations,EP_UNEMP,COVID-19_liability_protections_for_healthcare_providers,Penalty_for_failure_to_comply_with_vaccine_distribution_requirements,F_TOTAL,Vaccine_allocation_phase:_EMS_Providers,Made_Effort_to_Limit_Abortion_Access,EP_GROUPQ,Vaccine_allocation_phase:_Adults_Ages_75+,Vaccine_allocation_phase:_Higher_Education_Employees,Last_date_of_receipt_of_mail-in_ballot_request_for_the_general_election_(by_mail_or_online),F_THEME1,Percent_at_risk_for_serious_illness_due_to_COVID,Cannabis_dispensaries_considered_essential_business,Percent_Unemployed_(2018),MP_CROWD,EPL_CROWD,MP_PCI,Suspend_CHIP_premium_non-payment_lock-outs,EP_SNGPNT,MP_MOBILE,SPL_THEME3,RPL_THEME4,Religious_gatherings_exempt_without_clear_social_distance_mandate*,COVID-19_business_liability_protections,E_UNEMP,SPL_THEME2,E_MUNIT,Total_Unemployment_Rate_relative_to_prior_year_(%),Vaccine_allocation_phase:_Home_Healthcare_Workers,Minimum_Tax_Rate_(%),OSHA-approved_state_plan,MP_GROUPQ,MP_UNINSUR,SPL_THEME4,Report_Indigenous_COVID-19_cases,F_SNGPNT,State_FIPS_Code,F_MOBILE,Vaccine_allocation_phase:_Grocery_Store_Workers,EPL_SNGPNT,F_THEME3,"Automatic_applications_sent_for_mail-in_ballots_in_response_to_COVID-19_(0,1,2_2_being_conditional-_see_notes_for_details)",Report_COVID-19_deaths_by_race/ethnicity,positiveScore,Vaccine_allocation_phase:_Additional_Essential_Workers,EP_AGE65,"Occupational_injuries,_illnesses,_and_fatalities_reporting_prior_to_pandemic",EP_DISABL,Face_mask_mandate_enforced_by_criminal_charge/citation,E_SNGPNT,Vaccine_allocation_phase:_Firefighters,Liquor_stores_remained_open,MP_MINRTY,Expanded_eligibility_to_high-risk_individuals_in_preventative_quarantine,Data_reporting_required_for_medical_treatment,Expanded_scope_of_practice_of_certain_health_providers_to_administer_vaccines,MP_POV,MP_NOVEH,Expanded_eligibility_of_unemployment_insurance_to_anyone_who_is_quarantined_and/or_taking_care_of_someone_who_is_quarantined,Population_density_per_square_miles,F_NOHSDP,F_NOVEH,MP_DISABL,Initially_reopen_restaurants_for_outdoor_dining_only,Vaccine_allocation_phase:_Public_Transit_Workers,EPL_UNEMP,F_AGE65,Minimum_number_of_work_days_missed_by_workers_to_require_data_reporting,No_state_unemployment_waiting_period_prior_to_pandemic;_or_date_waiting_period_waived_not_found,Report_COVID-19_testing_by_race/ethnicity,Weekly_unemployment_insurance_maximum_amount_(dollars),Did_not_waive_copays_for_incarcerated_individuals,State_had_CHIP_premium_non-payment_lock-out_period_as_of_January_2019,Jul_1_2019_Minimum_Wage,Average_Benefit_Amount_(August),State_has_at_least_one_Indian/Alaska_Native_reservation,Permanent_mail-in_ballot_system,EPL_LIMENG,Face_mask_mandate_enforced_by_fines,E_NOVEH,EPL_DISABL,MP_SNGPNT,F_PCI,E_GROUPQ,Prioritization_by_race/ethnicity,Number_of_calendar_quarters_with_earnings_in_the_base_period_needed_to_qualify_for_UI,Medicaid_Expansion,LON,SPL_THEME1,No_legal_enforcement_of_face_mask_mandate,Vaccine_allocation_phase:_Food_Supply_Workers,Does_not_charge_copays_for_incarcerated_individuals,RPL_THEMES,MP_NOHSDP,State_department_in_charge_of_enforcing_programs,Total_Unemployment_Rate_relative_to_second_prior_year_(%),EP_PCI,EPL_POV,Report_COVID-19_hospitalizations_by_race,Waived_COVID/respiratory_illness-related_copays_during_pandemic_for_incarcerated_individuals,Paid_sick_leave_expansion_during_pandemic,EPL_AGE17,Maximum_Tax_Rate_(%),EPL_NOVEH,EP_NOVEH,Types_of_workers_eligible_for_workers'_compensation_expansion,Vaccine_allocation_phase:_General_Public,EPL_NOHSDP,Vaccine_allocation_phase:_Law_Enforcement_&_Public_Safety_Personnel,LAT,Vaccine_allocation_phase:_People_who_are_Incarcerated,Vaccine_allocation_phase:_Residents_of_Homeless_Shelters,Mar_29_2019_Minimum_Wage,Minimum_total_earnings_required_outside_the_highest_earning_calendar_quarter_of_the_base_period_to_qualify_for_UI,Report_Indigenous_COVID-19_deaths,COVID-19_workers'_compensation_expansion,Percent_living_under_the_federal_poverty_line_(2018),Vaccine_allocation_phase:_Pre-K-12_School_Employees,"Automatic_mail-in_ballot_system_in_response_to_COVID-19_(0,1,2_2_being_conditional-_see_notes_for_details)",Report_Indigenous_COVID-19_hospitalizations,EP_POV,F_MUNIT,Jan_1_2019_Minimum_Wage,F_THEME2,EP_MINRTY,F_UNEMP,EPL_AGE65,F_THEME4,State_previously_allowed_audio-only_telehealth,EP_CROWD,E_UNINSUR,EPL_GROUPQ,EP_LIMENG
0,1001.0,2020-04-16,Autauga,Alabama,86.0,3.009917,0.0,0.7408,0.0,0.5947,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.4,11.3,3.8,299.0,NaN,0.5810,1.3,0.0,0.0,4.0,29372.0,0.0,0.0,18.4,8000.0,NaN,0.0,0.0,0.0,0.0,1.0,NaN,0.2860,NaN,1.0,0.6336,2340.0,0.1,NaN,1.0,1.0,1.0,1.0,7.1,24.2,7.0,0.0,0.0,0.0,0.1,7.0688,1.0,7.25,0.0,3261.0,0.3631,1.0,100.7,NaN,NaN,0.0,0.6017,NaN,0.0,1.0,1.0,4.2,1.0,1.0,0.0,NaN,1.0,1.0,NaN,NaN,44133.0,0.0,43.1,NaN,5.6,0.7,0.2964,2306.0,0.0,7.5,2.0,1.1449,0.3741,0.0,1.0,1065.0,2.1076,886.0,250.0,NaN,0.65,3.0,0.3,0.9,2.2760,0.0,0.0,1.0,0.0,NaN,0.3792,0.0,0.0,1.0,0.0,NaN,14.6,1.0,19.3,0.0,1586.0,NaN,1.0,0.1,0.0,0.0,0.0,2.1,1.3,1.0,93.24,0.0,0.0,1.3,0.0,NaN,0.2745,0.0,3.0,0.0,0.0,275.0,0.0,0.0,7.25,250.77,1.0,0.0,0.5113,0.0,1191.0,0.7905,1.5,0.0,546.0,0.0,2.0,0.0,-86.64644,1.5403,1.0,NaN,0.0,0.4354,1.3,0.0,175.0,29372.0,0.5401,0.0,0.0,0.0,0.7529,6.8,0.4846,5.6,0.0,2.0,0.4397,NaN,32.532237,NaN,NaN,7.25,780.0,0.0,0.0,16.8,NaN,0.0,0.0,15.4,0.0,7.25,0.0,25.0,0.0,0.1850,0.0,0.0,1.4,3875.0,0.1525,0.8
1,1001.0,2020-04-17,Autauga,Alabama,87.0,3.030824,1.0,0.7408,0.0,0.5947,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.4,11.3,3.8,299.0,NaN,0.5810,1.3,0.0,0.0,4.0,29372.0,0.0,0.0,18.4,8000.0,NaN,0.0,0.0,0.0,0.0,1.0,NaN,0.2860,NaN,1.0,0.6336,2340.0,0.1,NaN,1.0,1.0,1.0,1.0,7.1,24.2,7.0,0.0,0.0,0.0,0.1,7.0688,1.0,7.25,0.0,3261.0,0.3631,1.0,100.7,NaN,NaN,0.0,0.6017,NaN,0.0,1.0,1.0,4.2,1.0,1.0,0.0,NaN,1.0,1.0,NaN,NaN,44133.0,0.0,43.1,NaN,5.6,0.7,0.2964,2306.0,0.0,7.5,2.0,1.1449,0.3741,0.0,1.0,1065.0,2.1076,886.0,250.0,NaN,0.65,3.0,0.3,0.9,2.2760,0.0,0.0,1.0,0.0,NaN,0.3792,0.0,0.0,1.0,0.0,NaN,14.6,1.0,19.3,0.0,1586.0,NaN,1.0,0.1,0.0,0.0,0.0,2.1,1.3,1.0,93.24,0.0,0.0,1.3,0.0,NaN,0.2745,0.0,3.0,0.0,0.0,275.0,0.0,0.0,7.25,250.77,1.0,0.0,0.5113,0.0,1191.0,0.7905,1.5,0.0,546.0,0.0,2.0,0.0,-86.64644,1.5403,1.0,NaN,0.0,0.4354,1.3,0.0,175.0,29372.0,0.5401,0.0,0.0,0.0,0.7529,6.8,0.4846,5.6,0.0,2.0,0.4397,NaN,32.532237,NaN,NaN,7.25,780.0,0.0,0.0,16.8,NaN,0.0,0.0,15.4,0.0,7.25,0.0,25.0,0.0,0.1850,0.0,0.0,1.4,3875.0,0.1525,0.8
2,1001.0,2020-04-18,Autauga,Alabama,88.0,3.030824,2.0,0.7408,0.0,0.5947,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.4,11.3,3.8,299.0,NaN,0.5810,1.3,0.0,0.0,4.0,29372.0,0.0,0.0,18.4,8000.0,NaN,0.0,0.0,0.0,0.0,1.0,NaN,0.2860,NaN,1.0,0.6336,2340.0,0.1,NaN,1.0,1.0,1.0,1.0,7.1,24.2,7.0,0.0,0.0,0.0,0.1,7.0688,1.0,7.25,0.0,3261.0,0.3631,1.0,100.7,NaN,NaN,0.0,0.6017,NaN,0.0,1.0,1.0,4.2,1.0,1.0,0.0,NaN,1.0,1.0,NaN,NaN,44133.0,0.0,43.1,NaN,5.6,0.7,0.2964,2306.0,0.0,7.5,2.0,1.1449,0.3741,0.0,1.0,1065.0,2.1076,886.0,250.0,NaN,0.65,3.0,0.3,0.9,2.2760,0.0,0.0,1.0,0.0,NaN,0.3792,0.0,0.0,1.0,0.0,NaN,14.6,1.0,19.3,0.0,1586.0,NaN,1.0,0.1,0.0,0.0,0.0,2.1,1.3,1.0,93.24,0.0,0.0,1.3,0.0,NaN,0.2745,0.0,3.0,0.0,0.0,275.0,0.0,0.0,7.25,250.77,1.0,0.0,0.5113,0.0,1191.0,0.7905,1.5,0.0,546.0,0.0,2.0,0.0,-86.64644,1.5403,1.0,NaN,0.0,0.4354,1.3,0.0,175.0,29372.0,0.5401,0.0,0.0,0.0,0.7529,6.8,0.4846,5.6,0.0,2.0,0.4397,NaN,32.532237,NaN,NaN,7.25,780.0,0.0,0.0,16.8,NaN,0.0,0.0,15.4,0.0,7.25,0.0,25.0,0.0,0.1850,0.0,0.0,1.4,3875.0,0.1525,0.8
3,1001.0,2020-04-19,Autauga,Alabama,89.0,3.044522,3.0,0.7408,0.0,0.5947,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.4,11.3,3.8,299.0,NaN,0.5810,1.3,0.0,0.0,4.0,29372.0,0.0,0.0,18.4,8000.0,NaN,0.0,0.0,0.0,0.0,1.0,NaN,0.2860,NaN,1.0,0.6336,2340.0,0.1,NaN,1.0,1.0,1.0,1.0,7.1,24.2,7.0,0.0,0.0,0.0,0.1,7.0688,1.0,7.25,0.0,3261.0,0.3631,1.0,100.7,NaN,NaN,0.0,0.6017,NaN,0.0,1.0,1.0,4.2,1.0,1.0,0.0,NaN,1.0,1.0,NaN,NaN,44133.0,0.0,43.1,NaN,5.6,0.7,0.2964,2306.0,0.0,7.5,2.0,1.1449,0.3741,0.0,1.0,1065.0,2.1076,886.0,250.0,NaN,0.65,3.0,0.3,0.9,2.2760,0.0,0.0,1.0,0.0,NaN,0.3792,0.0,0.0,1.0,0.0,NaN,14.6,1.0,19.3,0.0,1586.0,NaN,1.0,0.1,0.0,0.0,0.0,2.1,1.3,1.0,93.24,0.0,0.0,1.3,0.0,NaN,0.2745,0.0,3.0,0.0,0.0,275.0,0.0,0.0,7.25,250.77,1.0,0.0,0.5113,0.0,1191.0,0.7905,1.5,0.0,546.0,0.0,2.0,0.0,-86.64644,1.5403,1.0,NaN,0.0,0.4354,1.3,0.0,175.0,29372.0,0.5401,0.0,0.0,0.0,0.7529,6.8,0.4846,5.6,0.0,2.0,0.4397,NaN,32.532237,NaN,NaN,7.25,780.0,0.0,0.0,16.8,NaN,0.0,0.0,15.4,0.0,7.25,0.0,25.0,0.0,0.1850,0.0,0.0,1.4,3875.0,0.1525,0.8
4,1001.0,2020-04-20,Autauga,Alabama,90.0,3.064725,4.0,0.7408,0.0,0.5947,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.4,11.3,3.8,299.0,NaN,0.5810,1.3,0.0,0.0,4.0,29372.0,0.0,0.0,18.4,8000.0,NaN,0.0,0.0,0.0,0.0,1.0,NaN,0.2860,NaN,1.0,0.6336,2340.0,0.1,NaN,1.0,1.0,1.0,1.0,7.1,24.2,7.0,0.0,0.0,0.0,0.1,7.0688,1.0,7.25,0.0,3261.0,0.3631,1.0,100.7,NaN,NaN,0.0,0.6017,NaN,0.0,1.0,1.0,4.2,1.0,1.0,0.0,NaN,1.0,1.0,NaN,NaN,44133.0,0.0,43.1,NaN,5.6,0.7,0.2964,2306.0,0.0,7.5,2.0,1.1449,0.3741,0.0,1.0,1065.0,2.1076,886.0,250.0,NaN,0.65,3.0,0.3,0.9,2.2760,0.0,0.0,1.0,0.0,NaN,0.3792,0.0,0.0,1.0,0.0,NaN,14.6,1.0,19.3,0.0,1586.0,NaN,1.0,0.1,0.0,0.0,0.0,2.1,1.3,1.0,93.24,0.0,0.0,1.3,0.0,NaN,0.2745,0.0,3.0,0.0,0.0,275.0,0.0,0.0,7.25,250.77,1.0,0.0,0.5113,0.0,1191.0,0.7905,1.5,0.0,546.0,0.0,2.0,0.0,-86.64644,1.5403,1.0,NaN,0.0,0.4354,1.3,0.0,175.0,29372.0,0.5401,0.0,0.0,0.0,0.7529,6.8,0.4846,5.6,0.0,2.0,0.4397,NaN,32.532237,NaN,NaN,7.25,780.0,0.0,0.0,16.8,NaN,0.0,0.0,15.4,0.0,7.25,0.0,25.0,0.0,0.1850,0.0,0.0,1.4,3875.0,0.1525,0.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
445972,99999.0,2020-11-12,New York City,New York,296.0,9.819632,246.0,0.0022,0.0,0.9799,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.2,18.4,40.9,61715.0,NaN,0.0697,0.4,0.0,1.0,2.0,31984.0,0.0,0.0,0.1,11600.0,NaN,0.0,0.0,0.0,1.0,0.0,2.0,0.1736,NaN,1.0,0.9430,3900.0,0.0,2.0,1.0,1.0,0.2,0.0,8.2,22.0,NaN,1.0,44148.0,1.0,0.1,8.1240,0.0,11.10,1.0,92091.0,0.5223,0.0,291.1,NaN,NaN,0.0,0.9981,NaN,1.0,1.0,0.0,6.2,1.0,1.0,5.0,NaN,0.0,1.6,NaN,NaN,44131.0,0.0,36.9,1.0,5.0,0.3,0.9863,267.0,0.0,7.8,0.1,1.9277,0.9096,1.0,0.0,70250.0,1.1980,358674.0,NaN,NaN,0.00,2.0,0.1,0.2,3.3665,0.0,0.0,36.0,0.0,NaN,0.4330,2.0,2.0,1.0,0.0,2.0,14.8,1.0,10.2,0.0,60827.0,NaN,1.0,0.0,0.0,1.0,1.0,0.4,0.4,0.0,358.21,0.0,1.0,0.2,1.0,NaN,0.6207,0.0,1.0,0.0,0.0,504.0,0.0,0.0,11.10,333.83,1.0,0.0,0.9847,1.0,292462.0,0.0755,0.2,0.0,40893.0,0.0,2.0,1.0,-73.95064,2.0319,0.0,2.0,1.0,0.6201,0.3,1.0,NaN,31984.0,0.6258,0.0,0.0,1.0,0.4502,6.9,0.9981,55.8,0.0,2.0,0.7883,NaN,40.658566,NaN,NaN,11.10,1300.0,0.0,0.0,13.6,NaN,0.0,0.0,16.6,1.0,11.10,0.0,63.8,0.0,0.1974,3.0,0.0,9.5,136920.0,0.3792,12.0
445973,99999.0,2020-11-13,New York City,New York,297.0,9.863997,247.0,0.0022,0.0,0.9799,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.2,18.4,40.9,61715.0,NaN,0.0697,0.4,0.0,1.0,2.0,31984.0,0.0,0.0,0.1,11600.0,NaN,0.0,0.0,0.0,1.0,0.0,2.0,0.1736,NaN,1.0,0.9430,3900.0,0.0,2.0,1.0,1.0,0.2,0.0,8.2,22.0,NaN,1.0,44148.0,1.0,0.1,8.1240,0.0,11.10,1.0,92091.0,0.5223,0.0,291.1,NaN,NaN,0.0,0.9981,NaN,1.0,1.0,0.0,6.2,1.0,1.0,5.0,NaN,0.0,1.6,NaN,NaN,44131.0,0.0,36.9,1.0,5.0,0.3,0.9863,267.0,0.0,7.8,0.1,1.9277,0.9096,1.0,0.0,70250.0,1.1980,358674.0,NaN,NaN,0.00,2.0,0.1,0.2,3.3665,0.0,0.0,36.0,0.0,NaN,0.4330,2.0,2.0,1.0,0.0,2.0,14.8,1.0,10.2,0.0,60827.0,NaN,1.0,0.0,0.0,1.0,1.0,0.4,0.4,0.0,358.21,0.0,1.0,0.2,1.0,NaN,0.6207,0.0,1.0,0.0,0.0,504.0,0.0,0.0,11.10,333.83,1.0,0.0,0.9847,1.0,292462.0,0.0755,0.2,0.0,40893.0,0.0,2.0,1.0,-73.95064,2.0319,0.0,2.0,1.0,0.6201,0.3,1.0,NaN,31984.0,0.6258,0.0,0.0,1.0,0.4502,6.9,0.9981,55.8,0.0,2.0,0.7883,NaN,40.658566,NaN,NaN,11.10,1300.0,0.0,0.0,13.6,NaN,0.0,0.0,16.6,1.0,11.10,0.0,63.8,0.0,0.1974,3.0,0.0,9.5,136920.0,0.3792,12.0
445974,99999.0,2020-11-14,New York City,New York,298.0,9.911597,248.0,0.0022,0.0,0.9799,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.2,18.4,40.9,61715.0,NaN,0.0697,0.4,0.0,1.0,2.0,31984.0,0.0,0.0,0.1,11600.0,NaN,0.0,0.0,0.0,1.0,0.0,2.0,0.1736,NaN,1.0,0.9430,3900.0,0.0,2.0,1.0,1.0,0.2,0.0,8.2,22.0,NaN,1.0,44148.0,1.0,0.1,8.1240,0.0,11.10,1.0,92091.0,0.5223,0.0,291.1,NaN,NaN,0.0,0.9981,NaN,1.0,1.0,0.0,6.2,1.0,1.0,5.0,NaN,0.0,1.6,NaN,NaN,44131.0,0.0,36.9,1.0,5.0,0.3,0.9863,267.0,0.0,7.8,0.1,1.9277,0.9096,1.0,0.0,70250.0,1.1980,358674.0,NaN,NaN,0.00,2.0,0.1,0.2,3.3665,0.0,0.0,36.0,0.0,NaN,0.4330,2.0,2.0,1.0,0.0,2.0,14.8,1.0,10.2,0.0,60827.0,NaN,1.0,0.0,0.0,1.0,1.0,0.4,0.4,0.0,358.21,0.0,1.0,0.2,1.0,NaN,0.6207,0.0,1.0,0.0,0.0,504.0,0.0,0.0,11.10,333.83,1.0,0.0,0.9847,1.0,292462.0,0.0755,0.2,0.0,40893.0,0.0,2.0,1.0,-73.95064,2.0319,0.0,2.0,1.0,0.6201,0.3,1.0,NaN,31984.0,0.6258,0.0,0.0,1.0,0.4502,6.9,0.9981,55.8,0.0,2.0,0.7883,NaN,40.658566,NaN,NaN,11.10,1300.0,0.0,0.0,13.6,NaN,0.0,0.0,16.6,1.0,11.10,0.0,63.8,0.0,0.1974,3.0,0.0,9.5,136920.0,0.3792,12.0
445975,99999.0,2020-11-15,New York City,New York,299.0,9.957827,249.0,0.0022,0.0,0.9799,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.2,18.4,40.9,61715.0,NaN,0.0697,0.4,0.0,1.0,2.0,31984.0,0.0,0.0,0.1,11600.0,NaN,0.0,0.0,0.0,1.0,0.0,2.0,0.1736,NaN,1.0,0.9430,3900.0,0.0,2.0,1.0,1.0,0.2,0.0,8.2,22.0,NaN,1.0,44148.0,1.0,0.1,8.1240,0.0,11.10,1.0,92091.0,0.5223,0.0,291.1,NaN,NaN,0.0,0.9981,NaN,1.0,1.0,0.0,6.2,1.0,1.0,5.0,NaN,0.0,1.6,NaN,NaN,44131.0,0.0,36.9,1.0,5.0,0.3,0.9863,267.0,0.0,7.8,0.1,1.9277,0.9096,1.0,0.0,70250.0,1.1980,358674.0,NaN,NaN,0.00,2.0,0.1,0.2,3.3665,0.0,0.0,36.0,0.0,NaN,0.4330,2.0,2.0,1.0,0.0,2.0,14.8,1.0,10.2,0.0,60827.0,NaN,1.0,0.0,0.0,1.0,1.0,0.4,0.4,0.0,358.21,0.0,1.0,0.2,1.0,NaN,0.6207,0.0,1.0,0.0,0.0,504.0,0.0,0.0,11.10,333.83,1.0,0.0,0.9847,1.0,292462.0,0.0755,0.2,0.0,40893.0,0.0,2.0,1.0,-73.95064,2.0319,0.0,2.0,1.0,0.6201,0.3,1.0,NaN,31984.0,0.6258,0.0,0.0,1.0,0.4502,6.9,0.9981,55.8,0.0,2.0,0.7883,NaN,40.658566,NaN,NaN,11.10,1300.0,0.0,0.0,13.6,NaN,0.0,0.0,16.6,1.0,11.10,0.0,63.8,0.0,0.1974,3.0,0.0,9.5,136920.0,0.3792,12.0
445976,99999.0,2020-11-16,New York City,New York,300.0,10.002596,250.0,0.0022,0.0,0.9799,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.2,18.4,40.9,61715.0,NaN,0.0697,0.4,0.0,1.0,2.0,31984.0,0.0,0.0,0.1,11600.0,NaN,0.0,0.0,0.0,1.0,0.0,2.0,0.1736,NaN,1.0,0.9430,3900.0,0.0,2.0,1.0,1.0,0.2,0.0,8.2,22.0,NaN,1.0,44148.0,1.0,0.1,8.1240,0.0,11.10,1.0,92091.0,0.5223,0.0,291.1,NaN,NaN,0.0,0.9981,NaN,1.0,1.0,0.0,6.2,1.0,1.0,5.0,NaN,0.0,1.6,NaN,NaN,44131.0,0.0,36.9,1.0,5.0,0.3,0.9863,267.0,0.0,7.8,0.1,1.9277,0.9096,1.0,0.0,70250.0,1.1980,358674.0,NaN,NaN,0.00,2.0,0.1,0.2,3.3665,0.0,0.0,36.0,0.0,NaN,0.4330,2.0,2.0,1.0,0.0,2.0,14.8,1.0,10.2,0.0,60827.0,NaN,1.0,0.0,0.0,1.0,1.0,0.4,0.4,0.0,358.21,0.0,1.0,0.2,1.0,NaN,0.6207,0.0,1.0,0.0,0.0,504.0,0.0,0.0,11.10,333.83,1.0,0.0,0.9847,1.0,292462.0,0.0755,0.2,0.0,40893.0,0.0,2.0,1.0,-73.95064,2.0319,0.0,2.0,1.0,0.6201,0.3,1.0,NaN,31984.0,0.6258,0.0,0.0,1.0,0.4502,6.9,0.9981,55.8,0.0,2.0,0.7883,NaN,40.658566,NaN,NaN,11.10,1300.0,0.0,0.0,13.6,NaN,0.0,0.0,16.6,1.0,11.10,0.0,63.8,0.0,0.1974,3.0,0.0,9.5,136920.0,0.3792,12.0

In [11]:
Y = WYX["log_rolled_cases"]
W = WYX["shifted_days_from_start"]

X = WYX[WYX.columns.difference(case_number_columns)]

In [12]:
X

,Adults_ages_65+_prioritized_ahead_of_essential_workers,Aerosol_transmissable_diseases_standards,Air_or_ventilation_standards,"Automatic_applications_sent_for_mail-in_ballots_in_response_to_COVID-19_(0,1,2_2_being_conditional-_see_notes_for_details)","Automatic_mail-in_ballot_system_in_response_to_COVID-19_(0,1,2_2_being_conditional-_see_notes_for_details)",Average_Benefit_Amount_(August),Branch_of_government_implementing_COVID-19_liability_rules,COVID-19_anti-retaliation_rules,COVID-19_business_liability_protections,COVID-19_liability_protections_for_healthcare_providers,COVID-19_workers'_compensation_expansion,Cannabis_dispensaries_considered_essential_business,Closed_businesses_overnight,Data_reporting_required_for_medical_treatment,Did_not_waive_copays_for_incarcerated_individuals,Different_Minimum_Wage_for_Smaller_Businesses,Does_not_charge_copays_for_incarcerated_individuals,EPL_AGE17,EPL_AGE65,EPL_CROWD,EPL_DISABL,EPL_GROUPQ,EPL_LIMENG,EPL_MINRTY,EPL_MOBILE,EPL_MUNIT,EPL_NOHSDP,EPL_NOVEH,EPL_PCI,EPL_POV,EPL_SNGPNT,EPL_UNEMP,EP_AGE17,EP_AGE65,EP_CROWD,EP_DISABL,EP_GROUPQ,EP_LIMENG,EP_MINRTY,EP_MOBILE,EP_MUNIT,EP_NOHSDP,EP_NOVEH,EP_PCI,EP_POV,EP_SNGPNT,EP_UNEMP,EP_UNINSUR,E_CROWD,E_GROUPQ,E_MUNIT,E_NOVEH,E_PCI,E_SNGPNT,E_UNEMP,E_UNINSUR,Expanded_eligibility_of_unemployment_insurance_to_anyone_who_is_quarantined_and/or_taking_care_of_someone_who_is_quarantined,Expanded_eligibility_of_unemployment_insurance_to_those_who_have_lost_childcare/school_closures,Expanded_eligibility_to_high-risk_individuals_in_preventative_quarantine,Expanded_scope_of_practice_of_certain_health_providers_to_administer_vaccines,Extended_the_amount_of_time_an_individual_can_be_on_unemployment_insurance,F_AGE17,F_AGE65,F_CROWD,F_DISABL,F_GROUPQ,F_LIMENG,F_MINRTY,F_MOBILE,F_MUNIT,F_NOHSDP,F_NOVEH,F_PCI,F_POV,F_SNGPNT,F_THEME1,F_THEME2,F_THEME3,F_THEME4,F_TOTAL,F_UNEMP,Face_mask_mandate_enforced_by_criminal_charge/citation,Face_mask_mandate_enforced_by_fines,Firearm_sellers_remained_open,Initially_reopen_restaurants_for_outdoor_dining_only,Jan_1_2019_Minimum_Wage,Jul_1_2019_Minimum_Wage,LAT,LON,Last_date_of_receipt_of_mail-in_ballot_request_for_the_general_election_(by_mail_or_online),Liquor_stores_remained_open,MP_AGE17,MP_AGE65,MP_CROWD,MP_DISABL,MP_GROUPQ,MP_LIMENG,MP_MINRTY,MP_MOBILE,MP_MUNIT,MP_NOHSDP,MP_NOVEH,MP_PCI,MP_POV,MP_SNGPNT,MP_UNEMP,MP_UNINSUR,Made_Effort_to_Limit_Abortion_Access,Mar_29_2019_Minimum_Wage,Maximum_Tax_Rate_(%),Medicaid_Expansion,"Mental_health_professionals_per_100,000_population_in_2019",Mention_of_tribal_casinos,Minimum_Tax_Rate_(%),Minimum_number_of_work_days_missed_by_workers_to_require_data_reporting,Minimum_total_earnings_required_in_the_base_period_to_qualify_for_UI,Minimum_total_earnings_required_outside_the_highest_earning_calendar_quarter_of_the_base_period_to_qualify_for_UI,No_legal_enforcement_of_face_mask_mandate,No_state_unemployment_waiting_period_prior_to_pandemic;_or_date_waiting_period_waived_not_found,Number_Homeless_(2019),Number_of_calendar_quarters_with_earnings_in_the_base_period_needed_to_qualify_for_UI,OSHA-approved_state_plan,"Occupational_injuries,_illnesses,_and_fatalities_reporting_prior_to_pandemic",Oct_1_2019_Minimum_Wage,Paid_sick_leave_expansion_during_pandemic,Paid_sick_leave_prior_to_pandemic,Penalty_for_failure_to_comply_with_vaccine_distribution_requirements,Percent_Unemployed_(2018),Percent_at_risk_for_serious_illness_due_to_COVID,Percent_living_under_the_federal_poverty_line_(2018),Permanent_mail-in_ballot_system,Population_density_per_square_miles,Prioritization_by_race/ethnicity,Proof_of_age_eligibility_requirement_for_vaccination,Proof_of_residency_requirement_for_vaccination,Proof_of_work_eligibility_requirement_for_vaccination,RPL_THEME1,RPL_THEME2,RPL_THEME3,RPL_THEME4,RPL_THEMES,Reinstated_one_week_waiting_period_for_unemployment_insurance,Reinstated_work_search_requirement_for_UI,Religious_gatherings_exempt_without_clear_social_distance_mandate*,Report_COVID-19_cases_by_race/ethnicity,Report_COVID-19_deaths_by_race/ethnicity,Report_COVID-19_hospitalizations_by_race,Report_COVID-19_testing_by_race/ethnicity,Report_COVID-19_vaccinations_by_race/ethnicity,Report_Indigenous_COVID-19_cases,Report_Indigenous_COVID-19_deaths,Report_Indigenous_COVID-19_hospitalizations,Report_Indigenous_COVID-19_testing,Report_Indigenous_COVID-19_vaccinations,Require_earnings_in_the_last_two_calendar_quarters_of_the_base_period_in_order_to_qualify_for_UI,SPL_THEME1,SPL_THEME2,SPL_THEME3,SPL_THEME4,SPL_THEMES,State_FIPS_Code,State_department_in_charge_of_enforcing_programs,State_had_CHIP_premium_non-payment_lock-out_period_as_of_January_2019,State_has_at_least_one_Indian/Alaska_Native_reservation,State_previously_allowed_audio-only_telehealth,Suspend_CHIP_premium_non-payment_lock-outs,Taxable_Wage_Amount,Total_Unemployment_Rate_at_Extended_Benefits_program_shutoff,Total_Unemployment_Rate_relative_to_prior_year_(%),Total_Unemployment_Rate_relative_to_second_prior_year_(%),Types_of_workers_eligible_for_workers'_compensation_expansion,Vaccine_allocation_phase:_Additional_Essential_Workers,Vaccine_allocation_phase:_Additional_Healthcare_Workers,Vaccine_allocation_phase:_Adults_Ages_65+,Vaccine_allocation_phase:_Adults_Ages_75+,Vaccine_allocation_phase:_Adults_w/_High-Risk_Medical_Conditions,Vaccine_allocation_phase:_Correctional_Staff,Vaccine_allocation_phase:_EMS_Providers,Vaccine_allocation_phase:_Firefighters,Vaccine_allocation_phase:_Food_Supply_Workers,Vaccine_allocation_phase:_Frontline_Essential_Workers,Vaccine_allocation_phase:_Frontline_Healthcare_Workers,Vaccine_allocation_phase:_General_Public,Vaccine_allocation_phase:_Grocery_Store_Workers,Vaccine_allocation_phase:_Healthcare_Service_Workers,Vaccine_allocation_phase:_Higher_Education_Employees,Vaccine_allocation_phase:_Home_Healthcare_Workers,Vaccine_allocation_phase:_Law_Enforcement_&_Public_Safety_Personnel,Vaccine_allocation_phase:_Long-term_Care_Residents,Vaccine_allocation_phase:_People_who_are_Incarcerated,Vaccine_allocation_phase:_Pre-K-12_School_Employees,Vaccine_allocation_phase:_Public_Transit_Workers,Vaccine_allocation_phase:_Residents_of_Homeless_Shelters,Waived_COVID/respiratory_illness-related_copays_during_pandemic_for_incarcerated_individuals,Waived_all_copays_during_pandemic_for_incarcerated_individuals,Waived_work_search_requirement_for_unemployment_insurance,Weekly_unemployment_insurance_maximum_amount_(dollars),Were_there_casino(s)_in_State?_(Land_and_Non-Land_based),hhs_region,positiveScore
0,0.0,0.0,0.0,0.0,0.0,250.77,1.0,0.0,1.0,1.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.7529,0.1850,0.2964,0.7905,0.1525,0.5113,0.6336,0.7408,0.6017,0.4397,0.4846,0.2860,0.5401,0.3792,0.2745,24.2,14.6,1.4,19.3,1.0,0.8,25.0,18.4,3.8,11.3,5.6,29372.0,15.4,7.5,4.2,7.1,299.0,546.0,886.0,1191.0,29372.0,1586.0,1065.0,3875.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,7.25,7.25,32.532237,-86.64644,44133.0,1.0,0.1,0.1,0.7,1.3,0.3,0.4,0.1,2.0,1.3,1.3,1.3,2306.0,2.1,1.5,1.0,0.9,1.0,7.25,6.8,0.0,100.7,0.0,0.65,3.0,2340.0,780.0,1.0,0.0,3261.0,2.0,3.0,1.0,7.25,0.0,0.0,1.0,5.6,43.1,16.8,0.0,93.24,0.0,1.0,0.0,1.0,0.3631,0.5810,0.5947,0.3741,0.4354,1.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.5403,2.1076,1.1449,2.2760,7.0688,1.0,0.0,0.0,1.0,0.0,0.0,8000.0,7.0,250.0,175.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,1.0,275.0,1.0,4.0,0.0
1,0.0,0.0,0.0,0.0,0.0,250.77,1.0,0.0,1.0,1.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.7529,0.1850,0.2964,0.7905,0.1525,0.5113,0.6336,0.7408,0.6017,0.4397,0.4846,0.2860,0.5401,0.3792,0.2745,24.2,14.6,1.4,19.3,1.0,0.8,25.0,18.4,3.8,11.3,5.6,29372.0,15.4,7.5,4.2,7.1,299.0,546.0,886.0,1191.0,29372.0,1586.0,1065.0,3875.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,7.25,7.25,32.532237,-86.64644,44133.0,1.0,0.1,0.1,0.7,1.3,0.3,0.4,0.1,2.0,1.3,1.3,1.3,2306.0,2.1,1.5,1.0,0.9,1.0,7.25,6.8,0.0,100.7,0.0,0.65,3.0,2340.0,780.0,1.0,0.0,3261.0,2.0,3.0,1.0,7.25,0.0,0.0,1.0,5.6,43.1,16.8,0.0,93.24,0.0,1.0,0.0,1.0,0.3631,0.5810,0.5947,0.3741,0.4354,1.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.5403,2.1076,1.1449,2.2760,7.0688,1.0,0.0,0.0,1.0,0.0,0.0,8000.0,7.0,250.0,175.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,1.0,275.0,1.0,4.0,0.0
2,0.0,0.0,0.0,0.0,0.0,250.77,1.0,0.0,1.0,1.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.7529,0.1850,0.2964,0.7905,0.1525,0.5113,0.6336,0.7408,0.6017,0.4397,0.4846,0.2860,0.5401,0.3792,0.2745,24.2,14.6,1.4,19.3,1.0,0.8,25.0,18.4,3.8,11.3,5.6,29372.0,15.4,7.5,4.2,7.1,299.0,546.0,886.0,1191.0,29372.0,1586.0,1065.0,3875.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,7.25,7.25,32.532237,-86.64644,44133.0,1.0,0.1,0.1,0.7,1.3,0.3,0.4,0.1,2.0,1.3,1.3,1.3,2306.0,2.1,1.5,1.0,0.9,1.0,7.25,6.8,0.0,100.7,0.0,0.65,3.0,2340.0,780.0,1.0,0.0,3261.0,2.0,3.0,1.0,7.25,0.0,0.0,1.0,5.6,43.1,16.8,0.0,93.24,0.0,1.0,0.0,1.0,0.3631,0.5810,0.5947,0.3741,0.4354,1.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.5403,2.1076,1.1449,2.2760,7.0688,1.0,0.0,0.0,1.0,0.0,0.0,8000.0,7.0,250.0,175.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,1.0,275.0,1.0,4.0,0.0
3,0.0,0.0,0.0,0.0,0.0,250.77,1.0,0.0,1.0,1.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.7529,0.1850,0.2964,0.7905,0.1525,0.5113,0.6336,0.7408,0.6017,0.4397,0.4846,0.2860,0.5401,0.3792,0.2745,24.2,14.6,1.4,19.3,1.0,0.8,25.0,18.4,3.8,11.3,5.6,29372.0,15.4,7.5,4.2,7.1,299.0,546.0,886.0,1191.0,29372.0,1586.0,1065.0,3875.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,7.25,7.25,32.532237,-86.64644,44133.0,1.0,0.1,0.1,0.7,1.3,0.3,0.4,0.1,2.0,1.3,1.3,1.3,2306.0,2.1,1.5,1.0,0.9,1.0,7.25,6.8,0.0,100.7,0.0,0.65,3.0,2340.0,780.0,1.0,0.0,3261.0,2.0,3.0,1.0,7.25,0.0,0.0,1.0,5.6,43.1,16.8,0.0,93.24,0.0,1.0,0.0,1.0,0.3631,0.5810,0.5947,0.3741,0.4354,1.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.5403,2.1076,1.1449,2.2760,7.0688,1.0,0.0,0.0,1.0,0.0,0.0,8000.0,7.0,250.0,175.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,1.0,275.0,1.0,4.0,0.0
4,0.0,0.0,0.0,0.0,0.0,250.77,1.0,0.0,1.0,1.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.7529,0.1850,0.2964,0.7905,0.1525,0.5113,0.6336,0.7408,0.6017,0.4397,0.4846,0.2860,0.5401,0.3792,0.2745,24.2,14.6,1.4,19.3,1.0,0.8,25.0,18.4,3.8,11.3,5.6,29372.0,15.4,7.5,4.2,7.1,299.0,546.0,886.0,1191.0,29372.0,1586.0,1065.0,3875.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,7.25,7.25,32.532237,-86.64644,44133.0,1.0,0.1,0.1,0.7,1.3,0.3,0.4,0.1,2.0,1.3,1.3,1.3,2306.0,2.1,1.5,1.0,0.9,1.0,7.25,6.8,0.0,100.7,0.0,0.65,3.0,2340.0,780.0,1.0,0.0,3261.0,2.0,3.0,1.0,7.25,0.0,0.0,1.0,5.6,43.1,16.8,0.0,93.24,0.0,1.0,0.0,1.0,0.3631,0.5810,0.5947,0.3741,0.4354,1.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.5403,2.1076,1.1449,2.2760,7.0688,1.0,0.0,0.0,1.0,0.0,0.0,8000.0,7.0,250.0,175.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,1.0,275.0,1.0,4.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
445972,0.0,1.0,0.0,2.0,0.0,333.83,1.0,1.0,0.0,1.0,0.0,1.0,44148.0,1.0,0.0,0.0,1.0,0.4502,0.1974,0.9863,0.0755,0.3792,0.9847,0.9430,0.0022,0.9981,0.7883,0.9981,0.1736,0.6258,0.4330,0.6207,22.0,14.8,9.5,10.2,1.6,12.0,63.8,0.1,40.9,18.4,55.8,31984.0,16.6,7.8,6.2,8.2,61715.0,40893.0,358674.0,292462.0,31984.0,60827.0,70250.0,136920.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,2.0,3.0,5.0,0.0,0.0,1.0,0.0,1.0,11.10,11.10,40.658566,-73.95064,44131.0,1.0,0.0,0.1,0.3,0.2,0.1,0.2,0.0,0.1,0.4,0.3,0.4,267.0,0.4,0.2,0.2,0.2,0.0,11.10,6.9,1.0,291.1,1.0,0.00,1.0,3900.0,1300.0,0.0,0.0,92091.0,2.0,2.0,1.0,11.10,1.0,0.0,1.0,5.0,36.9,13.6,0.0,358.21,0.0,1.0,1.0,1.0,0.5223,0.0697,0.9799,0.9096,0.6201,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0319,1.1980,1.9277,3.3665,8.1240,36.0,1.0,0.0,1.0,0.0,0.0,11600.0,NaN,NaN,NaN,0.0,2.0,NaN,NaN,NaN,2.0,NaN,NaN,NaN,2.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,504.0,1.0,2.0,0.0
445973,0.0,1.0,0.0,2.0,0.0,333.83,1.0,1.0,0.0,1.0,0.0,1.0,44148.0,1.0,0.0,0.0,1.0,0.4502,0.1974,0.9863,0.0755,0.3792,0.9847,0.9430,0.0022,0.9981,0.7883,0.9981,0.1736,0.6258,0.4330,0.6207,22.0,14.8,9.5,10.2,1.6,12.0,63.8,0.1,40.9,18.4,55.8,31984.0,16.6,7.8,6.2,8.2,61715.0,40893.0,358674.0,292462.0,31984.0,60827.0,70250.0,136920.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,2.0,3.0,5.0,0.0,0.0,1.0,0.0,1.0,11.10,11.10,40.658566,-73.95064,44131.0,1.0,0.0,0.1,0.3,0.2,0.1,0.2,0.0,0.1,0.4,0.3,0.4,267.0,0.4,0.2,0.2,0.2,0.0,11.10,6.9,1.0,291.1,1.0,0.00,1.0,3900.0,1300.0,0.0,0.0,92091.0,2.0,2.0,1.0,11.10,1.0,0.0,1.0,5.0,36.9,13.6,0.0,358.21,0.0,1.0,1.0,1.0,0.5223,0.0697,0.9799,0.9096,0.6201,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0319,1.1980,1.9277,3.3665,8.1240,36.0,1.0,0.0,1.0,0.0,0.0,11600.0,NaN,NaN,NaN,0.0,2.0,NaN,NaN,NaN,2.0,NaN,NaN,NaN,2.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,504.0,1.0,2.0,0.0
445974,0.0,1.0,0.0,2.0,0.0,333.83,1.0,1.0,0.0,1.0,0.0,1.0,44148.0,1.0,0.0,0.0,1.0,0.4502,0.1974,0.9863,0.0755,0.3792,0.9847,0.9430,0.0022,0.9981,0.7883,0.9981,0.1736,0.6258,0.4330,0.6207,22.0,14.8,9.5,10.2,1.6,12.0,63.8,0.1,40.9,18.4,55.8,31984.0,16.6,7.8,6.2,8.2,61715.0,40893.0,358674.0,292462.0,31984.0,60827.0,70250.0,136920.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,2.0,3.0,5.0,0.0,0.0,1.0,0.0,1.0,11.10,11.10,40.658566,-73.95064,44131.0,1.0,0.0,0.1,0.3,0.2,0.1,0.2,0.0,0.1,0.4,0.3,0.4,267.0,0.4,0.2,0.2,0.2,0.0,11.10,6.9,1.0,291.1,1.0,0.00,1.0,3900.0,1300.0,0.0,0.0,92091.0,2.0,2.0,1.0,11.10,1.0,0.0,1.0,5.0,36.9,13.6,0.0,358.21,0.0,1.0,1.0,1.0,0.5223,0.0697,0.9799,0.9096,0.6201,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0319,1.1980,1.9277,3.3665,8.1240,36.0,1.0,0.0,1.0,0.0,0.0,11600.0,NaN,NaN,NaN,0.0,2.0,NaN,NaN,NaN,2.0,NaN,NaN,NaN,2.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,504.0,1.0,2.0,0.0
445975,0.0,1.0,0.0,2.0,0.0,333.83,1.0,1.0,0.0,1.0,0.0,1.0,44148.0,1.0,0.0,0.0,1.0,0.4502,0.1974,0.9863,0.0755,0.3792,0.9847,0.9430,0.0022,0.9981,0.7883,0.9981,0.1736,0.6258,0.4330,0.6207,22.0,14.8,9.5,10.2,1.6,12.0,63.8,0.1,40.9,18.4,55.8,31984.0,16.6,7.8,6.2,8.2,61715.0,40893.0,358674.0,292462.0,31984.0,60827.0,70250.0,136920.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,2.0,3.0,5.0,0.0,0.0,1.0,0.0,1.0,11.10,11.10,40.658566,-73.95064,44131.0,1.0,0.0,0.1,0.3,0.2,0.1,0.2,0.0,0.1,0.4,0.3,0.4,267.0,0.4,0.2,0.2,0.2,0.0,11.10,6.9,1.0,291.1,1.0,0.00,1.0,3900.0,1300.0,0.0,0.0,92091.0,2.0,2.0,1.0,11.10,1.0,0.0,1.0,5.0,36.9,13.6,0.0,358.21,0.0,1.0,1.0,1.0,0.5223,0.0697,0.9799,0.9096,0.6201,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0319,1.1980,1.9277,3.3665,8.1240,36.0,1.0,0.0,1.0,0.0,0.0,11600.0,NaN,NaN,NaN,0.0,2.0,NaN,NaN,NaN,2.0,NaN,NaN,NaN,2.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,504.0,1.0,2.0,0.0
445976,0.0,1.0,0.0,2.0,0.0,333.83,1.0,1.0,0.0,1.0,0.0,1.0,44148.0,1.0,0.0,0.0,1.0,0.4502,0.1974,0.9863,0.0755,0.3792,0.9847,0.9430,0.0022,0.9981,0.7883,0.9981,0.1736,0.6258,0.4330,0.6207,22.0,14.8,9.5,10.2,1.6,12.0,63.8,0.1,40.9,18.4,55.8,31984.0,16.6,7.8,6.2,8.2,61715.0,40893.0,358674.0,292462.0,31984.0,60827.0,70250.0,136920.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,2.0,3.0,5.0,0.0,0.0,1.0,0.0,1.0,11.10,11.10,40.658566,-73.95064,44131.0,1.0,0.0,0.1,0.3,0.2,0.1,0.2,0.0,0.1,0.4,0.3,0.4,267.0,0.4,0.2,0.2,0.2,0.0,11.10,6.9,1.0,291.1,1.0,0.00,1.0,3900.0,1300.0,0.0,0.0,92091.0,2.0,2.0,1.0,11.10,1.0,0.0,1.0,5.0,36.9,13.6,0.0,358.21,0.0,1.0,1.0,1.0,0.5223,0.0697,0.9799,0.9096,0.6201,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0319,1.1980,1.9277,3.3665,8.1240,36.0,1.0,0.0,1.0,0.0,0.0,11600.0,NaN,NaN,NaN,0.0,2.0,NaN,NaN,NaN,2.0,NaN,NaN,NaN,2.0,2.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,504.0,1.0,2.0,0.0

In [17]:
grf = CausalForest()

In [35]:
grf.fit(X,W,Y)

ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

In [19]:
W

0           0.0
1           1.0
2           2.0
3           3.0
4           4.0
          ...
445972    246.0
445973    247.0
445974    248.0
445975    249.0
445976    250.0
Name: shifted_days_from_start, Length: 445977, dtype: float64

In [32]:
Y.max()

11.582127647883352

In [33]:
Y.min()

2.995732273553991

In [34]:
W

0           0.0
1           1.0
2           2.0
3           3.0
4           4.0
          ...
445972    246.0
445973    247.0
445974    248.0
445975    249.0
445976    250.0
Name: shifted_days_from_start, Length: 445977, dtype: float64